<?php
  # file: lang/HR/admin.php3.HR.inc
  # Translation by Nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver : 19991008

  $No_admin_menu_access = "Nije Vam dozvoljeno administriranje sustava!" ; 
  $Icd_code_type = "ICD code type" ; #not translated yet! 
  $Graphics_enhanced = "Grafièki obogaæeno" ;
  $Disabled = "Onemoguæeno" ;
  $Enabled = "Dopu¹teno" ;
  $Scheduling_start_time = "Poèetak rasporeda" ;
  $Scheduling_end_time = "Kraj rasporeda" ;
  $Configure = "Konfiguriraj" ;
  $Reset = "Resetiraj" ;
  $Configuration_complete = "Konfiguracija zavr¹ena" ;
  $Return_adm_menu = "Povratak na administratorski izbornik" ;
  $Reinitialize_database = "Reinicijalizacija baze podataka" ;
  $Are_you_sure = "Jeste li SIGURNI da ¾elite" ;
  $Irreversable_process = "Ovo je neporatan proces!" ;
  $First_initialization = "Kliknite odvje ako je ovo prva inicijalizacija" ;
  $Continue = "Nastavak" ;
  $Cancel = "Prekini" ;
  $Erasing_old_db = "Brisanje stare baze podataka" ;
  $Error_accessing_sql = "Gre¹ka prilikom pristupanja bazi podataka" ;
  $Creating_new_db = "Stvaranje nove baze podataka" ;
  $Creating_tables = "Stvaranje tablica" ;
  $Administration_menu = "Administratcijski izbornik" ;
  $Update_config = "Obnovi konfiguraciju" ;
  $User_maintenance = "Korisnci" ;
  $Return_main_menu = "Povratak na glavni izbor" ;
  $DEFAULT = "IZVORNO";
    // 19990830
  $SELECTED = "ODABRANO";
  $Update_Configuration = "Obnavljanje konfiguracije";
    // 19991007
  $Calendar_overbooking = "Kalendar je prebukiran";

?>
