<?php
  # file : lang/HR/API.HR.inc
  # code : jeff b <jeff@univrel.pr.uconn.edu>
  # lic  : GPL
  # Translation by nikola <nikola@mamef.mef.hr>
  # ver  : 19991201

  $DEBUG_IS_ON = "DEBUG je ukljuèen";
  $Return_to_the_Main_Menu = "Povratak na glavni izbor";
  $Return_to_Previous_Menu = "Povratak na prethodni izbor";
  $lang_main = "Glavni"; // alt tag for main menu button
  $lang_exit = "Izlaz"; // alt tag for logout button
  $RETURN_TO_MENU          = "POVRATAK NA IZBOR";
  $NONE_SELECTED           = "NIJE ODABRANO";
  $SELECTED                = "SELECTED"; // must NOT be translated
  $lang_coded_by           = "programirao "; 
  $NO_RESULT_OF_QUERY      = "NEMA REZULTATA VA©EG UPITA";
  $Entered_incorrect_NamePasswd =
    "Unijeli ste krivo korisnièko ime ili ¹ifru!";
  $Possible_Cookies_Have_Expired =
    "Takoðer je moguæe da je isteklo trajanja va¹eg 'kolaèiæa'. Molim
     Vas prijavite se ponovo ili zamolite administratora sistema da 
     produ¾i trajanje kolaèiæa.";
  $Login_Screen            = "Poèetak rada";
    // 19990824
  $Add                     = "Dodaj";
  $Adding                  = "Dodavanje";
  $Clear                   = "Obir¹i";
    // 19990917
  $Return_to               = "Vrati se na";
  $Main_Menu               = "Glavni izbor";
  $Modify                  = "Izmjeni";
  $Modifying               = "Mijenjanje";
  $Done                    = "gotovo";
  $Menu                    = "Izbor";
  $Deleting                = "Brisanje";
  $Update_Delete_Another   = "Obnovi/Izbri¹i drugog";
  $Deleted                 = "izbrisano";
  $Abandon_Addition        = "Odustani od nadopuna";
  $Abandon_Modification    = "Odustani od izmjena";
  $Update                  = "Obnovi";
  $Remove_Changes          = "Izbaci promjene";
  $Exporting_data          = "Izvoz podataka";
  $Export                  = "Izvoz";
  $ERROR                   = "GREP©KA";
  $Action                  = "Akcija";
  // 19990920
  $lang_ALL                = "SVE";
  // 19990921
  $lang_ADD                = "DODAJ";  
  $lang_MOD                = "MODUL";
  $lang_DEL                = "BRI©I";
  // 19990922
  $No_Record_Found         = "Nije naðen $record_name koji ispunjaba uvijet.";
  $lang_back               = "nazad";
  // 19990924
  $lang_HELP               = "POMOÆ";
  $Module                  = "Modul";
  $Manage_Patient          = "Ureðivanje pacijenat";
  // 19991005
  $Week_Of                 = "Tjedan";
  // 19991013
  $Export_Database         = "Izvedi bazu podataka";
  // 19991026
  $Export_Data             = "Izvedi podatke";
  // 19991102
  $lang_months             = array ("", // null for 0
                                    "Sij",
                                    "Velj",   
                                    "O¾u",
                                    "Tra",
                                    "Svi",
                                    "Lip",
                                    "Srp",
                                    "Kol",
                                    "Ruj",
                                    "Lis",
                                    "Stu",
                                    "Pro" );
  $lang_days               = array ("", // null for 0
                                    "Ned",
                                    "Pon",
                                    "Uto",
                                    "Sri",
                                    "Èet",
                                    "Pet",
                                    "Sub" ); 
  // 19991116
  $midnight                = "ponoæ";
  $noon                    = "podne";
  // 19991122
  $Patient                 = "Pacijent";
  $lang_no                 = "ne";
  $lang_yes                = "da";
  $lang_go                 = "idi";  
  $State_Providence        = "®upanija";
  $Return_to_Menu          = "Povratak na izbor";
  // 19991201
  $Post                    = "Po¹alji";
?>
