<?php
  # file: lang/HR/authenticate.php3.HR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by nikola <nikola@mamef.mef.hr>

  $Error = "GRE©KA" ;
  $Return_to_the_login_screen = "Povratak na poèetni prozor";
  $Incorrect_name_password= "Unijeli ste krivo korisnièko ime ili ¹ifru. <BR>
   Ako mislite da je ova poruka nastala zbog gre¹ke, zabilje¾ite uvijete <BR>
   koji su do nje doveli, te se sa tim podatcima javit administratoru <BR>
   va¹eg sustava.";
?>
