<?php
  # file: lang/HR/book_appointment.php3.HR.inc
  # desc: book appointment croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr> not entirely translated!!
  # lic : GPL

  $Add_Appointment                     = "Naruèivanje";
  $lang_day                            = "dan";
  $lang_week                           = "tjedan";
  $lang_prev                           = "pro¹li";
  $lang_next                           = "sljedeæi";
  $Current_Date_is                     = "Dana¹nji datum je";
  $this_date_occurs_in_the_past        = "ovaj datum je veæ pro¹ao";
  $Current_Patient                     = "Trenutni pacijent";
  $Room                                = "Soba";
  $Check_Room                          = "Provjerite sobu";
  $Try_Again                           = "Poku¹ajte ponovo";
  $Date                                = "Datum";
  $The_selected_room_is_free_all_day   = "Odabrana soba je slobodna èitav dan.";
  $TIME                                = "VRIJEME";
  $NO_PREFERENCE                       = "SVEJEDNO";
  $Patient                             = "Pacijent";
  $Time                                = "Vrijeme";
  $lang_hour                           = "sat";   // singular
  $lang_hours                          = "sati";  // plural
  $lang_min_abbrev                     = "min";    // abbreviated minutes
  $lang_h                              = "h";      // single letter for hours
  $lang_m                              = "m";      // single letter for minutes
  $Duration                            = "Trajanje";
  $Physician                           = "Lijeènik";
  $Note                                = "Zabilje¹ka";
  $Adding_Appointment                  = "Dodavanje termina";
  // 19991013
  $Facility                            = "Slu¾ba/Odjel";
  $Change_Room                         = "Provjerite sobu";
?>
