<?php
  # file: lang/HR/call-in.php3.HR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by nikola <nikola@mamef.mef.hr>
  # Mod : 19990922

  $Call_In              = "Poziv";
  $Name                 = "Ime";
  $Last                 = "Prezime";
  $First                = "Prvo";
  $Middle               = "Srednje";
  $Contact_Information  = "Obavijestiti";
  $Home_Phone           = "Kuæni br. telefona";
  $Work_Phone           = "Br. telefona na poslu";
  $Took_Call            = "Poziv primio";
  $Date_of_Birth        = "Datum roðenja";
  $Complaint            = "Poruka";
  $Facility             = "Odjel/Slu¾ba";
  $Physician            = "Lijeènik";
  $Patient_Menu         = "Izbornik pacijenti";
  $Call_In_Menu         = "Izbornik za pozive";
  $Main_Menu            = "Glavni izbor";
  $NOT_IMPLEMENTED_YET  = "NIJE JO© UGRAÐENO";
  $Date_of_Call         = "Datum poziva";
  $Home_Work_Phone      = "Br. telefona kuæni/na poslu";
  $Action               = "Akcija";
  $VIEW                 = "POGLED";
  $BOOK                 = "KNJIGA";
  // 19990920
  $Old                  = "Stari";
  $All                  = "Svi";
  $Current              = "Trenutni";
?>
