<?php
  # file: lang/HR/cpt.php3.HR.inc
  # desc: CPT codes croatian (HR) language module
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

// 19990927 - mark l
  $Clear        = "Obri¹i";

  $record_name                      = "CPT kod";

  $CPT_Code                         = "CPT kod";
  $CPT_Name_Internal                = "CPT Ime (Interno)";
  $CPT_Name_External                = "CPT Ime (Externo)";
  $Relative_Value                   = "Relativna vrijednost";
  $Example                          = "npr.";
  $Type_of_Service                  = "Tip usluge";
  $Internal_Name                    = "Interno Ime";
?>
