<?php
  # file: lang/HR/custom_records.php3.HR.inc
  # desc: custom records croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name = "Custom Records";

  $Must_select_a_patient       =
      "To nemo¾ete uèiniti dok ne odaberete pacijenta!";
  $Must_select_a_template      =
      "To nemo¾ete uèiniti dok ne odaberete obrazac!";
  $Select_a_Patient            = "Odaberite pacijenta";
  $No_records_for_this_patient = "Nema zapisa za ovog pacijenta.";
  $Date_Added                  = "Datum je dodan";
  $Form                        = "Formular";
?>
