<?php
  # file: lang/HR/db_maintenance.php3.HR.inc
  # desc: database maintenance menu croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver : 19991102

  $Database_Maintenance            = "Odr¾avanje baze podataka";
  $CPT_Procedural_Codes            = "Kodovi CPT/Procedura";
  $CPT_Procedural_Modifiers        = "Izmjene CPT/Procedura";
  $Formulary_Pharmacy_Module       = "Modul Formulara (Farmaceutski)";
  $ICD_Codes                       = "ICD 9/10 Kodovi";
  $Insurance_Companies             = "Osiguravajuæa dru¹tva";
  $Insurance_Company_Groups        = "Osiguravajuæe grupe";
  $Physicians                      = "Lijeènici";
  $Physician_Degrees               = "Lijeènièke titule";
  $Physician_Groups                = "Grupe lijeènika";
  $Physician_Specialties           = "Specijalnosti lijeènika";
  $Physician_Statuses              = "Statusi lijeènika";
  $Place_of_Service_Facilities     = "Odjel/Slu¾ba (<I>Mjesta usluge</I>)";
  $Rooms                           = "Sobe";
  $Scheduling_Locations            = "Lokacije za termine";
  $Type_of_Service                 = "Oblici usluga";
  $Templates_for_Simple_Reports    = "Predlo¹ci jednostavnih izvje¹taja";
  $You_dont_have_access_for_this_menu = "Nemate pristup tom izborniku.";
  $Selectable_Printers             = "Dostupni pisaèi" ;
  $Fixed_Forms                     = "Odreðeni formulari" ;
  $Custom_Patient_Record_Templates = "Custom predlo¾ci zapisa pacijanta" ;
  $Diagnosis_Families              = "Vrste dijagnoza" ;

?>
