<?php
  # file: lang/HR/degrees.php3.HR.inc
  # desc: physician degrees croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # mods: max k <amk@span.ch>
  # Translation ba nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver : 19991007

  $record_name="Titule lijeènika";


  $Degree_Title                        = "Naziv titule";
  $Degree_Title_Example                = "npr. Lijeènik internist,...";
  $Degree_Name                         = "Naziv ";
  $Degree_Name_Example                 = "npr. Dr., Mr., ...";
  $Date_Last_Modified                  = "Datum zadnje promjene";
  $Degree                              = "Titula";
  $Description                         = "Opis";
  $No_degrees_are_currently_in_the_database =
     "Trenutno nema niti jedna titula u bazi podataka.";
?>
