<?php
  # file: lang/HR/episode_of_care.php3.HR.inc
  # desc: episode of care croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name = "Posjeti lijeèniku (Tok lijeèenja)";

  $Must_select_record_to_modify =
          "Morate odabrati zapis koji ¾elite mijenjati.";
  $Return_to_Menu              = "Povratak na izbor";
  $Description                 = "Opis";
  $Related_to_Pregnancy        = "Povezano sa trudnoæom?";
  $Date_of_First_Occurance     = "Poèetak simptoma dana";
  $Related_to_Employment       = "Povezano sa poslom koji obavlja";
  $Date_of_Last_Similar        = "Zadnje sliène smetnje";
  $Related_to_Automobile       = "Povezano sa  prometnom nezgodom";
  $Referring_Physician         = "Drugi lijeènik";
  $Related_to_Other_Cause      = "U odnosu na drugi uzrok";
  $Facility                    = "Odjel/Slu¾ba"; 
  $Diagnosis_Family            = "Vrsta dijagnoze";
  $Episode_Type                = "Vrsta smetnji";
  $lang_acute                  = "akutni";
  $lang_chronic                = "kronièni";
  $lang_chronic_recurrent      = "kronièni rekurentni";
  $lang_historical             = "u povijesti";
  $Automobile_Related_Information = 
           "Podaci u vezi sa prometnom nezgodom";
  $Auto_Insurance              = "Osiguravatelj od auto. odgovornosti";
  $Case_Number                 = "Sluèaj br.";
  $Address                     = "Adresa";
  $Line_1                      = "Red 1";
  $Line_2                      = "Red 2";
  $Contact_Name                = "Slu¾bena osoba";
  $Contact_Phone               = "Telefon ";
  $City                        = "Grad";
  $St_Pr                       = "®upanija";
  $Postal_Code                 = "Br. po¹te";
  $Email_Address               = "Email Adresa";
  $Country                     = "Dr¾ava";
  $Employment_Related_Information =
            "Podatci o poslu koji obavlja pacijent";
  $Name_of_Employer            = "Poslodavac";
  $File_Number                 = "File Number";
  $Pregnancy_Related_Information = 
            "Podatci o trudnoæi";
  $Length_of_Cycle             = "Duljina ciklusa (dani)";
  $Last_Menstrual_Period       = "Zadnja menstruacija";
  $Gravida                     = "Gravida";
  $Date_of_Confinement         = "Datum zaèeæa";
  $Para                        = "Para";
  $Miscarries                  = "Spontanih pobaèaja";
  $Abortions                   = "Izazvanih pobaèaja";
  $Other_Related_Information   = "Ostali podatci";
  $More_Information            = "Druge informacije";
  $Must_specify_patient        = "Morate odabrati pacijenta.";
  $Starting_Date               = "Od datuma";
  $Description                 = "Opis";
  $No_record_for_patient       = "Nema zapisa za odabranog pacijenta.";
?>
