<?php
  # file: lang/HR/phygroup.php3.HR.inc
  # desc: physician group croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name = "Grupa lijeènika";

  $Physician_Group_Name               = "Naziv grupe lijeènika";
  $Default_Facility                   = "Njihova slu¾ba/odjel";
  $Group_Name                         = "Ime grupe";
?>
