<?php
  # file: lang/HR/physician_week_view.php3.HR.inc
  # desc: physician weekly view croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $Physician_Weekly_View                   = "Tjedni pogled na lijeènika";
  $back_one_week                           = "prethodni";
  $forward_one_week                        = "sljdeæi";
  $No_Physician_Selected                   = "Nijedan lijeènik nije odabran"; 
  $Physician                               = "Lijeènik";
?>
