<?php
  # file: lang/HR/physician.php3.HR.inc
  # desc: physician maintenance menu croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation : nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver : 19991104

  $Add_Physician                   = "Dodavanje lijeènika"  ;
  $Last_name                       = "Ime"      ;
  $First_name                      = "Prvo ime"     ;
  $Title                           = "Titula"          ;
  $Middle_Name                     = "Srednje ime"    ;
  $Practice_Name                   = "Naziv ambulante "  ;
  $Primary_Address_Line            = "Ulica"    ;
  $Primary_Address_City            = "Grad"    ;
  $Primary_Address_State           = "®upanija"   ;
  $Primary_Address_Zip             = "Po¹tanski broj"     ;
  $Primary_Address_Phone           = "Broj telefona"   ;
  $Primary_Address_Fax             = "Broj fax-a"     ;
  $Secondary_Address_Line          = "Ulica"  ;
  $Secondary_Address_City          = "Grad"  ;
  $Secondary_Address_State         = "Naselje" ;
  $Secondary_Address_Zip           = "Po¹tanski broj"   ;
  $Secondary_Address_Phone         = "Broj telefona" ;
  $Secondary_Address_Fax           = "Broj fax-a"   ;
  $Email_Address                   = "E-mail adresa"           ;
  $Cellular_Phone                  = "Broj mobitela"          ;
  $BeeperPager                     = "Broj bipera ili pagera"     ;
  $UPIN_Number                     = "JMBG"         ;
  $Social_Security                 = "Broj osigurane osobe"     ;
  $Degree                          = "Stupanj"              ;
  $Specialty                       = "Specijalizacija"           ;
  $Internal_ID                     = "Interna ¹ifra"         ;
  $Status                          = "Status"              ;
  $Reference                       = "Reference"           ;
  $Number_of_Referrals             = "Number of Referrals" ;
  $Primary_care_provider           = "Primary care provider" ;
  $Referring                       = "Referring"           ;
  $NULL                            = "NULL"                ;
  $Number_of_Referrals             = "Number of Referrals" ;
  $Referral_Amount                 = "Referral Amount"     ;
  $S_charged                       = "\kn zaraðeno"          ;
  $S_received                      = "\kn naplaæeno"         ;
  $Add                             = "Dodaj"                 ;
  $Clear                           = "Obri¹i"               ;
  $Adding_Physician                = "Dodaj lijeènika"    ;
  $Adding                          = "Dodavanje"              ;
  $Done                            = "Gotovo"                ;
  $ERROR                           = "GRE©KA"               ;
  $Physician                       = "Lijeènik"           ;
  $Modify_Physician                = "Izmjena podataka o lijeèniku" ;
  $Please_use_the_MODIFY_form_to_MODIFY_someone = "Molim, koristite Formular za izmjene kada ¾elite izmjeniti neèije podatke." ;
  $Return_to_the_Main_Menu         = "Povratak na glavni izbor" ;
  $Update                          = "Obnovi"                  ;
  $Abandon_Modification            = "Odustani od izmjena"    ;
  $Modifying_Physician             = "Mijenjanje podataka o lijeèniku"     ;
  $Modifying                       = "Mijenjanje"               ;
  $Deleting_Physician              = "Brisanje lièenika"      ;
  $RESULT                          = "REZULTAT"                  ;
  $Delete_Another                  = "Izbi¹i drugog"          ;
  $Physician_Display               = "Prikaz podataka o lijeèniku"       ;
  $You_must_specify_an_id          = "Morate napisati internu ¹ifru"  ;
  $Return_to_the_Physician_Menu    = "Povratak na izbor o lijènicima" ;
  $NONE_SELECTED                   = "NI©TA NIJE ODABRANO"           ;
  $Physicians                      = "Ljeènici"              ;
  $Last_Name                       = "Prezime"               ;
  $First_Name                      = "Ime"              ;
  $Degrees                         = "Stupanj"                 ;
  $Action                          = "Kreni"                  ;
  $VIEW                            = "POGLEDAJ"                    ;
  $MOD                             = "IZMJENE"                     ;
  $DEL                             = "OBRI©I"                     ;
  $No_physicians_found_with_that_criteria = " Nije pronaðeno lijeènika sa zadanim podatcima." ;



?>
