<?php
  # file: lang/HR/phystatus.php3.HR.inc
  # desc: physician status croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # some mods: max k <amk@span.ch>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver : 19991007

  $record_name               = "Status ijeènika";

  $Status                    = "Status";
  $Update                    = "Obnovi";
  $Remove_Changes            = "Izbri¹i promjene";
  $Abandon_Modification      = "Napusti izmjenu";
  $Modifying                 = "Mjenjanje";
  $Done                      = "Gotovo";
  $Return_to_Previous_Menu   = "Povratak na prethodni izbornik";
  $Return_to_the_Main_Menu   = "Povratak na glavni izbor";
  $Deleting                  = "Brisanje";
  $Deleted                   = "Obrisano";
  $RESULT                    = "REZULTAT";
  $Update_Delete_Another     = "Obnovi ili obri¹i drugog";
  $Return_to                 = "Povratak na";
  $RETURN_TO_MENU            = "POVRATAK NA IZBOR";
  $No_Record_Found           = "Nijedan zapis nije naðen";
?>
