<?php
  # file: lang/HR/physician_day_view.php3.HR.inc
  # desc: physician daily view croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $Physician_Daily_View                    = "Dnevni progled na lijeènika";
  $back_one_day                            = "prethodni";
  $forward_one_day                         = "sljedeæi";
  $No_Physician_Selected                   = "Nijedan lijeènik nije odabran"; 
  $Physician                               = "Lijeènik";
?>
