<?php
  # file: lang/HR/progress_notes.php3.HR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name                  = "Zabilje¹ke o toku lijeèenja";
  $Module                       = "Modul";
  $ERROR                        = "GRE©KA";
  $Must_Specify_A_Patient       = "Morate odabrati pacijenta!";
  $Entry                        = "Unos";
  $Manage_Patient               = "Voðenje pacijenta";
  $View_Modify                  = "Pogled/Izmjene";
  $Applicable_Date              = "Primjenjiv datum";

    // the actual progress parts (with underlines)
  $Subjective                   = "<U>S</U>ubjektivno";
  $Objective                    = "<U>O</U>bjektivno";
  $Assessment                   = "Pr<U>O</U>cjena";
  $Plan                         = "<U>P</U>lan";
  $Interval                     = "<U>I</U>nterval";
  $Education                    = "<U>E</U>dukacija";
  $Prescription                 = "<U>R</U>ecepti";

  $Add                          = "Dodaj";
  $Clear                        = "Obri¹i";
  $Abort_Addition               = "Napusti dodato";
  $Adding                       = "Dodavanje";
  $Done                         = "gotovo";
  $FAILED                       = "NIJE USPJELO";
  $Must_Call_With_Patient_ID    = "Morate pozvati tu funkciju sa ".
                                  "pacijent odabran.";
  $Modify                       = "Izmjeni";
  $Change                       = "Promjeni";
  $Restore                      = "Obnovi";
  $Modifying                    = "Mijenjanje";
  $View                         = "Pogled";
  $Menu                         = "Izbor";
  $Specify_Notes_to_Display     = "Morate naznaèiti zabilje¹ke o lijeèenju  ".
                                  "da bi bile prikazane.";
  $Modify_Notes                 = "Izmjeni zabilje¹ke";
  $Patient                      = "Pacijent";
  $This_Patient_Has_No_Notes    = "Ovaj pacijent nema zabilje¹ki do dana¹njeg dana.";
  $Existing                     = "Izlazim";
?>
