<?php
  # file: lang/HR/roomequip.php3.HR.inc
  # desc: room equipment croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name                       = "Oprema ambulante";
  $Name_of_Equipment                 = "Naziv opreme";
  $Description                       = "Opis";
  $Equipment                         = "Oprema";
?>
