<?php
  # file: lang/HR/room.php3.HR.inc
  # desc: room (scheduling location) croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name = "Oprema ambulante";

  $Room_Name                      = "Ambulanta";
  $Location                       = "Lokacija";
  $Room_Description               = "Opis ambulante";
  $Default_Physician              = "Lijeènik ambulante";
  $Surgery_Equipped               = "Kirur¹ka oprema?";
  $Is_Booking_Enabled             = "Dopu¹teno naruèivanje?";
  $IP_Address                     = "IP adresa raèunala";
  $For_Future_Use                 = "za buduæe kori¹tenje";
  $For_Scheduling                 = "za raspored";
  $Description                    = "Opis";
?>
