<?php
  # file: lang/HR/Rx.php3.HR.inc
  # desc: prescription module croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name = "Recept";

  $Must_Have_Patient_For_Prescriptions =
    "Trebate imati pacijenata da mo¾ete koristit recepte.";
  $No_Access_To_This_Patient           =
    "Vi nemate dozvoljen pristup zapisima ovog pacijenta.";
  $Display                             = "Poka¾i";
  $Patient                             = "Pacijent";
  $Drug                                = "Lijek";
  $Dosage                              = "Doza";
  $Starting_Date                       = "Poèetni datum";
  $In_Days                             = "dana";
  $Infinite                            = "0 = trajno";
  $Refills                             = "Dodatno";
  $Substitution                        = "Zamjena";
  $May_Not_Substitute                  = "nemo¾e zamjeniti";
  $May_Substitute                      = "mo¾e zamijeniti";
  $Manage_Prescriptions                = "Rad s receptima";
  // 19991002
  $Duration                            = "Trajanje";
?>
