<?php
  # file: lang/HR/select_printer.php3.HR.inc
  # desc: Selectable printer management croatian (HR) language file
  # code: max k <amk@span.ch>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver : 19991020

  $record_name = "Odabir printera za ispis" ;

  $Selectable_Printer    = "Printer"   ;
  $Printer_Name          = "Ime printera"         ;
  $Printer_Host          = "Ranèunalo (sa printerom)"         ;
  $Access_Level          = "Nivo pristupa"         ;
  $Description           = "Opis"          ;
  $Add                   = "Dodaj"                  ;
  $Clear                 = "Obir¹i"                ;
  $Adding                = "Dodavanje"               ;
  $Done                  = "Gotovo"                 ;
  $ERROR                 = "GRE©KA"                ;
  $Return_to             = "Natrag na"            ;
  $Menu                  = "Izbor"                 ;
  $Modify                = "Izmjene"               ;
  $Please_use_MODIFY     = "Molim Vas koristite Izmjene za mijenjanje " ;
  $Return_to_the_Main_Menu = "Povratak na glavni izbor" ;
  $RESULT                = "REZULTAT"               ;
  $Abandon_Addition      = "Napusti dodano"     ;
  $Update                = "Obnavljanje"               ;
  $Remove_Changes        = "Obri¹i izmjene"       ;
  $Abandon_Modification  = "Napusti izmjene" ;
  $Modifying             = "Mjenjanje"            ;
  $Deleting              = "Brisanje"             ;
  $Deleted               = "Obrisano"              ;
  $Update_Delete_Another = "Obnivi ili obri¹i drugog" ;
  $Export                = "Izvoz"               ;
  $Exporting_data        = "Izoz podataka"       ;
  $Action                = "Kreni"               ;
  $Printer               = "Printer"              ;
  $Host                  = "Raèunalo"                 ;
  $MOD                   = "IZMJENI"                  ;
  $DEL                   = "OBRI©I"                  ;
  $No_Record_Found       = "Nijedan zapis nije naðen"      ;
  $Current_Contents      = "Trenutni sadr¾aj"      ;
  $For_Reference         = "Za referencu"        ;

?>
