<?php
  # file: lang/HR/simplerep.php3.HR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # module: max k <amk@span.ch>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver: 19991103

  $record_name = "Jednostavni nalaz";

  $Add                         = "Dodaj";
  $Clear                       = "Obri¹i"; 
  $Label                       = "Oznaka";
  $Category                    = "Kategorija";
  $Text                        = "Tekst";
  $Abandon_Addition            = "Napusti izmjenu";
  $Adding                      = "Dodavanje";
  $Return_to                   = "Povratak na";
  $Modify                      = "Izmjeni";
  $Please_use_MODIFY           = "Molim Vas koristite formular za Izmjene";
  $Return_to_the_Main_Menu     = "Povratak na glavni izbor";
  $Update                      = "Obnovi";
  $Remove_Changes              = "Obri¹i promjenjeno";
  $Abandon_Modification        = "Napusti izmjennjeno";
  $Modifying                   = "Mjenjanje";
  $Done                        = "gotovo";
  $ERROR                       = "GRE©KA";
  $Menu                        = "Izbor";
  $Deleting                    = "Brisanje";
  $Deleted                     = "obrisano";
  $Update_Delete_Another       = "Obnovi/Obri¹i drugog";
  $Must_Have_Patient_to_Make_Reports =
    "Morate imati pacijenta da bi ste pisali nalazd!";
  $Choose_Report_for_Patient   = "Odaberite nalaz za pacijenta";
  $Patient                     = "Pacijent";
  $Manage_Patient              = "Voðenje pacijenta";
  $Action                      = "Kreni";
  $Mr                          = "G.";   // 19990926
  $Mrs                         = "Gða.";
  $Report                      = "Izvje¹taj";
  $Physician                   = "Lijeènik";
  $Facility                    = "Facility";
  $Proceeding                  = "nastavljam dalje";  //  19990927
  $Proceed                     = "Nastavi dalje";
  $Please_choose               = "Molim Vas odaberite ne¹to za svakog"; // 19990927
  $Before                      = "prije";
  $Return_to_report_selection  = "Povratak na Nalaze"; // 19990928
  $Destinatary_is              = "©alje se";
  $Delivery_Method             = "Naèin dostave";
  $NONE_SELECTED               = "NIJE ODABRANO";
  $The_Patient                 = "Pacijent";
  $A_Physician                 = "Lijeènik";
  $An_Insurer                  = "Osiguranje";
  $Other                       = "Drugi";
  $Printer                     = "Printer";
  $Fax                         = "Fax"; 
  $E_mail                      = "E-mail";
  $Edit_report_for_patient     = "Pisanje izvje¹taja za pacijenta";
  $Phone                       = "Telefon";  //19991005
  $Datequalif                  = "";
  $Help_for_simple_reports     = "Pomoæ - za jednostavne nalaze";
  $Edit_add_simple_reports     = "Dodaj ili izmjeni jednoastavni nalaz";  // 19991007
  $Patients_primary_insurer    = "Primarno osiguranje";   // 19991008
  $Patients_secundary_insurer  = "Dodatno osiguranje";
  $Patients_tertiary_insurer   = "Dodatno osiguranje";
  $Select_from_contact_list    = "Odabir iz liste kontakata";
  $Patients_primary_employer   = "Pacijentov poslodavac";
  $Patients_secundary_employer = "Drugi poslodavac pacijenta";
  $No_delivery_method_selected = "Nije odabran naèin dostave!"; // 19991008
  $Print                       = "Ispis";
  $To                          = "Kome";                               // 19991009
  $Patient_has_no_fax          = "Na¾alost, pacijent nema valjani broj fax-a";
  $Send                        = "Po¹alji";
  $Patient_has_no_email        = "Na¾alost, pacijnt nema valjanu e-mail adresu";
  $A_physician_must_sign_his_own_name = "Lijeènik se mora sam potpisati";
  $Verification_Key            = "Kljuè (Verification Key)";
  $Suppress_headers            = "Izostavi zaglavlje";
  $Show_full_titles            = "Prika¾i punu titulu lijeènika";
  $Mailed                      = "Poslano"   ;
  $From                        = "Od"     ;
  $Copy_to                     = "Kopiju po¹alji"  ;
  $Subject                     = "Sadr¾aj"  ;
  $Male                        = "Mu¹ko"     ;
  $Female                      = "®ensko"   ;
  $Adult                       = "Odrasli"    ;
  $Child                       = "Djete"    ;
  $Return_to_reports_menu      = "Povratak na izbors nalaza";  


?>
