<?php
  # file: lang/HR/simplerep_lout.php3.HR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # module: max k <amk@span.ch>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL
  # ver: 19991026


  $Verification_Key            = "Kljuè (Verification Key)"      ;
  $To                          = "Kome"                    ;
  $Generate_lout_for           = "Napravi za"     ;
  $Sr_page                     = "Stranica"                  ;
  $From                        = "Od koga"                  ;
  $Of                          = "Od"                    ;
  $Page                        = "Stranica"                  ;
  $Return_to_report_selection  = "Natrag na izbor nalaza" ;


?>
