<?php
  # file: lang/HR/specialties.php3.HR.inc
  # desc: specialties croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name = "Specijalizacija";

  $Specialty_Name                        = "Naziv specijalizacije";
  $Specialty_Description                 = "Opis specijalizacije";
  $Name                                  = "Ime";
  $Description                           = "Opis";
?>
