<?php
  # file: lang/HR/TEMPLATE.HR.inc
  # desc: TEMPLATE for language files
  # desc: Uzorak za jeziène datoteke
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  // language variables always have underscores and
  //  are either all caps or start with a capital
  //  letter -- jeff

  // you also must have the $record_name variable for ancillary dbs:
  // $record_name = "Room Equipment";
  // $Username = "Korisnik";
  // $Password = "©ifra";
  // $Enter_the_database = "Unesite ime baze podataka";
?>
