<?php
  # file: lang/HR/tos.php3.HR.inc
  # desc: type of service croatian (HR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Translation by nikola <nikola@mamef.mef.hr>
  # lic : GPL

  $record_name = "Vrste usluge";

  $phrase[Type_of_Service_Name]        = "Naziv usluge";
  $phrase[Type_of_Service_Description] = "Opis usluge";
  // 19991013
  $phrase[Name]                        = "Ime";
  $phrase[Description]                 = "Opis";
?>
