<?php
  # file: lang/HR/user.php3.HR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by nikola <nikola@mamef.mef.hr>
  # mod: 19991004

  $record_name                         = "Korisnik";
  $User_name                           = "Ime korisnika" ;
  $Password                            = "©ifra" ;
  $Verify                              = "provjera" ;
  $Description                         = "Opis" ;
  $Physician_group                     = "Grupa lijeènika" ;
  $User_level                          = "Korisniæki nivo" ;
  $Locked_out                          = "!!! Zabranjen pristup !!!" ;
  $Undefined                           = "NEDEFINIRANO" ;
  $Delete_privs                        = "Obi¹i privilegije" ;
  $Superuser                           = "SuperKorisnik/Admin." ;
  $Abandon_addition                    = "Odustani od ove radnje" ; # Just say no ;-)
  $Passwords_must_match                = "©ifre moraju odgovarati !" ;
  $Go_back_to_user_menu                = "Natrag na izbornik korisnika" ;
  
  $Please_use_the_modify_form          = "Koristite formular Izmjene da to uèinite" ;
  $Result                              = "REZULTAT" ;
  $You_cannot_modify_root              = "Nemo¾ete promjeniti SuperKorisnika" ;
  $You_cannot_delete_root              = "Nemo¾ete obrisati SuperKorisnika" ;
  $Query_result                        = "Rezultat upita" ;
  $Query_string                        = "Sadr¾aj upita" ;
  $Actual_query_result                 = "Potpuni izgled upita" ;
  $Another                             = "Drugi" ;
  $Maintenance                         = "Odr¾avanje" ;
  $Action                              = "Kreni" ;
  $No                                  = "Ne" ;
  $Found_with_that_criteria            = "naðen sa kriterijem" ;
  $Try_Again                           = "Poku¹aj ponovo";
  $Authorized_facilities               = "Authorizirani odjel/slu¾ba";
  $Authorized_physicians               = "Authorizirani lijeènici";
  $Authorized_phy_groups               = "Authorizirani grpue lijeènika";
    // 19990909
  $User_type                           = "Vrsta korisnika";
  $Physician                           = "Lijeènik";
  $Miscellaneous                       = "Ostalo";
    //19990927 - mark l
  $Update                              = "Obnovi";
  $Remove_changes                      = "Zanemari izmjene";
    // 19990929
  $Actual_physician                    = "Trenutni lijeènik";
?>
