<?php
  # file: lang/HR/user.php3.HR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by nikola <nikola@mamef.mef.hr>
  # mod: 19991004
  # mod: 20000529 adam b

  $record_name                         = "Korisnik";

  $phrase[User_name]              = "Ime korisnika" ;
  $phrase[Password]               = "©ifra" ;
  $phrase[Verify]                 = "provjera" ;
  $phrase[Description]            = "Opis" ;
  $phrase[Physician_group]        = "Grupa lijeènika" ;
  $phrase[User_level]             = "Korisniæki nivo" ;
  $phrase[Locked_out]             = "!!! Zabranjen pristup !!!" ;
  $phrase[Undefined]              = "NEDEFINIRANO" ;
  $phrase[Delete_privs]           = "Obi¹i privilegije" ;
  $phrase[Superuser]              = "SuperKorisnik/Admin." ;
  $phrase[Abandon_addition]       = "Odustani od ove radnje" ; # Just say no ;-)
  $phrase[Passwords_must_match]   = "©ifre moraju odgovarati !" ;
  $phrase[Go_back_to_user_menu]   = "Natrag na izbornik korisnika" ;
  
  $phrase[Please_use_the_modify_form]
                                  = "Koristite formular Izmjene da to uèinite" ;
  $phrase[Result]                 = "REZULTAT" ;
  $phrase[You_cannot_modify_root] = "Nemo¾ete promjeniti SuperKorisnika" ;
  $phrase[You_cannot_delete_root] = "Nemo¾ete obrisati SuperKorisnika" ;
  $phrase[Query_result]           = "Rezultat upita" ;
  $phrase[Query_string]           = "Sadr¾aj upita" ;
  $phrase[Actual_query_result]    = "Potpuni izgled upita" ;
  $phrase[Another]                = "Drugi" ;
  $phrase[Maintenance]            = "Odr¾avanje" ;
  $phrase[Action]                 = "Kreni" ;
  $phrase[No]                     = "Ne" ;
  $phrase[Found_with_that_criteria] = "naðen sa kriterijem" ;
  $phrase[Try_Again]              = "Poku¹aj ponovo";
  $phrase[Authorized_facilities]  = "Authorizirani odjel/slu¾ba";
  $phrase[Authorized_physicians]  = "Authorizirani lijeènici";
  $phrase[Authorized_phy_groups]  = "Authorizirani grpue lijeènika";
    // 19990909
  $phrase[User_type]              = "Vrsta korisnika";
  $phrase[Physician]              = "Lijeènik";
  $phrase[Miscellaneous]          = "Ostalo";
    //19990927 - mark l
  $phrase[Update]                 = "Obnovi";
  $phrase[Remove_changes]         = "Zanemari izmjene";
    // 19990929
  $phrase[Actual_physician]       = "Trenutni lijeènik";
?>
