# $Id$
# $Author$

THISDIR=lib/template
SUBDIR=default newskin

all:
	# Nothing

install:
	mkdir -p $(INSTDIR)/$(THISDIR)
	cp -rvf ${SUBDIR} $(INSTDIR)/$(THISDIR)

clean:
	# Nothing

dist-clean:
	# Nothing
	
