<?php
  # file: lang/EN/admin.php3.EN.inc
  # translation : Max Klohn <amk@span.ch>
  # lic : GPL
  # ver : 19991008

  $No_admin_menu_access = "You do not have access to the Administrative Menu" ; 
  $Icd_code_type = "ICD code type" ;
  $Graphics_enhanced = "Graphics Enhanced" ;
  $Disabled = "Disabled" ;
  $Enabled = "Enabled" ;
  $Scheduling_start_time = "Scheduling Starting Time" ;
  $Scheduling_end_time = "Scheduling Ending Time" ;
  $Configure = "Configure" ;
  $Reset = "Reset" ;
  $Configuration_complete = "Configuration complete" ;
  $Return_adm_menu = "Return to Administration Menu" ;
  $Reinitialize_database = "Reinitialize database" ;
  $Are_you_sure = "Are you SURE you want to" ;
  $Irreversable_process = "This is an irreversible process!" ;
  $First_initialization = "Check here if it is a first intitialization" ;
  $Continue = "Continue" ;
  $Cancel = "Cancel" ;
  $Erasing_old_db = "Erasing the old database" ;
  $Error_accessing_sql = "Error while accessing the SQL database" ;
  $Creating_new_db = "Creating a new database" ;
  $Creating_tables = "Creating tables" ;
  $Administration_menu = "Administration Menu" ;
  $Update_config = "Update configuration" ;
  $User_maintenance = "User Maintenance" ;
  $Return_main_menu = "Return to Main Menu" ;
  $DEFAULT = "DEFAULT";
    // 19990830
  $SELECTED = "SELECTED";
  $Update_Configuration = "Update Configuration";
    // 19991007
  $Calendar_overbooking = "Calendar Over-Booking";

?>
