<?php
  # file : lang/EN/API.EN.inc
  # code : jeff b <jeff@univrel.pr.uconn.edu>
  # lic  : GPL
  # Translation by jeff b
  # ver  : 19991201

  $DEBUG_IS_ON = "DEBUG IS ON";
  $Return_to_the_Main_Menu = "Return to the Main Menu";
  $Return_to_Previous_Menu = "Return to Previous Menu";
  $lang_main = "main"; // alt tag for main menu button
  $lang_exit = "exit"; // alt tag for logout button
  $RETURN_TO_MENU          = "RETURN TO MENU";
  $NONE_SELECTED           = "NONE SELECTED";
  $SELECTED                = "SELECTED"; // must NOT be translated
  $lang_coded_by           = "coded by"; 
  $NO_RESULT_OF_QUERY      = "NO RESULT OF QUERY";
  $Entered_incorrect_NamePasswd =
    "You have entered an incorrect user name or password";
  $Possible_Cookies_Have_Expired =
    "It is also possible that your cookies have expired. Please<BR>
     log in again, or ask your system administrator to increase the<BR>
     cookie-eating time.";
  $Login_Screen            = "Login Screen";
    // 19990824
  $Add                     = "Add";
  $Adding                  = "Adding";
  $Clear                   = "Clear";
    // 19990917
  $Return_to               = "Return to";
  $Main_Menu               = "Main Menu";
  $Modify                  = "Modify";
  $Modifying               = "Modifying";
  $Done                    = "done";
  $Menu                    = "Menu";
  $Deleting                = "Deleting";
  $Update_Delete_Another   = "Update/Delete Another";
  $Deleted                 = "deleted";
  $Abandon_Addition        = "Abandon Addition";
  $Abandon_Modification    = "Abandon Modification";
  $Update                  = "Update";
  $Remove_Changes          = "Remove Changes";
  $Exporting_data          = "Exporting data";
  $Export                  = "Export";
  $ERROR                   = "ERROR";
  $Action                  = "Action";
  // 19990920
  $lang_ALL                = "ALL";
  // 19990921
  $lang_ADD                = "ADD";  
  $lang_MOD                = "MOD";
  $lang_DEL                = "DEL";
  // 19990922
  $No_Record_Found         = "No $record_name found with that criteria.";
  $lang_back               = "back";
  // 19990924
  $lang_HELP               = "HELP";
  $Module                  = "Module";
  $Manage_Patient          = "Manage Patient";
  // 19991005
  $Week_Of                 = "Week of";
  // 19991013
  $Export_Database         = "Export Database";
  // 19991026
  $Export_Data             = "Export Data";
  // 19991102
  $lang_months             = array ("", // null for 0
                                    "Jan",
                                    "Feb",   
                                    "Mar",
                                    "Apr",
                                    "May",
                                    "Jun",
                                    "Jul",
                                    "Aug",
                                    "Sep",
                                    "Oct",
                                    "Nov",
                                    "Dec" );
  $lang_days               = array ("", // null for 0
                                    "Sun",
                                    "Mon",
                                    "Tue",
                                    "Wed",
                                    "Thu",
                                    "Fri",
                                    "Sat" ); 
  // 19991116
  $midnight                = "midnight";
  $noon                    = "noon";
  // 19991122
  $Patient                 = "Patient";
  $lang_no                 = "no";
  $lang_yes                = "yes";
  $lang_go                 = "go";  
  $State_Providence        = "State/Providence";
  $Return_to_Menu          = "Return to Menu";
  // 19991201
  $Post                    = "Post";
?>
