<?php
  # file: lang/EN/authenticate.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>

  $Error = "ERROR" ;
  $Return_to_the_login_screen = "Return to the Login Screen";
  $Incorrect_name_password= "You have entered an incorrect username or password. <BR>
   Please contact your system administrator. If you believe this message is<BR>
   in error, please make a note of the circumstances under which it<BR>
   occurred, and give it to your system administrator to use for his or <BR>
   her bug report." ;
?>
