<?php
  # file: lang/EN/book_appointment.php3.EN.inc
  # desc: book appointment english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $Add_Appointment                     = "Add Appointment";
  $lang_day                            = "day";
  $lang_week                           = "week";
  $lang_prev                           = "prev";
  $lang_next                           = "next";
  $Current_Date_is                     = "Current Date is";
  $this_date_occurs_in_the_past        = "this date occurs in the past";
  $Current_Patient                     = "Current Patient";
  $Room                                = "Room";
  $Check_Room                          = "Check Room";
  $Try_Again                           = "Try Again";
  $Date                                = "Date";
  $The_selected_room_is_free_all_day   = "The selected room is free all day.";
  $TIME                                = "TIME";
  $NO_PREFERENCE                       = "NO PREFERENCE";
  $Patient                             = "Patient";
  $Time                                = "Time";
  $lang_hour                           = "hour";   // singular
  $lang_hours                          = "hours";  // plural
  $lang_min_abbrev                     = "min";    // abbreviated minutes
  $lang_h                              = "h";      // single letter for hours
  $lang_m                              = "m";      // single letter for minutes
  $Duration                            = "Duration";
  $Physician                           = "Physician";
  $Note                                = "Note";
  $Adding_Appointment                  = "Adding Appointment";
  // 19991013
  $Facility                            = "Facility";
  $Change_Room                         = "Change Room";
?>
