<?php
  # file: lang/EN/call-in.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Mod : 19990922

  $Call_In              = "Call In";
  $Name                 = "Name";
  $Last                 = "Last";
  $First                = "First";
  $Middle               = "Middle";
  $Contact_Information  = "Contact Information";
  $Home_Phone           = "Home Phone";
  $Work_Phone           = "Work Phone";
  $Took_Call            = "Took Call";
  $Date_of_Birth        = "Date of Birth";
  $Complaint            = "Message";
  $Facility             = "Facility";
  $Physician            = "Physician";
  $Patient_Menu         = "Patient Menu";
  $Call_In_Menu         = "Call-In Menu";
  $Main_Menu            = "Main Menu";
  $NOT_IMPLEMENTED_YET  = "NOT IMPLEMENTED YET";
  $Date_of_Call         = "Date of Call";
  $Home_Work_Phone      = "Home/Work Phone";
  $Action               = "Action";
  $VIEW                 = "VIEW";
  $BOOK                 = "BOOK";
  // 19990920
  $Old                  = "Old";
  $All                  = "All";
  $Current              = "Current";
?>
