<?php
  # file: lang/EN/cpt.php3.EN.inc
  # desc: CPT codes english (EN) language module
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

// 19990927 - mark l
  $Clear        = "Clear";

  $record_name                      = "CPT Code";

  $CPT_Code                         = "CPT Code";
  $CPT_Name_Internal                = "CPT Name (Internal)";
  $CPT_Name_External                = "CPT Name (External)";
  $Relative_Value                   = "Relative Value";
  $Example                          = "ex";
  $Type_of_Service                  = "Type of Service";
  $Internal_Name                    = "Internal Name";
?>
