<?php
  # file: lang/EN/custom_records.php3.EN.inc
  # desc: custom records english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Custom Records";

  $Must_select_a_patient       =
      "You cannot do this unless you select a patient!";
  $Must_select_a_template      =
      "You cannot do this unless you select a template!";
  $Select_a_Patient            = "Select a Patient";
  $No_records_for_this_patient = "There are no records for this patient.";
  $Date_Added                  = "Date Added";
  $Form                        = "Form";
?>
