<?php
  # file: lang/EN/db_maintenance.php3.EN.inc
  # desc: database maintenance menu english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # ver : 19991102

  $Database_Maintenance            = "Database Maintenance";
  $CPT_Procedural_Codes            = "CPT/Procedural Codes";
  $CPT_Procedural_Modifiers        = "CPT/Procedural Modifiers";
  $Formulary_Pharmacy_Module       = "Formulary (Pharmacy) Module";
  $ICD_Codes                       = "ICD 9/10 Codes";
  $Insurance_Companies             = "Insurance Companies";
  $Insurance_Company_Groups        = "Insurance Company Groups";
  $Physicians                      = "Physicians";
  $Physician_Degrees               = "Physician Degrees";
  $Physician_Groups                = "Physician Groups";
  $Physician_Specialties           = "Physician Specialties";
  $Physician_Statuses              = "Physician Statuses";
  $Place_of_Service_Facilities     = "Facilities (<I>Places of Service</I>)";
  $Rooms                           = "Rooms";
  $Scheduling_Locations            = "Scheduling Locations";
  $Type_of_Service                 = "Type of Service";
  $Templates_for_Simple_Reports    = "Templates for Simple Reports";
  $You_dont_have_access_for_this_menu = "You don't have access for this menu.";
  $Selectable_Printers             = "Selectable Printers" ;
  $Fixed_Forms                     = "Fixed Forms" ;
  $Custom_Patient_Record_Templates = "Custom Patient Record Templates" ;
  $Diagnosis_Families              = "Diagnosis Families" ;

?>
