<?php
  # file: lang/EN/degrees.php3.EN.inc
  # desc: physician degrees english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # mods: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name="Physician Degree";


  $Degree_Title                        = "Degree Title";
  $Degree_Title_Example                = "Doctor of Chiropody, etc";
  $Degree_Name                         = "Degree Name";
  $Degree_Name_Example                 = "MD, DPM, etc";
  $Date_Last_Modified                  = "Date Last Modified";
  $Degree                              = "Degree";
  $Description                         = "Description";
  $No_degrees_are_currently_in_the_database =
     "No degrees are currently in the database.";
?>
