<?php
  # file: lang/EN/episode_of_care.php3.EN.inc
  # desc: episode of care english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Episode of Care";

  $Must_select_record_to_modify =
          "You must select a record to modify.";
  $Return_to_Menu              = "Return to Menu";
  $Description                 = "Description";
  $Related_to_Pregnancy        = "Related to Pregnancy?";
  $Date_of_First_Occurance     = "Date of First Occurance";
  $Related_to_Employment       = "Related to Employment";
  $Date_of_Last_Similar        = "Date of Last Similar";
  $Related_to_Automobile       = "Related to Automobile Accident";
  $Referring_Physician         = "Referring Physician";
  $Related_to_Other_Cause      = "Related to Other Cause";
  $Facility                    = "Facility"; 
  $Diagnosis_Family            = "Diagnosis Family";
  $Episode_Type                = "Episode Type";
  $lang_acute                  = "acute";
  $lang_chronic                = "chronic";
  $lang_chronic_recurrent      = "chronic recurrent";
  $lang_historical             = "historical";
  $Automobile_Related_Information =
           "Automobile Related Information";
  $Auto_Insurance              = "Auto Insurance";
  $Case_Number                 = "Case Number";
  $Address                     = "Address";
  $Line_1                      = "Line 1";
  $Line_2                      = "Line 2";
  $Contact_Name                = "Contact Name";
  $Contact_Phone               = "Contact Phone #";
  $City                        = "City";
  $St_Pr                       = "St/Pr";
  $Postal_Code                 = "Postal Code";
  $Email_Address               = "Email Address";
  $Country                     = "Country";
  $Employment_Related_Information =
            "Employment Related Information";
  $Name_of_Employer            = "Name of Employer";
  $File_Number                 = "File Number";
  $Pregnancy_Related_Information = 
            "Pregnancy Related Information";
  $Length_of_Cycle             = "Length of Cycle (days)";
  $Last_Menstrual_Period       = "Last Menstrual Period";
  $Gravida                     = "Gravida";
  $Date_of_Confinement         = "Date of Confinement";
  $Para                        = "Para";
  $Miscarries                  = "Miscarries";
  $Abortions                   = "Abortions";
  $Other_Related_Information   = "Other Related Information";
  $More_Information            = "More Information";
  $Must_specify_patient        = "You must specify a patient.";
  $Starting_Date               = "Starting Date";
  $Description                 = "Description";
  $No_record_for_patient       = "No record for specified patient.";
?>
