<?php
  # file: lang/EN/facility.php3.EN.inc
  # desc: facility (place of service) english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # ver : 19991005

  $record_name = "Facility (POS)";

  $Facility_Name                  = "Facility Name";
  $Address_Line_1                 = "Address Line 1";
  $Address_Line_2                 = "Address Line 2";
  $City                           = "City";
  $State                          = "State";
  $Zip                            = "Zip";
  $Description_Note               = "Description/Note";
  $Default_Physician              = "Default_Physician";
  $Phone_Number                   = "Phone Number";
  $Fax_Number                     = "Fax Number";
  $Email_Address                  = "Email Address";
  $Date_of_Entry                  = "Date of Entry";
  $Country                        = "Country";   // 19991005
?>
