<?php
  # file : lang/EN/frmlry.php3.EN.inc
  # desc : formulary/pharmacy english (EN) language file
  # code : jeff b <jeff@univrel.pr.uconn.edu>
  # mods : max k <amk@span.ch>
  # lic  : GPL
  # ver  : 19991007

  $record_name = "Formulary";

  $Class                          = "Class";
  $Generic_Name                   = "Generic Name";
  $Trademark_Name                 = "Trademark Name";
  $Indication_1                   = "Indication 1";
  $Indication_2                   = "Indication 2";
  $Indication_3                   = "Indication 3";
  $Date_Added                     = "Date Added";
?>
