<?php
  # file: lang/EN/icd9.php3.EN.inc
  # desc: CPT codes english (EN) language module
  # code: mark l <lesswin@ibm.net>
  # lic : GPL

//19990927 - mark l
  $Clear        = "Clear";

  $record_name                      = "ICD9 Code";

  $ICD9_Code                        = "ICD9 Code";
  $ICD10_Code                       = "ICD10 Code";
  $ICD9_Description                 = "ICD9 Description";
  $ICD10_Description                = "ICD10 Description";
  $Date_of_Entry                    = "Date of Entry";
  $Diagnosis_Related_Groups         = "Diagnosis Related Groups (Unused)";
  $Number_of_Times_Used             = "Number of Times Used";
  $Amount_Billed                    = "Amount Billed";
  $Amount_Collected                 = "Amount Collected";
?>
