<?php
  # file: lang/EN/index.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by jeff b

  $Username     = "Username";
  $Password     = "Password";
  $Enter_the_database = "Enter the database";
  $Clear        = "Clear";
  $Language     = "Language";
  $Default      = "Default";
    // 19990820
  $Facility     = "Facility";
  $Login        = "Login";
    // 19990922
  $Resume       = "Resume";
  $Reset_Resume = "Reset Resume";
?>
