<?php
  # file: lang/EN/main.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Mod : 19990929

  $Main_menu                 = "Main Menu" ;
  $Administration_menu       = "Administration Menu" ;
  $Billing_functions         = "Billing Functions" ;
  $Database_maintenance      = "Database Maintenance" ;
  $Patient_functions         = "Patient Functions" ;
  $Help_main_menu            = "Help for the Main Menu" ;
  $Logout_of                 = "Logout of" ;
  $Quickjump                 = "QUICKJUMP" ;
  $User_level                = "USER LEVEL" ;
  $User_description          = "USER DESCRIPTION" ;
  $Call_in                   = "Call In";
  $Entry                     = "Entry";
  // 19991006
  $Day_View                  = "Day View (Calendar)";
  $Week_View                 = "Week View (Calendar)";
?>
