<?php
  # file: lang/EN/manage.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by jeff b
  # Mods by max k <amk@span.ch>
  # mod: 19990917

  $Attach_to_Guarantor           = "Attach to Guarantor";
  $Must_select_a_patient         = "You must select a patient.";
  $Select_Guarantor_to_Attach_to = "Select Guarantor to Attach to:";
  $detach                        = "detach";
  $Attach                        = "Attach";
  $Return_to_Patient_Management  = "Return to Patient Management";
  $Attaching_Guarantor           = "Attaching Guarantor";
  $Detaching_current_dependants  = "Detaching current dependants";
  $lang_done                     = "done.";
  $Manage_Patient                = "Manage Patient";
  $Select_a_patient              = "Select a patient";
  $Patient_Information           = "Patient Information";
  $View_Manage                   = "View/Manage";
  $Prescriptions                 = "Prescriptions";
  $Procedures                    = "Procedures";
  $Progress_Notes                = "Progress Notes";
  $Reports_and_certificates      = "Reports and Certificates";  // 19990813
  $Choose                        = "Choose";                    // 19990813
  $Show_Dependants               = "Show Dependants";
  $Show_Guarantor                = "Show Guarantor";
  $Last_Name                     = "Last Name";
  $All                           = "All";
  $Select_Another_Patient        = "Select Another Patient";
    // 19990809
  $Appointments                  = "Appointments";
  $Book                          = "Book";
  $Patient                       = "Patient";
  $Show_Today                    = "Show Today";
?>
