<?php
  # file: lang/EN/patient.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL, v2
  # Adaptation by max k <amk@span.ch>

  $record_name                   = "Patient";

  $Dependant                     = "Dependant";
  $Patient                       = "Patient";
  $Last_name                     = "Last Name";
  $First_name                    = "First Name";
  $Middle_name                   = "Middle Name";
  $Date_of_birth                 = "Date of Birth";
  $YMD                           = "Y-M-D";
  $Gender                        = "Gender";
  $NONE_SELECTED                 = "NONE SELECTED";
  $Female                        = "female";
  $Male                          = "male";
  $Transgender                   = "transgender";
  $Marital_status                = "Marital Status";
  $Unknown                       = "unknown";
  $Single                        = "single";
  $Married                       = "married";
  $Divorced                      = "divorced";
  $Internal_practice_id          = "Internal Practice ID";
  $Address                       = "Address";
  $Line                          = "Line";
  $City                          = "City";
  $State                         = "State";
  $Zip_code                      = "Zip Code";
  $Country                       = "Country";
  $Home_phone                    = "Home Phone";
  $Work_phone                    = "Work Phone";
  $Fax_number                    = "Fax Number";
  $Email_address                 = "Email Address";
  $Drivers_license               = "Drivers License";
  $No_state                      = "No State";
  $Referring_doctor              = "Referring Doctor";
  $Primary_care_physician        = "Primary Care Physician";
  $Other                         = "Other";
  $Physician                     = "Physician";
  $Type_of_billing               = "Type of Billing"; 
  $Monthly_billing_on_acct       = "monthly billing on account";
  $Statement_billing             = "statement billing";
  $Charge_card_billing           = "charge card billing";
  $Monthly_budget_amount         = "Monthly Budget Amount";
  $In_house_doctor               = "In-House Doctor";
  $Primary_insurance             = "Primary Insurance";
  $Secondary_insurance           = "Secondary Insurance";
  $Tertiary_insurance            = "Tertiary Insurance";
  $Discount_percent_if_applic    = "Discount % (if applicable)";
  $Self_insured                  = "self-insured";
  $Guarantor                     = "Guarantor";
  $Next_of_kin_information       = "Next of Kin Information";
  $Employed_presently            = "Employed Presently?";
  $UNKNOWN                       = "UNKNOWN";
  $Yes                           = "yes";
  $No                            = "no";
  $PartTimeStudent               = "Part Time Student";
  $FullTimeStudent               = "Full Time Student";
  $Adding_patient                = "Adding Patient";
  $ADDING                        = "Adding";
  $Query_result                  = "Query result";
  $Query_string                  = "Query string";
  $Actual_query_result           = "Actual query result";    
  $Error                         = "ERROR";    
  $Return_to_the                 = "Return to the";
  $Patient_menu                  = "Patient Menu";
  $Main_menu                     = "Main Menu";
  $MODIFYING                     = "Modifying";
  $Please_use_the_MODIFY_form    = "Please use the MODIFY form to MODIFY a code";
  $Result                        = "RESULT";
  $Book_an_appointment           = "Book an Appointment";
  $Date                          = "Date";
  $Of_entry                      = "of Entry";
  $Of_last_mod                   = "of Last Mod";
  $Update                        = "Update";
  $Remove_changes                = "Remove Changes";
  $Manage                        = "Manage";
  $Select_another                = "Select Another";
  $Patients_meeting_criteria     = "Patients Meeting Criteria";
  $Action                        = "Action";
  $NEWDEP                        = "NEWDEP";
  $DEPS                          = "DEPS";
  $GUA                           = "GUA";
  $MANAGE                        = "MANAGE";
  $No_patients_found_with_that   = "No Patients found with that Criteria";
  $PATIENTS                      = "Patients";
  $In_system                     = "In System";
  $No_patients                   = "No Patients";
  $Ppl                           = "Patient(s)";
  $One                           = "One";
  $By_name                       = "By Name";
  $Patients_field_search         = "Patients Field Search"; 
  $Social_security_number        = "Social Security Number";
  $Patient_account_number        = "Patient Account Number";
  $Show_all                      = "Show All";
  $Contains                      = "Contains";
  $Find                          = "find";
  $Searching_for                 = "Searching for";
  $Last_names                    = "Last Names";
  $All_Patients                  = "All Patients";
  $Dependants                    = "Dependants";
    // 19990823
  $Separated                     = "separated";
    // 19990830
  $Call_In_Menu                  = "Call-In Menu";
    // 19990923
  $Current_Patient		 = "Current Patient"; 
  $CONTAINS			 = "contains";        
?>
