<?php
  # file: lang/EN/phy_avail_map.EN.inc
  # desc: physician available map english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Physician Available Map";

  $Must_specify_physician          = "You must specify a physician!";
  $Absence_date_from               = "Availability Change (Date From)";
  $Absence_date_to                 = "Availability Change (Date To)";
  $Time_beginning                  = "Beginning of Time";
  $Time_ending                     = "Ending of Time";
  // 19991005
  $lang_to                         = "to";
  $Comment                         = "Comment";
  $Physician                       = "Physician";
  $Availability                    = "Availability";
?>
