<?php
  # file: lang/EN/phystatus.php3.EN.inc
  # desc: physician status english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # some mods: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name               = "Physician Status";

  $Status                    = "Status";
  $Update                    = "Update";
  $Remove_Changes            = "Remove Changes";
  $Abandon_Modification      = "Abandon Modification";
  $Modifying                 = "Modifying";
  $Done                      = "Done";
  $Return_to_Previous_Menu   = "Return to Previous Menu";
  $Return_to_the_Main_Menu   = "Return to the Main Menu";
  $Deleting                  = "Deleting";
  $Deleted                   = "Deleted";
  $RESULT                    = "RESULT";
  $Update_Delete_Another     = "Update or delete another";
  $Return_to                 = "Return to";
  $RETURN_TO_MENU            = "RETURN TO MENU";
  $No_Record_Found           = "No record was found";
?>
