<?php
  # file: lang/EN/physician.php3.EN.inc
  # desc: physician maintenance menu english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation : max k <amk@span.ch>
  # lic : GPL
  # ver : 19991104

  $Add_Physician                   = "Add Physician"  ;
  $Last_name                       = "Last Name"      ;
  $First_name                      = "First Name"     ;
  $Title                           = "Title"          ;
  $Middle_Name                     = "Middle Name"    ;
  $Practice_Name                   = "Practice Name"  ;
  $Primary_Address_Line            = "Primary Address Line"    ;
  $Primary_Address_City            = "Primary Address City"    ;
  $Primary_Address_State           = "Primary Address State"   ;
  $Primary_Address_Zip             = "Primary Address Zip"     ;
  $Primary_Address_Phone           = "Primary Address Phone"   ;
  $Primary_Address_Fax             = "Primary Address Fax"     ;
  $Secondary_Address_Line          = "Secondary Address Line"  ;
  $Secondary_Address_City          = "Secondary Address City"  ;
  $Secondary_Address_State         = "Secondary Address State" ;
  $Secondary_Address_Zip           = "Secondary Address Zip"   ;
  $Secondary_Address_Phone         = "Secondary Address Phone" ;
  $Secondary_Address_Fax           = "Secondary Address Fax"   ;
  $Email_Address                   = "Email Address"           ;
  $Cellular_Phone                  = "Cellular Phone"          ;
  $BeeperPager                     = "Beeper or Pager"     ;
  $UPIN_Number                     = "UPIN Number"         ;
  $Social_Security                 = "Social Security"     ;
  $Degree                          = "Degree"              ;
  $Specialty                       = "Specialty"           ;
  $Internal_ID                     = "Internal ID"         ;
  $Status                          = "Status"              ;
  $Reference                       = "Reference"           ;
  $Number_of_Referrals             = "Number of Referrals" ;
  $Primary_care_provider           = "Primary care provider" ;
  $Referring                       = "Referring"           ;
  $NULL                            = "NULL"                ;
  $Number_of_Referrals             = "Number of Referrals" ;
  $Referral_Amount                 = "Referral Amount"     ;
  $S_charged                       = "\$ charged"          ;
  $S_received                      = "\$ received"         ;
  $Add                             = "Add"                 ;
  $Clear                           = "Clear"               ;
  $Adding_Physician                = "Adding Physician"    ;
  $Adding                          = "Adding"              ;
  $Done                            = "Done"                ;
  $ERROR                           = "ERROR"               ;
  $Physician                       = "Physician"           ;
  $Modify_Physician                = "Modify Physician"    ;
  $Please_use_the_MODIFY_form_to_MODIFY_someone = "Please use the MODIFY form to MODIFY someone" ;
  $Return_to_the_Main_Menu         = "Return to the Main Menu" ;
  $Update                          = "Update"                  ;
  $Abandon_Modification            = "Abandon Modification"    ;
  $Modifying_Physician             = "Modifying Physician"     ;
  $Modifying                       = "Modifying"               ;
  $Deleting_Physician              = "Deleting Physician"      ;
  $RESULT                          = "RESULT"                  ;
  $Delete_Another                  = "Delete Another"          ;
  $Physician_Display               = "Physician Display"       ;
  $You_must_specify_an_id          = "You must specify an id"  ;
  $Return_to_the_Physician_Menu    = "Return to the Physician Menu" ;
  $NONE_SELECTED                   = "NONE SELECTED"           ;
  $Physicians                      = "Physicians"              ;
  $Last_Name                       = "Last Name"               ;
  $First_Name                      = "First Name"              ;
  $Degrees                         = "Degrees"                 ;
  $Action                          = "Action"                  ;
  $VIEW                            = "VIEW"                    ;
  $MOD                             = "MOD"                     ;
  $DEL                             = "DEL"                     ;
  $No_physicians_found_with_that_criteria = "No physicians found with that criteria" ;



?>