<?php
  # file: lang/EN/physician_week_view.php3.EN.inc
  # desc: physician weekly view english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $Physician_Weekly_View                   = "Physician Weekly View";
  $back_one_week                           = "prev";
  $forward_one_week                        = "next";
  $No_Physician_Selected                   = "No Physician Selected"; 
  $Physician                               = "Physician";
?>
