<?php
  # file: lang/EN/physician_day_view.php3.EN.inc
  # desc: physician daily view english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $Physician_Daily_View                    = "Physician Daily View";
  $back_one_day                            = "prev";
  $forward_one_day                         = "next";
  $No_Physician_Selected                   = "No Physician Selected"; 
  $Physician                               = "Physician";
?>
