<?php
  # file: lang/EN/progress_notes.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name                  = "Progress Notes";
  $Module                       = "Module";
  $ERROR                        = "ERROR";
  $Must_Specify_A_Patient       = "You must specify a patient!";
  $Entry                        = "Entry";
  $Manage_Patient               = "Manage Patient";
  $View_Modify                  = "View/Modify";
  $Applicable_Date              = "Applicable Date";

    // the actual progress parts (with underlines)
  $Subjective                   = "<U>S</U>ubjective";
  $Objective                    = "<U>O</U>bjective";
  $Assessment                   = "<U>A</U>ssessment";
  $Plan                         = "<U>P</U>lan";
  $Interval                     = "<U>I</U>nterval";
  $Education                    = "<U>E</U>ducation";
  $Prescription                 = "p<U>R</U>escription";

  $Add                          = "Add";
  $Clear                        = "Clear";
  $Abort_Addition               = "Abort Addition";
  $Adding                       = "Adding";
  $Done                         = "done";
  $FAILED                       = "FAILED";
  $Must_Call_With_Patient_ID    = "You must call this function with a ".
                                  "patient selected.";
  $Modify                       = "Modify";
  $Change                       = "Change";
  $Restore                      = "Restore";
  $Modifying                    = "Modifying";
  $View                         = "View";
  $Menu                         = "Menu";
  $Specify_Notes_to_Display     = "You must specify the progress notes to ".
                                  "be displayed.";
  $Modify_Notes                 = "Modify Notes";
  $Patient                      = "Patient";
  $This_Patient_Has_No_Notes    = "This patient has no notes to date.";
  $Existing                     = "Existing";
?>
