<?php
  # file: lang/EN/room.php3.EN.inc
  # desc: room (scheduling location) english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Room Equipment";

  $Room_Name                      = "Room Name";
  $Location                       = "Location";
  $Room_Description               = "Room Description";
  $Default_Physician              = "Default Physician";
  $Surgery_Equipped               = "Surgery Equipped?";
  $Is_Booking_Enabled             = "Is Booking Enabled?";
  $IP_Address                     = "IP Address";
  $For_Future_Use                 = "for future use";
  $For_Scheduling                 = "for Scheduling";
  $Description                    = "Description";
?>
