<?php
  # file: lang/EN/Rx.php3.EN.inc
  # desc: prescription module english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Prescription";

  $Must_Have_Patient_For_Prescriptions =
    "You must have a patient to use this prescription module.";
  $No_Access_To_This_Patient           =
    "You don't have access to this patients' record.";
  $Display                             = "Display";
  $Patient                             = "Patient";
  $Drug                                = "Drug";
  $Dosage                              = "Dosage";
  $Starting_Date                       = "Starting Date";
  $In_Days                             = "in days";
  $Infinite                            = "0 = infinite";
  $Refills                             = "Refills";
  $Substitution                        = "Substitution";
  $May_Not_Substitute                  = "may not substitute";
  $May_Substitute                      = "May substitute";
  $Manage_Prescriptions                = "Manage Prescriptions";
  // 19991002
  $Duration                            = "Duration";
?>
