<?php
  # file: lang/EN/select_printer.php3.EN.inc
  # desc: Selectable printer management english (EN) language file
  # code: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991020

  $record_name = "Selectable Printers Management" ;

  $Selectable_Printer    = "Selectable Printer"   ;
  $Printer_Name          = "Printer Name"         ;
  $Printer_Host          = "Printer Host"         ;
  $Access_Level          = "Access Level"         ;
  $Description           = "Description"          ;
  $Add                   = "Add"                  ;
  $Clear                 = "Clear"                ;
  $Adding                = "Adding"               ;
  $Done                  = "Done"                 ;
  $ERROR                 = "ERROR"                ;
  $Return_to             = "Return to"            ;
  $Menu                  = "Menu"                 ;
  $Modify                = "Modify"               ;
  $Please_use_MODIFY     = "Please use the MODIFY form to MODIFY a" ;
  $Return_to_the_Main_Menu = "Return to the Main Menu" ;
  $RESULT                = "RESULT"               ;
  $Abandon_Addition      = "Abandon Addition"     ;
  $Update                = "Update"               ;
  $Remove_Changes        = "Remove Changes"       ;
  $Abandon_Modification  = "Abandon Modification" ;
  $Modifying             = "Modifying"            ;
  $Deleting              = "Deleting"             ;
  $Deleted               = "Deleted"              ;
  $Update_Delete_Another = "Update or Delete Another" ;
  $Export                = "Export"               ;
  $Exporting_data        = "Exporting data"       ;
  $Action                = "Action"               ;
  $Printer               = "Printer"              ;
  $Host                  = "Host"                 ;
  $MOD                   = "MOD"                  ;
  $DEL                   = "DEL"                  ;
  $No_Record_Found       = "No Record Found"      ;
  $Current_Contents      = "Current Content"      ;
  $For_Reference         = "For Reference"        ;

?>
