<?php
  # file: lang/EN/simplerep.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # module: max k <amk@span.ch>
  # lic : GPL
  # ver: 19991103

  $record_name = "Simple Reports";

  $Add                         = "Add";
  $Clear                       = "Clear"; 
  $Label                       = "Label";
  $Category                    = "Category";
  $Text                        = "Text";
  $Abandon_Addition            = "Abandon Addition";
  $Adding                      = "Adding";
  $Return_to                   = "Return to";
  $Modify                      = "Modify";
  $Please_use_MODIFY           = "Please use the MODIFY form to MODIFY a";
  $Return_to_the_Main_Menu     = "Return to the Main Menu";
  $Update                      = "Update";
  $Remove_Changes              = "Remove Changes";
  $Abandon_Modification        = "Abandon Modification";
  $Modifying                   = "Modifying";
  $Done                        = "done";
  $ERROR                       = "ERROR";
  $Menu                        = "Menu";
  $Deleting                    = "Deleting";
  $Deleted                     = "deleted";
  $Update_Delete_Another       = "Update/Delete Another";
  $Must_Have_Patient_to_Make_Reports =
    "You must have a patient to make reports!";
  $Choose_Report_for_Patient   = "Choose Report for Patient";
  $Patient                     = "Patient";
  $Manage_Patient              = "Manage Patient";
  $Action                      = "Action";
  $Mr                          = "Mr";   // 19990926
  $Mrs                         = "Mrs";
  $Report                      = "Report";
  $Physician                   = "Physician";
  $Facility                    = "Facility";
  $Proceeding                  = "proceeding";  //  19990927
  $Proceed                     = "Proceed";
  $Please_choose               = "Please select something for each";  // 19990927
  $Before                      = "before";
  $Return_to_report_selection  = "Return to Report Selection"; // 19990928
  $Destinatary_is              = "Destinatary is";
  $Delivery_Method             = "Delivery Method";
  $NONE_SELECTED               = "NONE SELECTED";
  $The_Patient                 = "The Patient";
  $A_Physician                 = "A Physician";
  $An_Insurer                  = "An Insurer";
  $Other                       = "Other";
  $Printer                     = "Printer";
  $Fax                         = "Fax"; 
  $E_mail                      = "E-mail";
  $Edit_report_for_patient     = "Edit report for patient";
  $Phone                       = "Phone";  //19991005
  $Datequalif                  = "";
  $Help_for_simple_reports     = "Help for simple reports";
  $Edit_add_simple_reports     = "Add or Edit Simple Reports";  // 19991007
  $Patients_primary_insurer    = "Patient's Primary Insurer";   // 19991008
  $Patients_secundary_insurer  = "Patient's Secundary Insurer";
  $Patients_tertiary_insurer   = "Patient's Tertiary Insurer";
  $Select_from_contact_list    = "Select from Contact List";
  $Patients_primary_employer   = "Patient's Primary Employer";
  $Patients_secundary_employer = "Patient's Secundary Employer";
  $No_delivery_method_selected = "No delivery method was selected!"; // 19991008
  $Print                       = "Print";
  $To                          = "To";                               // 19991009
  $Patient_has_no_fax          = "Sorry, this patient has no valid fax number";
  $Send                        = "Send";
  $Patient_has_no_email        = "Sorry, this patient has no e-mail address";
  $A_physician_must_sign_his_own_name = "A physician must sign his own name";
  $Verification_Key            = "Verification Key";
  $Suppress_headers            = "Suppress Headers";
  $Show_full_titles            = "Show Full Physician Titles";
  $Mailed                      = "Mailed"   ;
  $From                        = "From"     ;
  $Copy_to                     = "Copy to"  ;
  $Subject                     = "Subject"  ;
  $Male                        = "Male"     ;
  $Female                      = "Female"   ;
  $Adult                       = "Adult"    ;
  $Child                       = "Child"    ;
  $Return_to_reports_menu      = "Return to the Reports Menu";  


?>
