<?php
  # file: lang/EN/simplerep_plaintext_email.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # module: max k <amk@span.ch>
  # lic : GPL
  # ver: 19991030


  $Verification_Key            = "Verification Key"      ;
  $To                          = "To"                    ;
  $Generate_lout_for           = "Generate lout for"     ;
  $Sr_page                     = "Page"                  ;
  $From                        = "From"                  ;
  $Of                          = "Of"                    ;
  $Page                        = "Page"                  ;
  $Return_to_report_selection  = "Return to Report Selection" ;
  $Mailed                      = "Mailed"                ;
  $Wrong_Delivery              = "Wrong Delivery Method Selected" ;

?>