<?php
  # file: lang/EN/specialties.php3.EN.inc
  # desc: specialties english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Specialty";

  $Specialty_Name                        = "Specialty Name";
  $Specialty_Description                 = "Specialty Description";
  $Name                                  = "Name";
  $Description                           = "Description";
?>
