<?php
  # file: lang/EN/TEMPLATE.EN.inc
  # desc: TEMPLATE for language files
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  // language variables always have underscores and
  //  are either all caps or start with a capital
  //  letter -- jeff

  // you also must have the $record_name variable for ancillary dbs:
  // $record_name = "Room Equipment";
  // $Username = "Username";
  // $Password = "Password";
  // $Enter_the_database = "Enter the database";
?>
