<?php
  # file: lang/EN/tos.php3.EN.inc
  # desc: type of service english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Type of Service (TOS)";

  $phrase[Type_of_Service_Name]        = "Type of Service Name";
  $phrase[Type_of_Service_Description] = "Type of Service Description";
  // 19991013
  $phrase[Name]                        = "Name";
  $phrase[Description]                 = "Description";
  // 20000529
  $phrase[Please_use_the_MODIFY_form_to_MODIFY_a] = 
                  "Please use the MODIFY form to MODIFY a ";
?>
