<?php
  # file: lang/EN/tos.php3.EN.inc
  # desc: type of service english (EN) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL

  $record_name = "Type of Service (TOS)";

  $Type_of_Service_Name        = "Type of Service Name";
  $Type_of_Service_Description = "Type of Service Description";
  // 19991013
  $Name                        = "Name";
  $Description                 = "Description";
?>
