<?php
  # file: lang/EN/user.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod: 19991004

  $record_name                         = "User";
  $User_name                           = "User name" ;
  $Password                            = "Password" ;
  $Verify                              = "verify" ;
  $Description                         = "Description" ;
  $Physician_group                     = "Physician Group" ;
  $User_level                          = "User level" ;
  $Locked_out                          = "!!! Locked Out !!!" ;
  $Undefined                           = "UNDEFINED" ;
  $Delete_privs                        = "Delete priv." ;
  $Superuser                           = "SuperUser/Admin." ;
  $Abandon_addition                    = "Abandon this operation" ; # Just say no ;-)
  $Passwords_must_match                = "Passwords must match !" ;
  $Go_back_to_user_menu                = "Go back to the User Menu" ;
  
  $Please_use_the_modify_form          = "Please use the MODIFY form to do this" ;
  $Result                              = "RESULT" ;
  $You_cannot_modify_root              = "You cannot modify the SuperUser" ;
  $You_cannot_delete_root              = "You cannot delete the SuperUser" ;
  $Query_result                        = "Query result" ;
  $Query_string                        = "Query string" ;
  $Actual_query_result                 = "Actual query result" ;
  $Another                             = "Another" ;
  $Maintenance                         = "Maintenance" ;
  $Action                              = "Action" ;
  $No                                  = "No" ;
  $Found_with_that_criteria            = "found with that criteria" ;
  $Try_Again                           = "Try Again";
  $Authorized_facilities               = "Authorized Facilities";
  $Authorized_physicians               = "Authorized Physicians";
  $Authorized_phy_groups               = "Authorized Phy. Groups";
    // 19990909
  $User_type                           = "User Type";
  $Physician                           = "Physician";
  $Miscellaneous                       = "Miscellaneous";
    //19990927 - mark l
  $Update                              = "Update";
  $Remove_changes                      = "Remove Changes";
    // 19990929
  $Actual_physician                    = "Actual Physician";
?>
