<?php
  # file: lang/EN/user.php3.EN.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod: 19991004

  $record_name                         = "User";
  $phrase[User_name]                   = "User name" ;
  $phrase[Password]                    = "Password" ;
  $phrase[Verify]                      = "verify" ;
  $phrase[Description]                 = "Description" ;
  $phrase[Physician_group]             = "Physician Group" ;
  $phrase[User_level]                  = "User level" ;
  $phrase[Locked_out]                  = "!!! Locked Out !!!" ;
  $phrase[Undefined]                   = "UNDEFINED" ;
  $phrase[Delete_privs]                = "Delete priv." ;
  $phrase[Superuser]                   = "SuperUser/Admin." ;
  $phrase[Abandon_addition]            = "Abandon this operation" ; # Just say no ;-)
  $phrase[Passwords_must_match]        = "Passwords must match !" ;
  $phrase[Go_back_to_user_menu]        = "Go back to the User Menu" ;
  
  $phrase[Please_use_the_modify_form]  = "Please use the MODIFY form to do this" ;
  $phrase[Result]                      = "RESULT" ;
  $phrase[You_cannot_modify_root]      = "You cannot modify the SuperUser" ;
  $phrase[You_cannot_delete_root]      = "You cannot delete the SuperUser" ;
  $phrase[Query_result]                = "Query result" ;
  $phrase[Query_string]                = "Query string" ;
  $phrase[Actual_query_result]         = "Actual query result" ;
  $phrase[Another]                     = "Another" ;
  $phrase[Maintenance]                 = "Maintenance" ;
  $phrase[Action]                      = "Action" ;
  $phrase[No]                          = "No" ;
  $phrase[Found_with_that_criteria]    = "found with that criteria" ;
  $phrase[Try_Again]                   = "Try Again";
  $phrase[Authorized_facilities]       = "Authorized Facilities";
  $phrase[Authorized_physicians]       = "Authorized Physicians";
  $phrase[Authorized_phy_groups]       = "Authorized Phy. Groups";
    // 19990909
  $phrase[User_type]                   = "User Type";
  $phrase[Physician]                   = "Physician";
  $phrase[Miscellaneous]               = "Miscellaneous";
    //19990927 - mark l
  $phrase[Update]                      = "Update";
  $phrase[Remove_changes]              = "Remove Changes";
    // 19990929
  $phrase[Actual_physician]            = "Actual Physician";
?>
