<?php
  # file: lang/FR/admin.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Ver : 19991007

  $No_admin_menu_access 	= "Vous n'avez pas accès au menu d'administration" ; 
  $Icd_code_type 		= "Codes CIM" ;
  $Graphics_enhanced 		= "Graphiques" ;
  $Disabled 			= "désactivés" ;
  $Enabled 			= "activés" ;
  $Scheduling_start_time 	= "Début des RDV" ;
  $Scheduling_end_time 		= "Fin des RDV" ;
  $Configure 			= "Accepter" ;
  $Reset 			= "Annuler" ;
  $Configuration_complete 	= "Fin de la configuration" ;
  $Return_adm_menu 		= "Retour au menu d'administration" ;
  $Reinitialize_database 	= "Reinitialiser la base de données" ;
  $Are_you_sure 		= "Etes-vous sur de vouloir" ;
  $Irreversable_process 	= "C'est est un processus irréversible!" ;
  $First_initialization 	= "Cliquer ici s'il s'agit du'une première initialisation" ;
  $Continue 			= "Continuer" ;
  $Cancel 			= "Annuler" ;
  $Erasing_old_db 		= "Effacement des anciennes données" ;
  $Error_accessing_sql 		= "Erreur lors de l'accès de la base de données SQL" ;
  $Done 			= "Terminé" ;
  $Creating_new_db 		= "Création d'une nouvelle base de données" ;
  $Creating_tables 		= "Création de tables" ;
  $Administration_menu 		= "Menu d'Administration" ;
  $Update_config 		= "Mise à jour de la configuration" ;
  $User_maintenance 		= "Configuration des usagers" ;
  $Return_main_menu 		= "Retour au menu principal" ;
  $DEFAULT 			= "PAR DEFAUT";
  $SELECTED 			= "SELECTIONNE";
  $Update_Configuration 	= "Mise à jour de la configuration";
  $Calendar_overbooking         = "Superposition de RDV dans le Calendrier";

?>
