<?php
  # file: lang/FR/API.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Ver : 19991102

  $DEBUG_IS_ON 			= "DEBOGUAGE ACTIF";
  $Return_to_the_Main_Menu 	= "Retour au menu principal";
  $Return_to_Previous_Menu 	= "Retour au menu précédent";
  $lang_main = "principal"; // alt tag for main menu button
  $lang_exit = "sortie"; // alt tag for logout button
  $RETURN_TO_MENU		= "RETOUR AU MENU";
  $ADD                     	= "AJOUTER";
  $NONE_SELECTED           	= "AUCUN SELECTIONNE";
  $SELECTED                	= "SELECTED"; // must NOT be translated
  $lang_coded_by           	= "codé par"; 
  $NO_RESULT_OF_QUERY      	= "PAS DE RESULTAT A LA REQUETE";
  $Entered_incorrect_NamePasswd =
    "Vous avez introduit un nom ou un mot de passe erronés";
  $Possible_Cookies_Have_Expired =
    "Il est aussi possible que vos cookies aient expiré. SVP<BR>
     connectez-vous a nouveau, ou demandez a votre administrateur système<BR>
     d'accroitre le temps de vie des cookies.";
  $Login_Screen			= "Autenthification";
    // 19990824
  $Add				= "Ajouter";
  $Adding                  	= "En train d'ajouter";
  $Clear                   	= "Effacer";
    // 19990917
  $Return_to               	= "Retour à";
  $Main_Menu               	= "Menu principal";
  $Modify                  	= "Modifier";
  $Modifying               	= "En train de modifier";
  $Done                    	= "Fini";
  $Menu                    	= "Menu";
  $Deleting                	= "En train de supprimer";
  $Update_Delete_Another   	= "Mettre à jour/supprimer un autre";
  $Deleted                 	= "Supprimé";
  $Abandon_Addition        	= "Annuler l'ajout";
  $Abandon_Modification    	= "Abandonner la modification";
  $Update                  	= "Mettre à jour";
  $Remove_Changes          	= "Annuler les changements";
  $Exporting_data          	= "En train d'exporter des données";
  $Export                  	= "Exporter";
  $ERROR                   	= "ERREUR";
  $Action                  	= "Action";
  // 19990920
  $lang_ALL                	= "TOUT";
  // 19990921
  $lang_ADD	                = "AJT";
  $lang_MOD                     = "MOD";
  $lang_DEL                     = "EFF";
  // 19990922
  $No_Record_Found              = "Aucun $record_name ne correspond à ces critères.";
  $lang_back                    = "retour";
  // 19990924
  $lang_HELP               = "AIDE";
  $Module                  = "Module";
  $Manage_Patient          = "Gestion Patient";
  // 19991005
  $Week_Of                 = "Semainde de";
  // 19991013
  $Export_Database         = "Exporter les données";

?>
