<?php
  # file: lang/FR/authenticate.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>

  $Error = "ERREUR" ;
  $Return_to_the_login_screen = "Retour au formulaire d'autenthification";
  $Incorrect_name_password= "Vous avez introduit un nom ou un mot de passe <BR>
   erronés. Si l'erreur persiste, veuillez contacter votre administrateur <BR>
   système. Veuillez prendre note des circonstances dans lesquelles ce message <BR>
   est apparu, et communiquez également ces informations à votre <BR>
   administrateur système. Elles seront utiles pour signaler un bogue." ;

?>
