<?php
  # file: lang/FR/book_appointment.php3.FR.inc
  # desc: book appointment french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991008

  $Add_Appointment                     = "Ajouter Rendez-Vous";
  $lang_day                            = "jour";
  $lang_week                           = "semaine";
  $lang_prev                           = "prec";
  $lang_next                           = "proch";
  $Current_Date_is                     = "Nous sommes le";
  $this_date_occurs_in_the_past        = "Cette date est passée";
  $Current_Patient                     = "Patient Actuel";
  $Room                                = "Salle";
  $Check_Room                          = "Vérifier la Salle";
  $Try_Again                           = "Essayez à nouveau";
  $Date                                = "Date";
  $The_selected_room_is_free_all_day   = "La salle sélectionnée est libre toute la journée.";
  $TIME                                = "HEURE";
  $NO_PREFERENCE                       = "PAS DE PREFERENCE";
  $Patient                             = "Patient";
  $Time                                = "Heure";
  $lang_hour                           = "heure";  // singular
  $lang_hours                          = "heures"; // plural
  $lang_min_abbrev                     = "min";    // abbreviated minutes
  $lang_h                              = "h";      // single letter for hours
  $lang_m                              = "m";      // single letter for minutes
  $Duration                            = "Durée";
  $Physician                           = "Médecin";
  $Note                                = "Note";
  $Adding_Appointment                  = "En train d'ajouter le RDV";
?>
