<?php
  # file: lang/FR/call-in.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Mod : 19990830

$Call_In              = "Appel";
$Add                  = "Ajouter";
$Adding               = "En train d'ajouter";
$Clear                = "Effacer";
$Name                 = "Nom";
$Last                 = "Patronyme";
$First                = "Prénom";
$Middle               = "Suppl.";
$Contact_Information  = "Informations de contact";
$Home_Phone           = "Tél. Domicile";
$Work_Phone           = "Tél. Travail";
$Took_Call            = "Appel pris par";
$Date_of_Birth        = "Date de naissance";
$Complaint            = "Message";
$Facility             = "Local";
$Physician            = "Médecin";
$Patient_Menu         = "Menu Patients";
$Call_In_Menu         = "Menu Appels";
$Main_Menu            = "Menu Principal";
$NOT_IMPLEMENTED_YET  = "PAS ENCORE IMPLEMENTE";
$Date_of_Call         = "Date de l'appel";
$Home_Work_Phone      = "Tel. Dom./Trav.";
$Action               = "Action";
$VIEW                 = "VOIR";
$BOOK                 = "RDV";
  // 19990920
$Old                  = "Anciens";
$All                  = "Tous";
$Current              = "Courants";

?>
