<?php
  # file: lang/FR/cpt.php3.FR.inc
  # desc: CPT codes french (FR) language module
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver : 19990921

  $record_name                      = "Codes de Procédure";

  $CPT_Code                         = "Code de Procédure";
  $CPT_Name_Internal                = "Nom C.P. (Interne)";
  $CPT_Name_External                = "Nom C.P. (Externe)";
  $Relative_Value                   = "Valeur relative";
  $Example                          = "ex.";
  $Type_of_Service                  = "Type de Service";
  $Internal_Name                    = "Nom Interne";
?>
