<?php
  # file: lang/FR/db_maintenance.php3.FR.inc
  # desc: database maintenance menu french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver: 19991102


  $Database_Maintenance            = "Configuration de la base de données";
  $CPT_Procedural_Codes            = "CPT/Codes de procédures";
  $CPT_Procedural_Modifiers        = "CPT/Modificateurs de Procédures";
  $Formulary_Pharmacy_Module       = "Module de prescriptions";
  $ICD_Codes                       = "Codes CIM 9/10";
  $Insurance_Companies             = "Compagnies d'Assurances";
  $Insurance_Company_Groups        = "Groupes de Compagnies d'Assurances";
  $Physicians                      = "Médecins";
  $Physician_Degrees               = "Titres des Médecins";
  $Physician_Groups                = "Groupes de Médecins";
  $Physician_Specialties           = "Spécialités de Médecins";
  $Physician_Statuses              = "Statuts de Médecins";
  $Place_of_Service_Facilities     = "Locaux d'exercice";
  $Rooms                           = "Chambres";
  $Scheduling_Locations            = "Locaux pour RDV";
  $Type_of_Service                 = "Types de services";
  $Templates_for_Simple_Reports    = "Modèles de rapports";
  $You_dont_have_access_for_this_menu = "Vous n'avez pas accès à ce menu.";
  $Selectable_Printers             = "Imprimantes Disponibles" ;
  $Fixed_Forms                     = "Formulaires" ;
  $Custom_Patient_Record_Templates = "Modèles de Fiches du Dossier Patient" ;
  $Diagnosis_Families              = "Familles de Diagnostics" ;
?>
