<?php
  # file: lang/FR/degrees.php3.FR.inc
  # desc: physician degrees french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name                         = "Titres et Degrés";

  $Degree_Title                        = "Titre";
  $Degree_Title_Example                = "Spécialiste en Rhumatologie, etc";
  $Degree_Name                         = "Abbreviation";
  $Degree_Name_Example                 = "MD, DPM, etc";
  $Date_Last_Modified                  = "Date de la dernière modification";
  $Degree                              = "Titre";
  $Description                         = "Description";
  $No_degrees_are_currently_in_the_database =
     "Il n'y a actuellement aucun titre dans la base de données.";
?>
