<?php
  # file: lang/FR/facility.php3.FR.inc
  # desc: facility (place of service) french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver: 19991005

  $record_name = "Locaux de pratique";

  $Facility_Name                  = "Dénomination";
  $Address_Line_1                 = "Ligne d'adresse 1";
  $Address_Line_2                 = "Ligne d'adresse 2";
  $City                           = "Ville";
  $State                          = "Etat/Canton";
  $Zip                            = "Code Postal";
  $Description_Note               = "Description";
  $Default_Physician              = "Médecin par défaut";
  $Phone_Number                   = "Numéro Tel.";
  $Fax_Number                     = "Numéro Fax.";
  $Email_Address                  = "Courriel";
  $Date_of_Entry                  = "Date d'entrée";
  $Country                        = "Pays";   // 19991005
?>