<?php
  # file: lang/FR/frmlry.php3.FR.inc
  # desc: formulary/pharmacy french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation : max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name = "Formulaire";

  $Class                          = "Classe";
  $Generic_Name                   = "Nom Générique";
  $Trademark_Name                 = "Nom Commercial";
  $Indication_1                   = "Indication 1";
  $Indication_2                   = "Indication 2";
  $Indication_3                   = "Indication 3";
  $Date_Added                     = "Date d'ajout";
?>
