<?php
  # file: lang/FR/index.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod : 19990924

  $Username            = "Usager";
  $Password            = "Mot de passe";
  $Enter_the_database  = "Accès à la Base";
  $Clear               = "Effacer";
  $Language            = "Langue";
  $Default             = "Par défaut";
  $Facility            = "Local";
  $Login               = "Login";
    // 19990922
  $Resume              = "Retour à l'édition";
  $Reset_Resume        = "Effacer point de retour";

?>
