<?php
  # file: lang/FR/main.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Mod: 19991008

  $Main_menu                 = "Menu Principal" ;
  $Administration_menu       = "Menu d'Administration" ;
  $Billing_functions         = "Facturation" ;
  $Database_maintenance      = "Configuration BD" ;
  $Patient_functions         = "Patients" ;
  $Help_main_menu            = "Aide pour le menu principal" ;
  $Logout_of                 = "Sortir de" ;
  $Quickjump                 = "ALLER A" ;
  $User_level                = "NIVEAU USAGER" ;
  $User_description          = "DESCRIPTION" ;
  $Call_in                   = "Appels";
  $Entry                     = "Nouveau";
  $Menu                      = "Menu"; 
  // 19990929
  $Day_View                  = "Vue de la Journée";
  $Week_View                 = "Vue Hebdomadaire (Calendrier)";
?>
