<?php
  # file: lang/FR/manage.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod : 19990921

  $Attach_to_Guarantor           = "Lier à un Garant";
  $Must_select_a_patient         = "Vous devez sélectionner un patient.";
  $Select_Guarantor_to_Attach_to = "Choisir le Garant de référence :";
  $detach                        = "détacher";
  $Attach                        = "Attacher";
  $Return_to_Patient_Management  = "Retour a la gestion du patient";
  $Attaching_Guarantor           = "En train de lier au Garant";
  $Detaching_current_dependants  = "En train de détacher les actuels dépendants";
  $lang_done                     = "terminé.";
  $Manage_Patient                = "Gestion du Patient";
  $Select_a_patient              = "Selectionnez un Patient";
  $Patient_Information           = "Information sur le Patient";
  $Modify                        = "Modifier";
  $Add                           = "Ajouter";
  $View_Manage                   = "Voir/Administrer";
  $Prescriptions                 = "Prescriptions";
  $Procedures                    = "Procedures";
  $Progress_Notes                = "Notes Cliniques";
  $Reports_and_certificates      = "Rapports et Certificats";  //19990813
  $Choose                        = "Choisir";                  //19990813
  $Show_Dependants               = "Voir les Dependants";
  $Show_Guarantor                = "Voir le Garant";
  $Last_Name                     = "Nom de Famille";
  $All                           = "Tous";
  $Select_Another_Patient        = "Selectionner un autre Patient";
    // 19990809
  $Appointments                  = "Rendez-vous";
  $Book                          = "Livre";
  $Patient                       = "Patient";
  $Show_Today                    = "Montrer aujourd'hui";
?>
