<?php
  # file: lang/FR/phy_avail_map.FR.inc
  # desc: physician available map french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation : max k <amk@span.ch>
  # ver : 19991006

  $record_name = "Disponibilités du médecin";

  $Must_specify_physician          = "Vous devez spécifier un médecin!";
  $Absence_date_from               = "Changement de disponibilité (Date début)";
  $Absence_date_to                 = "Changement de disponibilité (Date fin)";
  $Time_beginning                  = "Début d'activité";
  $Time_ending                     = "Fin d'activité";
  // 19991005
  $lang_to                         = "à";
  $Comment                         = "Commentaire";
  $Physician                       = "Médecin";
  $Availability                    = "Disponibilité";

?>