<?php
  # file: lang/FR/phygroup.php3.FR.inc
  # desc: physician group french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19990924

  $record_name = "Groupes de Médecins";

  $Physician_Group_Name               = "Nom du Groupe de Médecins";
  $Default_Facility                   = "Local par Défaut";
  $Group_Name                         = "Nom";
?>
