<?php
  # file: lang/FR/physician.php3.FR.inc
  # desc: physician maintenance menu french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation : max k <amk@span.ch>
  # lic : GPL
  # ver : 19991104

  $Add_Physician                   = "Ajouter un Médecin"  ;
  $Last_name                       = "Nom"                 ;
  $First_name                      = "Prénom"              ;
  $Title                           = "Titre"               ;
  $Middle_Name                     = "Complément"          ;
  $Practice_Name                   = "Nom au Cabinet"      ;
  $Primary_Address_Line            = "Adresse Principale Ligne"  ;
  $Primary_Address_City            = "Adresse Principale Ville"  ;
  $Primary_Address_State           = "Adresse Principale Canton" ;
  $Primary_Address_Zip             = "Adresse Principale Code Postal" ;
  $Primary_Address_Phone           = "Adresse Principale Téléphone"   ;
  $Primary_Address_Fax             = "Adresse Principale Fax"         ;
  $Secondary_Address_Line          = "Adresse Secondaire Ligne"       ;
  $Secondary_Address_City          = "Adresse Secondaire Ville"       ;
  $Secondary_Address_State         = "Adresse Secondaire Canton"      ;
  $Secondary_Address_Zip           = "Adresse Secondaire Code Postal" ;
  $Secondary_Address_Phone         = "Adresse Secondaire Téléphone"   ;
  $Secondary_Address_Fax           = "Adresse Secondaire Fax"         ;
  $Email_Address                   = "Courriel"            ;
  $Cellular_Phone                  = "Tel. Portable"       ;
  $BeeperPager                     = "Autre Gadgetophone"  ;
  $UPIN_Number                     = "Numéro de Convention";
  $Social_Security                 = "Numéro de Sécurité Sociale" ;
  $Degree                          = "Diplôme"             ;
  $Specialty                       = "Spécialité"          ;
  $Internal_ID                     = "Numéro Interne"      ;
  $Status                          = "Statut"              ;
  $Reference                       = "Référence"           ;
  $Number_of_Referrals             = "Nombre de Patients Référés"    ;
  $Primary_care_provider           = "Fournisseur de Soins Primaire" ;
  $Referring                       = "Référent"                      ;
  $NULL                            = "AUCUN"                         ;
  $Number_of_Referrals             = "Nombre de Référés"             ;
  $Referral_Amount                 = "Produit des Références"          ;
  $S_charged                       = "F facturés"          ;
  $S_received                      = "F reçus"             ;
  $Add                             = "Ajouter"             ;
  $Clear                           = "Effacer"             ;
  $Adding_Physician                = "En train d'ajouter un médecin"  ;
  $Adding                          = "En train d'ajouter"             ;
  $Done                            = "Terminé"             ;
  $ERROR                           = "ERREUR"              ;
  $Physician                       = "Médecin"             ;
  $Modify_Physician                = "Modifier le Médecin" ;
  $Please_use_the_MODIFY_form_to_MODIFY_someone = "SVP Utilisez le formulaire de MODIFICATION pour ce faire" ;
  $Return_to_the_Main_Menu         = "Retour au Menu Principal";
  $Update                          = "Mise à jour"             ;
  $Abandon_Modification            = "Abandonner la Modification";
  $Modifying_Physician             = "En train de Modifier le Médecin" ;
  $Modifying                       = "En train de Modifier"            ;
  $Deleting_Physician              = "En train de supprimer le Médecin";
  $RESULT                          = "RESULTAT"                  ;
  $Delete_Another                  = "Supprimenr un autre"       ;
  $Physician_Display               = "Voir le Médecin"           ;
  $You_must_specify_an_id          = "Vous devez spécifier un numéro" ;
  $Return_to_the_Physician_Menu    = "Retour au Menu des Médecins"    ;
  $NONE_SELECTED                   = "AUCUN SELECTIONNE"              ;
  $Physicians                      = "Médecins"                       ;
  $Last_Name                       = "Nom"                            ;
  $First_Name                      = "Prénom"                  ;
  $Degrees                         = "Diplômes"                ;
  $Action                          = "Action"                  ;
  $VIEW                            = "VOIR"                    ;
  $MOD                             = "MOD"                     ;
  $DEL                             = "EFF"                     ;
  $No_physicians_found_with_that_criteria = "Aucun médecin ne correspond à ces critères" ;



?>