<?php
  # file: lang/FR/phystatus.php3.FR.inc
  # desc: physician status french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name               = "Statuts de Médecins";

  $Status                    = "Statut";
  $Update                    = "Mettre à Jour";
  $Remove_Changes            = "Annuler les Changements";
  $Abandon_Modification      = "Abandonnner la Modification";
  $Modifying                 = "En train de modifier";
  $Done                      = "Terminé";
  $Return_to_Previous_Menu   = "Retour au menu précédent";
  $Return_to_the_Main_Menu   = "Retour au menu principal";
  $Deleting                  = "En train d'effacer";
  $Deleted                   = "Effacé";
  $RESULT                    = "RESULTAT";
  $Update_Delete_Another     = "Mettre à jour ou effacer un autre";
  $Return_to                 = "Retour à";
  $RETURN_TO_MENU            = "RETOUR AU MENU";
  $No_Record_Found           = "Aucun enregistrement trouvé";
?>
