<?php
  # file: lang/FR/physician_week_view.php3.FR.inc
  # desc: physician weekly view french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver : 19991006 

  $Physician_Weekly_View                   = "Emploi du temps hebdomadaire";
  $back_one_week                           = "semaine précédente";
  $forward_one_week                        = "semaine suivante";
  $No_Physician_Selected                   = "Aucun médecin sélectionné"; 
  $Physician                               = "Médecin";

?>
