<?php
  # file: lang/FR/physician_day_view.php3.FR.inc
  # desc: physician daily view french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver: 19991004

  $Physician_Daily_View                    = "Journée du médecin";
  $back_one_day                            = "précédente";
  $forward_one_day                         = "suivante";
  $No_Physician_Selected                   = "Pas de médecin sélectionné"; 
  $Physician                               = "Médecin";
?>
