<?php
  # file: lang/FR/progress_notes.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver: 1990921

  $record_name                  = "Notes Cliniques";
  $Module                       = "Module";
  $ERROR                        = "ERREUR";
  $Must_Specify_A_Patient       = "Vous devez spécifier un patient!";
  $Entry                        = "Entrée";
  $Manage_Patient               = "Administrer Patient";
  $View_Modify                  = "Voir/Modifier";
  $Applicable_Date              = "Date Applicable";

    // the actual progress parts (with underlines)
  $Subjective                   = "<U>S</U>ubjectivement";
  $Objective                    = "<U>O</U>bjectivement";
  $Assessment                   = "ev<U>A</U>luation";
  $Plan                         = "<U>P</U>lan";
  $Interval                     = "<U>I</U>ntervalle";
  $Education                    = "<U>E</U>ducation";
  $Prescription                 = "p<U>R</U>escription";

  $Add                          = "Ajouter";
  $Clear                        = "Effacer";
  $Abort_Addition               = "Annuler l'ajout";
  $Adding                       = "En train d'ajouter";
  $Done                         = "Terminé";
  $FAILED                       = "ECHEC";
  $Must_Call_With_Patient_ID    = "vous devez appeler cette fonction avec un ".
                                  "patient sélectionné.";
  $Modify                       = "Modifier";
  $Change                       = "Changer";
  $Restore                      = "Récupérer";
  $Modifying                    = "En train de modifier";
  $View                         = "Voir";
  $Menu                         = "Menu";
  $Specify_Notes_to_Display     = "Vous devez préciser quelles notes ".
                                  "il faut montrer.";
  $Modify_Notes                 = "Modifier les Notes";
  $Patient                      = "Patient";
  $This_Patient_Has_No_Notes    = "Ce patient n'a pas de notes jusqu'à ce jour.";
  $Existing                     = "Existantes";
?>
