<?php
  # file: lang/FR/roomequip.php3.FR.inc
  # desc: room equipment french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19990921

  $record_name                       = "Dispositif des Chambres";
  $Name_of_Equipment                 = "Nom";
  $Description                       = "Description";
  $Equipment                         = "Equipement";
?>
