<?php
  # file: lang/FR/room.php3.FR.inc
  # desc: room (scheduling location) french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name = "Salles";

  $Room_Name                      = "Nom de la Salle";
  $Location                       = "Localisation";
  $Room_Description               = "Description de la Salle";
  $Default_Physician              = "Médecin par Défaut";
  $Surgery_Equipped               = "Equipement de Chirurgie?";
  $Is_Booking_Enabled             = "Est-ce que les RDV sont activés?";
  $IP_Address                     = "Addresse IP";
  $For_Future_Use                 = "Pour un futur usage";
  $For_Scheduling                 = "Pour les RDV";
  $Description                    = "Description";
?>
