<?php
  # file: lang/FR/Rx.php3.FR.inc
  # desc: prescription module french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation : max k <amk@span.ch>
  # ver : 19991006

  $record_name = "Prescription";

  $Must_Have_Patient_For_Prescriptions =
    "Vous devez avoir sélectionné un patient pour utiliser ce module de prescription.";
  $No_Access_To_This_Patient           =
    "Vous n'avez pas accès au dossier de ce patient.";
  $Display                             = "Montrer";
  $Patient                             = "Patient";
  $Drug                                = "Médicament";
  $Dosage                              = "Dosage";
  $Starting_Date                       = "Date début";
  $In_Days                             = "en jours";
  $Infinite                            = "0 = infini";
  $Refills                             = "Renouvellements";
  $Substitution                        = "Substitution";
  $May_Not_Substitute                  = "Ne pas substituer";
  $May_Substitute                      = "Peut substituer";
  $Manage_Prescriptions                = "Gestion d'ordonnances";
  // 19991002
  $Duration                            = "Durée";
?>
