<?php
  # file: lang/FR/select_printer.php3.FR.inc
  # desc: Selectable printer management french (FR) language file
  # code: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991020

  $record_name    = "Selection d'Imprimantes"     ;

  $Selectable_Printer    = "Imprimante à sélectionner" ;
  $Printer_Name          = "Nom de l'Imprimante"  ;
  $Printer_Host          = "Machine Hôte"         ;
  $Access_Level          = "Niveau d'accès"       ;
  $Description           = "Description"          ;
  $Add                   = "Ajouter"              ;
  $Clear                 = "Effacer"              ;
  $Adding                = "En train d'ajouter"   ;
  $Done                  = "Terminé"              ;
  $ERROR                 = "ERREUR"               ;
  $Return_to             = "Retourner à"          ;
  $Menu                  = "Menu"                 ;
  $Modify                = "Modifier"             ;
  $Please_use_MODIFY     = "SVP Utilisez le formulaire de MODIFICATION" ;
  $Return_to_the_Main_Menu = "Retour au Menu Principal"  ;
  $RESULT                = "RESULTAT"             ;
  $Abandon_Addition      = "Abandonner l'Addition";
  $Update                = "Mettre à Jour"        ;
  $Remove_Changes        = "Effacer les Changements"     ;
  $Abandon_Modification  = "Abandonnner la Modification" ;
  $Modifying             = "En train de Modifier" ;
  $Deleting              = "En train d'Effacer"   ;
  $Deleted               = "Effacé"               ;
  $Update_Delete_Another = "Effacer ou Modifier une Autre" ;
  $Export                = "Exporter"               ;
  $Exporting_data        = "En train d'Exporter des Données" ;
  $Action                = "Action"               ;
  $Printer               = "Imprimante"           ;
  $Host                  = "Hôte"                 ;
  $MOD                   = "MOD"                  ;
  $DEL                   = "EFF"                  ;
  $No_Record_Found       = "Aucun Enregistrement Trouvé"    ;
  $Current_Contents      = "Contient Actuellement"          ;
  $For_Reference         = "Pour Référence"                 ;

?>
