<?php
  # file        : lang/FR/simplerep.php3.FR.inc
  # code        : jeff b <jeff@univrel.pr.uconn.edu>
  # Translation : max k <amk@span.ch>
  # lic         : GPL
  # ver         : 19991103

  $record_name = "Générateur de rapports";

  $Add                         = "Ajouter";
  $Clear                       = "Effacer"; 
  $Label                       = "Identificateur";
  $Category                    = "Catégorie";
  $Text                        = "Texte";
  $Abandon_Addition            = "Abandonner l'ajout";
  $Adding                      = "En train d'ajouter";
  $Return_to                   = "Retour à";
  $Modify                      = "Modifier";
  $Please_use_MODIFY           = "SVP utilisez le masque MODIFIER pour ce faire";
  $Return_to_the_Main_Menu     = "Retour au menu principal";
  $Update                      = "Mettre à jour";
  $Remove_Changes              = "Renoncer aux changements";
  $Abandon_Modification        = "Renoncer à la modification";
  $Modifying                   = "En train de modifier";
  $Done                        = "Terminé";
  $ERROR                       = "ERREUR";
  $Menu                        = "Menu";
  $Deleting                    = "En train d'effacer";
  $Deleted                     = "Effacé";
  $Update_Delete_Another       = "Mettre à jour/Supprimer un autre";
  $Must_Have_Patient_to_Make_Reports =
    "Vous devez d'abord sélectionner un patient pour générer des rapports!";
  $Choose_Report_for_Patient   = "Choisir un rapport pour ce patient";
  $Patient                     = "Patient";
  $Manage_Patient              = "Administrer le patient";
  $Action                      = "Action";
  $Mr                          = "M";   // 19990926
  $Mrs                         = "Mme";
  $Report                      = "Rapport";
  $Physician                   = "Médecin";
  $Facility                    = "Local";
  $Proceeding                  = "continuer";  //  19990927
  $Proceed                     = "Continuer";
  $Please_choose               = "SVP choisir";  // 19990927
  $Before                      = "avant de";
  $Return_to_report_selection  = "Retour à la sélection de rapports"; // 19990928
  $Destinatary_is              = "Le destinataire est";
  $Delivery_Method             = "Moyen d'envoi";
  $NONE_SELECTED               = "AUCUN SELECTIONNE";
  $The_Patient                 = "Le patient";
  $A_Physician                 = "Un médecin";
  $An_Insurer                  = "Un assureur";
  $Other                       = "Autre";
  $Printer                     = "Imprimante";
  $Fax                         = "Fax"; //that one will be hard to translate <G>
  $E_mail                      = "Courriel";
  $Edit_report_for_patient     = "Editer le rapport pour le patient";
  $Phone                       = "Téléphone";  //19991005
  $Datequalif                  = "le";
  $Help_for_simple_reports     = "Aide pour le générateur de rapports";
  $Edit_add_simple_reports     = "Ajouter ou Editer des Rapports";  // 19991007
  $Patients_primary_insurer    = "Premier Assureur du Patient";   // 19991008
  $Patients_secundary_insurer  = "Deuxième Assureur du Patient";
  $Patients_tertiary_insurer   = "Troisième Assureur du Patient";
  $Select_from_contact_list    = "Choisir dans la Liste de Contacts";
  $Patients_primary_employer   = "Premier Employeur du Patient";
  $Patients_secundary_employer = "Deuxième Employeur du Patient";
  $No_delivery_method_selected = "Pas de méthode d'envoi sélectionnée!"; // 19991008
  $Print                       = "Imprimer";
  $To                          = "Destinataire";                      // 19991009
  $Patient_has_no_fax          = "Désolé, ce patient n'a pas de numéro de fax..." ;
  $Send                        = "Envoyer ce" ;
  $Patient_has_no_email        = "Désolé, ce patient n'a pas de e-mail" ;
  $A_physician_must_sign_his_own_name = "Un médecin doit signer avec son propre nom";
  $Verification_Key            = "Clef d'authentification" ;
  $Suppress_headers            = "Supprimer les en-têtes" ;
  $Show_full_titles            = "Montrer tous les titres et diplômes du Médecin" ;
  $Mailed                      = "Message Envoyé" ;
  $From                        = "De" ;
  $Copy_to                     = "Copie à" ;
  $Subject                     = "Sujet" ;
  $Male                        = "Masculin"  ;
  $Female                      = "Féminin"   ;
  $Adult                       = "Adulte"    ;
  $Child                       = "Enfant"    ;
  $Return_to_reports_menu      = "Retourner au Menu des Rapports" ;  


?>
