<?php
  # file: lang/FR/simplerep_lout.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # module: max k <amk@span.ch>
  # lic : GPL
  # ver: 19991026


  $Verification_Key            = "Clef de Vérification"  ;
  $To                          = "Destinataire"          ;
  $Generate_lout_for           = "Génère lout pour"      ;
  $Sr_page                     = "Page"                  ;
  $From                        = "De"                    ;
  $Of                          = "de"                    ;
  $Page                        = "Page"                  ;
  $Return_to_report_selection  = "Retour au Sélecteur de Rapports" ;

?>