<?php
  # file: lang/FR/specialties.php3.FR.inc
  # desc: specialties french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19990924

  $record_name = "Specialités";

  $Specialty_Name                        = "Nom de la Spécialité";
  $Specialty_Description                 = "Description de la Spécialité";
  $Name                                  = "Nom";
  $Description                           = "Description";
?>
