<?php
  # file: lang/FR/tos.php3.FR.inc
  # desc: type of service french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991015

  $record_name = "Types de Services (TdS)";

  $Type_of_Service_Name        = "Nom TdS";
  $Type_of_Service_Description = "Description TdS";
  // 19991013
  $Name                        = "Nom";
  $Description                 = "Description";
?>
