<?php
  # file: lang/FR/user.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod: 19991004

  $record_name                      = "Usager";  

  $Add                              = "Ajouter" ;
  $Adding                           = "En train d'ajouter" ;
  $Modify                           = "Modifier" ;
  $Modifying                        = "En train de modifier" ;
  $User_name                        = "Usager" ;
  $Password                         = "Mot de passe" ;
  $Verify                           = "vérifier" ;
  $Description                      = "Description" ;
  $Physician_group                  = "Groupe de Médecins" ;
  $User_level                       = "Niveau d'accès" ;
  $Locked_out                       = "!!! Exclu !!!" ;
  $Undefined                        = "NON DEFINI" ;
  $Delete_privs                     = "Peut Effacer" ;
  $Superuser                        = "SuperUsager/Admin." ;
  $Update                           = "Actualiser" ;
  $Remove_changes                   = "Annuler les modifications" ;
  $Abandon_addition                 = "Abandonner l'opération" ; # Just say no ;-)
  $Passwords_must_match             = "Erreur dans la répétition des mots de passe !" ;
  $Done                             = "Terminé" ;
  $Go_back_to_user_menu             = "Retour au menu des usagers" ;
  $Please_use_the_modify_form       = "SVP utilisez le formulaire MODIFIER pour ça" ;
  $Return_to_main_menu              = "Retour au menu principal" ;
  $Result                           = "RESULTAT" ;
  $Error                            = "ERREUR" ;
  $You_cannot_modify_root           = "Vous ne pouvez pas modifier le superusager" ;
  $You_cannot_delete_root           = "Vous ne pouvez pas effacer le superusager" ;
  $Query_result                     = "Résultat de la requête" ;
  $Query_string                     = "Chaîne de la requête" ;
  $Actual_query_result              = "Code en retour de la requête" ;
  $Deleting                         = "En train d'effacer" ;
  $Delete                           = "Effacer" ;
  $Another                          = "Un autre" ;
  $Maintenance                      = "Manutention" ;
  $Action                           = "Action" ;
  $No                               = "Aucun" ;
  $Found_with_that_criteria         = "trouvé avec ces critères" ;
  $Try_Again                        = "Essayez à nouveau";       // 19990813
  $Authorized_facilities            = "Locaux authorisés";
  $Authorized_physicians            = "Médecins Authorisés";
  $Authorized_phy_groups            = "Groupes de médecins authorisés"; 
  $User_type                        = "Type d'usager";
  $Physician                        = "Médecin";
  $Miscellaneous                    = "Divers";
  $lang_MOD			    = "MOD" ;
  $lang_DEL			    = "EFF" ;
  $Actual_physician                 = "Médecin réel";

?>
