<?php
  # file: lang/FR/user.php3.FR.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod: 19991004
  # mod: 20000529 adam b (phrase[])

  $record_name                      = "Usager";  

//    this is in API.inc
//  $Add                              = "Ajouter" ;
//  $Adding                           = "En train d'ajouter" ;
//  $Modify                           = "Modifier" ;
//  $Modifying                        = "En train de modifier" ;
  $phrase[User_name]             = "Usager" ;
  $phrase[Password]              = "Mot de passe" ;
  $phrase[Verify]                = "vérifier" ;
  $phrase[Description]           = "Description" ;
  $phrase[Physician_group]       = "Groupe de Médecins" ;
  $phrase[User_level]            = "Niveau d'accès" ;
  $phrase[Locked_out]            = "!!! Exclu !!!" ;
  $phrase[Undefined]             = "NON DEFINI" ;
  $phrase[Delete_privs]          = "Peut Effacer" ;
  $phrase[Superuser]             = "SuperUsager/Admin." ;
  $phrase[Update]                = "Actualiser" ;
  $phrase[Remove_changes]        = "Annuler les modifications" ;
  $phrase[Abandon_addition]      = "Abandonner l'opération" ; # Just say no ;-)
  $phrase[Passwords_must_match] 
                             = "Erreur dans la répétition des mots de passe !" ;
  $phrase[Done]                  = "Terminé" ;
  $phrase[Go_back_to_user_menu]  = "Retour au menu des usagers" ;
  $phrase[Please_use_the_modify_form]
                               = "SVP utilisez le formulaire MODIFIER pour ça" ;
  $phrase[Return_to_main_menu]   = "Retour au menu principal" ;
  $phrase[Result]                = "RESULTAT" ;
  $phrase[Error]                 = "ERREUR" ;
  $phrase[You_cannot_modify_root]
                                = "Vous ne pouvez pas modifier le superusager" ;
  $phrase[You_cannot_delete_root]
                                = "Vous ne pouvez pas effacer le superusager" ;
  $phrase[Query_result]         = "Résultat de la requête" ;
  $phrase[Query_string]         = "Chaîne de la requête" ;
  $phrase[Actual_query_result]  = "Code en retour de la requête" ;
  $phrase[Deleting]             = "En train d'effacer" ;
  $phrase[Delete]               = "Effacer" ;
  $phrase[Another]              = "Un autre" ;
  $phrase[Maintenance]          = "Manutention" ;
  $phrase[Action]               = "Action" ;
  $phrase[No]                   = "Aucun" ;
  $phrase[Found_with_that_criteria] = "trouvé avec ces critères" ;
  $phrase[Try_Again]            = "Essayez à nouveau";       // 19990813
  $phrase[Authorized_facilities]  = "Locaux authorisés";
  $phrase[Authorized_physicians]  = "Médecins Authorisés";
  $phrase[Authorized_phy_groups]  = "Groupes de médecins authorisés"; 
  $phrase[User_type]            = "Type d'usager";
  $phrase[Physician]            = "Médecin";
  $phrase[Miscellaneous]        = "Divers";
  $phrase[MOD]                  = "MOD" ;
  $phrase[DEL]                  = "EFF" ;
  $phrase[Actual_physician]     = "Médecin réel";
?>
