<?php
  # file: lang/DE/admin.php3.DE.inc
  # code: Max Klohn <amk@span.ch>
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004
  # lic : GPL
  # mod : 19990917

  $No_admin_menu_access = "Der Zugriff zum Administrationsmenü wurde verweigert";     
  # "You do not have access to the Administrative Menu" ; 
  $Icd_code_type = "Geben Sie den ICD Code ein"; 
  #"ICD code type" ;
  $Graphics_enhanced = "Graphiken vergrößert" ;
  $Disabled = "Ausgeschaltet" ;
  $Enabled = "Eingeschaltet" ;
  $Scheduling_start_time = "Startzeit des Behandlungsplanes";
  #"Scheduling Starting Time" ;
  $Scheduling_end_time = "Endzeit des Behandlungsplanes";
  #"Scheduling Ending Time" ;
  $Configure = "Konfigurieren" ;
  $Reset = "Zurücksetzen" ;
  $Configuration_complete = "Konfiguration beendet" ;
  $Return_adm_menu = "Zurück zum Administrationsmenü" ;
  $Reinitialize_database = "Datenbank neu initialisieren" ;
  $Are_you_sure = "Sind Sie SICHER, daß Sie das wollen?" ;
  $Irreversable_process = "Dieser Vorgang kann nicht mehr rückgängig gemacht werden!" ;    
  #"This is an irreversible process!" ;   
  $First_initialization = "Prüfen Sie hier falls dies die erste Initialisierung ist" ;   
  #"Check here if it is a first intitialization" ;  
  $Continue = "Fortsetzen" ;   
  $Cancel = "Abbrechen" ;
  $Erasing_old_db = "Alte Datenbank löschen" ;
  $Error_accessing_sql = "Fehler während des Zugriffes auf die SQL Datenbank" ;
  #"Error while accessing the SQL database" ;
  $Creating_new_db = "Neue Datenbank anlegen" ;
  $Creating_tables = "Tabellen anlegen" ;
  $Administration_menu = "Administrationsmenü " ;
  $Update_config = "Update konfigurieren" ;
  $User_maintenance = "Benutzerverwaltung" ;
  $Return_main_menu = "Zurück zum Hauptmenü" ;
  $DEFAULT = "VOREINSTELLUNG";
    // 19990830
  $SELECTED = "AUSGEWÄHLT";
  $Update_Configuration = "Update konfigurieren";
?>
