<?php
  # file: lang/DE/API.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung von Johann KRAUTINGER <j.krau@teleweb.at> 19991102

  $DEBUG_IS_ON = "DEBUG IS ON";
  $Return_to_the_Main_Menu = "Zurück zum Hauptmenü";
  $Return_to_Previous_Menu = "Zurück zum vorherigen Menü";
  $lang_main = "Hauptmenü"; // alt tag for main menu button
  $lang_exit = "Beenden"; // alt tag for logout button
  $RETURN_TO_MENU          = "Zurück zur Übersicht";
  $NONE_SELECTED           = "NICHTS AUSGEWÄHLT";
  $SELECTED                = "SELECTED"; // must NOT be translated
  $lang_coded_by           = "PROGRAMMIERT VON"; 
  $NO_RESULT_OF_QUERY      = "Kein Ergebnis auf diese Abfrage";
  $Entered_incorrect_NamePasswd =
    "Der Benutzername oder das Passwort war nicht korrekt";
  $Possible_Cookies_Have_Expired =
    "Es ist möglich, daß Ihre Cookies abgelaufen sind. Bitte<BR>
     melden Sie sich neu an,oder bitten Sie Ihren Systemadministrator <BR>      
     die Laufzeit Ihrer Cookies zu verlängern.";
  $Login_Screen            = "Anmeldungs Menü";
    // 19990824
  $Add                     = "Hinzufügen";
  $Adding                  = "wird hinzugefügt"; #"Adding"
  $Clear                   = "Löschen";
    // 19990917
  $Return_to               = "Zurück";
  $Main_Menu               = "Haupt Menü";
  $Modify                  = "Erneuern";
  $Modifying               = "wird erneuert";
  $Done                    = "FERTIG";
  $Menu                    = "ÜBERSICHT";
  $Deleting                = "WIRD GELÖSCHT";
  $Update_Delete_Another   = "UPDATEN/LÖSCHEN/ANDERE WAHL";
  $Deleted                 = "wurde gelöscht";
  $Abandon_Addition        = "Abandon Addition";
  $Abandon_Modification    = "Abandon Modification";
  $Update                  = "Update";
  $Remove_Changes          = "Änderungen verwerfen";
  $Exporting_data          = "Daten exportieren";
  $Export                  = "Export";
  $ERROR                   = "FEHLER";
  $Action                  = "Durchführung"; #"Action"
  // 19990920
  $lang_ALL                = "ALLES";
  // 19990921
  $lang_ADD                = "HINZU";
  $lang_MOD                = "ÄND";
  $lang_DEL                = "LÖSCHE";
  // 19990922
  $No_Record_Found         = "Es wurde kein DB-Name mit diesen Kriterien
                            gefunden.";   
  $lang_back               = "Zurück";
  // 19990924
  $lang_HELP               = "HILFE";
  $Module                  = "Module"; #NICHT ÜBERSETZT
  $Manage_Patient          = "Patientendaten verwalten"; 
#"manage patient"
?>
