<?php
  # file: lang/DE/authenticate.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung von: Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $Error = "FEHLER" ;
  $Return_to_the_login_screen = "Zurück zum Anmeldungs-Menü";
  $Incorrect_name_password= "Der Benutzername oder das Passwort war nicht korrekt. <BR>
   Bitte verständigen Sie Ihren Systemadministrator. Wenn Sie glauben, daß diese Meldung <BR>
   falsch ist notieren Sie die Umstände unter denen sie auftrat und geben Sie die Notiz <BR>     
   Ihrem Systemadministrator zur Anfertigung eines Bugreports." ;
?>
