<?php
  # file: lang/DE/call-in.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Johann KRAUTINGER <j.krau@teleweb.at> 19991004
  # Mod : 19990922

  $Call_In              = "NOCH NICHT ÜBERSETZT";
    # "Call In";
  $Name                 = "Name";
  $Last                 = "Familienname";
  $First                = "Vorname";
  $Middle               = "weitere Vornamen";
  $Contact_Information  = "Kontakt Information";
    #"Contact Information";
  $Home_Phone           = "Telefon privat";
  $Work_Phone           = "Telefon am Arbeitsplatz";
  $Took_Call            = "Ist anzusprechen als";
    #"Took Call";
  $Date_of_Birth        = "Geburtsdatum";
  $Complaint            = "Nachricht";
    #"Message";
  $Facility             = "medizinische Einrichtung/Abteilung";
  $Physician            = "Arzt";
  $Patient_Menu         = "Patienten Übersicht";
  $Call_In_Menu         = "NOCH NICHT ÜBERSETZT";
    # "Call-In Menu";
  $Main_Menu            = "Hauptmenü";
  $NOT_IMPLEMENTED_YET  = "WURDE NOCH NICHT IMPLEMENTIERT";
  $Date_of_Call         = "NOCH NICHT ÜBERSETZT";
    # "Date of Call";
  $Home_Work_Phone      = "Telefon privat/beruflich";
  $Action               = "Ausführen";
  $VIEW                 = "ANZEIGEN";
  $BOOK                 = "NOCH NICHT ÜBERSETZT (BOOK)";
  // 19990920
  $Old                  = "ALT";
  $All                  = "ALLES";
  $Current              = "GEGENWÄRTIG";
?>
