<?php
  # file: lang/DE/cpt.php3.DE.inc
  # desc: CPT codes german (DE) language module
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name                      = "CPT Code - nicht übersetzt";

  $CPT_Code                         = "CPT Code - nicht übersetzt";
  $CPT_Name_Internal                = "CPT Name - nicht übersetzt(Internal)";
  $CPT_Name_External                = "CPT Name - nicht übersetzt(External)";
  $Relative_Value                   = "Relativer Wert";
  #"Relative Value";
  $Example                          = "Beispiel";
  $Type_of_Service                  = "Art der Dienstleistung";
  #"Type of Service";
  $Internal_Name                    = "Interner Name"; 
  #"Internal Name";
?>
