<?php
  # file: lang/DE/cptmod.php3.DE.inc
  # desc: CPT modifier codes german (DE) language module
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweeb.at> 19991004
  
  $record_name                      = "CPT Erneuern";
    #"CPT Modifier";
  $Modifier                         = "Erneuern";
    #"Modifier";
  $Description                      = "Beschreibung";
    #"Description";
?>
