<?php
  # file: lang/DE/db_maintenance.php3.DE.inc
  # desc: database maintenance menu german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $Database_Maintenance            = "Datenbank Verwaltung";
    #"Database Maintenance";
  $CPT_Procedural_Codes            = "CPT/Procedural Codes (nicht übersetzt)";
  $CPT_Procedural_Modifiers        = "CPT/Procedural Modifiers (nicht übersetzt)";      
  $Formulary_Pharmacy_Module       = "Apotheken-Formular-Modul";      
  $ICD_Codes                       = "ICD 9/10 Codes";
  $Insurance_Companies             = "Zuständige Krankenversicherungen";
  #"Insurance Companies";
  $Insurance_Company_Groups        = "Zuständiger Sozialversicherungsverband";
  #"Insurance Company Groups";
  $Physicians                      = "Ärzte";
  $Physician_Degrees               = "akademischer Grad";
  $Physician_Groups                = "Ärztliche Fachrichtung";
  $Physician_Specialties           = "medizinische Sonderfächer";
  $Physician_Statuses              = "Ausbildungsstand des Arztes";
    #"Physician Statuses";
  $Place_of_Service_Facilities     = "Dienststelle / Fachabteilung";
    #"Place of Service / Facilities";
  $Rooms                           = "Zimmer";
    #"Rooms";
  $Scheduling_Locations            = "Behandlungsbereich";
  #"Scheduling Locations";
  $Type_of_Service                 = "Art der Dienstleistung";
    #"Type of Service";
  $Templates_for_Simple_Reports    = "Templates for Simple Reports (nicht übersetzt)";   
  $You_dont_have_access_for_this_menu = "Sie besitzen keine Zugriffsberechtigung zu diesem Menü";   
    #"You don't have access for this menu.";
 ?>
