<?php
  # file: lang/DE/degrees.php3.DE.inc
  # desc: physician degrees german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $Degree_Title                        = "Berufsbezeichnung";
  $Degree_Title_Example                = "Dr.Med. Facharzt für Neurologie usw";
  $Degree_Name                         = "Name der Berufsbezeichnung";  
  $Degree_Name_Example                 = "Dr.Med.,DGKP, etc";   
  $Date_Last_Modified                  = "Datum der letzten Änderung";  
  $Degree                              = "akademischer Grad / Berufsbezeichnung";      
  $Description                         = "Beschreibung";     
$No_degrees_are_currently_in_the_database = "Die Datenbanke enthält derzeit keine Berufsbezeichnungen."; 
?>
