<?php
  # file: lang/DE/facility.php3.DE.inc
  # desc: facility (place of service) german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name = "medizinische Einrichtung/ABTEILUNG";
  $Facility_Name                  = "Name der Einrichtung";
  #"Facility Name";
  $Address_Line_1                 = "Adresse Zeile 1";
  #"Address Line 1";
  $Address_Line_2                 = "Adresse Zeile 2";
  #"Address Line 2";
  $City                           = "Stadt oder Ort";
  $State                          = "Bundesland";
  $Zip                            = "Postleitzahl";
  $Description_Note               = "Beschreibung_Anmerkung";
  #"Description/Note";
  $Default_Physician              = "Arzt (Voreinstellung)";
  #"Default_Physician";
  $Phone_Number                   = "Telefonnummer";
  $Fax_Number                     = "Fax Nummer";
  $Email_Address                  = "Email Addresse";
  $Date_of_Entry                  = "Datum des Behandlungsbeginnes";
  #"Date of Entry";
?>
