<?php
  # file: lang/DE/frmlry.php3.DE.inc
  # desc: formulary/pharmacy german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name = "FORMULAR";

  $Class                          = "Medikamenten Gruppe";
  $Generic_Name                   = "Wirkstoffbezeichnung";
  $Trademark_Name                 = "Handelsname";
  $Indication_1                   = "Indikation 1";
  $Indication_2                   = "Indikation 2";
  $Date_Added                     = "Datum der Eingabe";
  #"Date Added";
?>
