<?php
  # file: lang/DE/index.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at>

  $Username     = "Benutzername";
  $Password     = "Passwort";
  $Enter_the_database = "Datenbank öffnen";
  $Clear        = "Löschen";
  $Language     = "Sprache";
  $Default      = "Voreinstellung";
    // 19990820
  $Facility     = "medizinische Einrichtung";
  $Login        = "Anmeldung";
    // 19990922
  $Resume       = "Resume (nicht übersetzt)";
  $Reset_Resume = "Reset Resume (nicht übersetzt)";
?>
