<?php
  # file: lang/DE/main.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Johann KRAUTINGER <j.krau@teleweb.at>
  # Mod : 19990827

  $Main_menu                 = "Hauptmenü" ;
  $Administration_menu       = "Verwaltungsmenü" ;
  $Billing_functions         = "Verrechnungsfunktionen";
  #"Billing Functions" ;
  $Database_maintenance      = "Datenbank Verwaltung";
  #"Database Maintenance" ;
  $Patient_functions         = "Patientendaten eingeben";
  #"Patient Functions" ;
  $Help_main_menu            = "Hilfe zum Hauptmenü";
  #"Help for the Main Menu" ;
  $Logout_of                 = "Aussteigen von";
  #"Logout of" ;
  $Quickjump                 = "Überspringen";
  #"QUICKJUMP" ;
  $User_level                = "Benutzerverwaltung";
  #"USER LEVEL" ;
  $User_description          = "BENUTZERBESCHREIBUNG";
  #"USER DESCRIPTION" ;
  $Call_in                   = "Call In";
  $Entry                     = "EINSTEIGEN";
  #"Entry";
?>
