<?php
  # file: lang/DE/manage.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Johann KRAUTINGER <j.krau@teleweb.at> 19991004
  # Mods by max k <amk@span.ch>
  # mod: 19990917

  $Attach_to_Guarantor           = "Attach to Guarantor (nicht übersetzt)";
  $Must_select_a_patient         = "Wählen Sie einen Patienten aus";
  #"You must select a patient.";
  $Select_Guarantor_to_Attach_to = "Select Guarantor to Attach to: (nicht übersetzt)";   
  $detach                        = "detach (nicht übersetzt)";
  $Attach                        = "Attach (nicht übersetzt)";
  $Return_to_Patient_Management  = "Zurück zur Patientenverwaltung";
  #"Return to Patient Management";
  $Attaching_Guarantor           = "Attaching Guarantor (nicht übersetzt)";
  
  $Detaching_current_dependants  = "Detaching current dependants (nicht übersetzt)";      
  $lang_done                     = "Fertig.";
  $Manage_Patient                = "Patientendaten eingeben";
  #"Manage Patient";
  $Select_a_patient              = "Patienten auswählen";
  $Patient_Information           = "Patienteninformation";
  $View_Manage                   = "Anzeigen/Durchführen";
  #"View/Manage";
  $Prescriptions                 = "Anordnungen";
  #"Prescriptions";
  $Procedures                    = "Tätigkeiten";
  #"Procedures";
  $Progress_Notes                = "Krankheitsverlauf";
  #"Progress Notes";
  $Reports_and_certificates      = "Befundberichte";
  #"Reports and Certificates";  // 19990813
  $Choose                        = "Auswählen";
  #"Choose";                    // 19990813
  $Show_Dependants               = "Angehörige anzeigen";
  $Show_Guarantor                = "Bürgen anzeigen";
  $Last_Name                     = "Familienname";
  $All                           = "Alles";
  $Select_Another_Patient        = "Einen anderen Patienten auswählen";
    // 19990809
  $Appointments                  = "Termine";
  $Book                          = "Book";
  $Patient                       = "Patient";
  $Show_Today                    = "Heutige Eingaben Anzeigen";
?>
