<?php
  # file: lang/DE/patient.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL, v2
  # Adaptation by max k <amk@span.ch>
  # Translated by Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name                   = "Patient";

  $Dependant                     = "Angehöriger";
  $Patient                       = "Patient";
  $Last_name                     = "Familienname";
  $First_name                    = "Vorname";
  $Middle_name                   = "weitere Vornamen";
  $Date_of_birth                 = "Geburtsdatum";
  $YMD                           = "J-M-T";
  $Gender                        = "Geschlecht";
  $NONE_SELECTED                 = "NICHTS AUSGEWÄHLT";
  $Female                        = "weiblich";
  $Male                          = "männlich";
  $Transgender                   = "transsexuell";
  $Marital_status                = "Familienstand";
  $Unknown                       = "unbekannt";
  $Single                        = "ledig";
  $Married                       = "verheiratet";
  $Divorced                      = "geschieden";
  # The following menu item should be implemented, see next line (mark: Johann K):   
  #$Widowed                       = "verwitwet";
  $Internal_practice_id          = "Patienten-ID-Nummer";
  $Address                       = "Adresse";
  $Line                          = "Zeile";
  $City                          = "Stadt oder Ort";
  $State                         = "Bundesland";
  $Zip_code                      = "Postleitzahl";
  $Country                       = "Staat";
  $Home_phone                    = "TelefonNr privat";
  $Work_phone                    = "TelefonNr beruflich";
  $Fax_number                    = "Fax Nummer";
  $Email_address                 = "Email Addresse";
  $Drivers_license               = "Führerschein";
  $No_state                      = "keiner";
  #"No State";
  $Referring_doctor              = "Referring Doctor (nicht übersetzt)";
  $Primary_care_physician        = "behandelnder Arzt";
  #"Primary Care Physician";
  $Other                         = "Andere";
  $Physician                     = "Arzt";
  $Type_of_billing               = "Art der Verrechnung"; 
  $Monthly_billing_on_acct       = "monatliche Abbuchung vom Konto";
  $Statement_billing             = "statement billing (nicht übersetzt)";
  $Charge_card_billing           = "Bezahlung per Creditkarte";
  $Monthly_budget_amount         = "Monthly Budget Amount (nicht übersetzt)";
  $In_house_doctor               = "Arzt für Allgemeinmedizin";
  $Primary_insurance             = "Krankenversicherung";
  $Secondary_insurance           = "Zusatzversicherung";
  $Tertiary_insurance            = "2. Zusatzversicherung";
  $Discount_percent_if_applic    = "Discount % (if applicable)";
  $Self_insured                  = "Selbstzahler";
  #"Self-insured";
  $Guarantor                     = "Bürge";
  $Next_of_kin_information       = "Nächster Angehöriger";
  #"Next of Kin Information";
  $Employed_presently            = "Employed Presently?";
  $UNKNOWN                       = "UNBEKANNT";
  $Yes                           = "JA";
  $No                            = "NEIN";
  $Adding_patient                = "Patient hinzufügen";
  $ADDING                        = "Hinzufügen";
  $Query_result                  = "Suchergebnis";
  $Query_string                  = "Suchkriterien";
  $Actual_query_result           = "Actual query result";    
  $Error                         = "FEHLER";    
  $Return_to_the                 = "Zurück zum";
  $Patient_menu                  = "Patientenmenü";
  $Main_menu                     = "Hauptmenü";
  $MODIFYING                     = "Verändern";
  $Please_use_the_MODIFY_form    = "Bitte benützen sie das Veränderungsformular um Eingaben zu berichtigen";    
  #"Please use the MODIFY form to MODIFY a code";
  $Result                        = "Ergebnis";
  $Book_an_appointment           = "Termin eingeben";
  #"Book an Appointment";
  $Date                          = "Datum";
  $Of_entry                      = "der Eingabe";
  $Of_last_mod                   = "der letzten Veränderung";
  $Update                        = "Update";
  $Remove_changes                = "Veränderungen verwerfen";
  $Manage                        = "Verwalten";
  $Select_another                = "Andere auswählen";
  $Patients_meeting_criteria     = "Kriterien des Behandlungstermines";
  #"Patients Meeting Criteria";
  $Action                        = "Durchführn";
  $NEWDEP                        = "NEUE ANGEH.";
  $DEPS                          = "ANGEH.";
  $GUA                           = "BÜRGE";
  $MANAGE                        = "VERWALTE";
  $No_patients_found_with_that   = "Kein Patient mit diesen Kriterien gefunden";   
  $PATIENTS                      = "Patienten";
  $In_system                     = "In System (nicht übersetzt)";
  $No_patients                   = "Keine Patienten";
  $Ppl                           = "Patient/en";
  $One                           = "Ein/er";
  $By_name                       = "Mit dem Namen";
  #"By name";
  $Patients_field_search         = "Suche nach dem Patientenfeld";
  #"Patients Field Search"; 
  $Social_security_number        = "Sozialversicherungsnummer";
  $Patient_account_number        = "Kontonummer des Patienten";
  #mark (j.krau@teleweb.at): which account no is meant? the bank or
  # the customers account
  $Show_all                      = "Alles Anzeigen";
  $Contains                      = "Enthält";
  $Find                          = "SUCHEN";
  $Searching_for                 = "SUCHEN NACH";
  $Last_names                    = "Familienname";
  $All_Patients                  = "Alle Patienten";
  $Dependants                    = "Angehörige";
    // 19990823
  $Separated                     = "getrennt";
    // 19990830
  $Call_In_Menu                  = "Call-In Menu";
    // 19990923
  $Current_Patient		 = "gegenwärtige Patienten";
  #"Current Patient"; 
  $CONTAINS			 = "Enthält";        
?>
