<?php
  # file: lang/DE/phygroup.php3.DE.inc
  # desc: physician group german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translated by Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name = "Ärztliche Fachrichtungen";

  $Physician_Group_Name               = "Bezeichnung der Fachrichtung";
  $Default_Facility                   = "Voreinstellung der med. Einrichtung";
  $Group_Name                         = "Fachrichtung";
  #"Group name";
?>
