<?php
  # file: lang/DE/progress_notes.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translated by Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name                  = "Krankheitsverlauf";
  #"Progress Notes";
  #mark by j.krau: means progress notes the progress of the disease and the
  #therapy in latin language "decursus morbis"?
   $Module                      = "Module";
  $ERROR                        = "FEHLER";
  $Must_Specify_A_Patient       = "Sie müssen den Patienten nennen!";
  $Entry                        = "Eintritt";
  #"Entry";
  $Manage_Patient               = "Patientendaten eingeben";
  #"Manage Patient";
  $View_Modify                  = "Anzeigen/Verändern";
  #"View/Modify";
  $Applicable_Date              = "Datum der Verabreichung";
  #"Applicable Date";

    // the actual progress parts (with underlines)
  $Subjective                   = "<U>A</U>bhängig";
  #"<U>S</U>ubjective";
  $Objective                    = "<U>O</U>bjekt";
  #"<U>O</U>bjective";
  $Assessment                   = "<U>P</U>rognose";
  #"<U>A</U>ssessment";
  $Plan                         = "<U>B</U>ehandlungsplan";
  #"<U>P</U>lan";
  $Interval                     = "<U>I</U>ntervalle";
  $Education                    = "<U>A</U>usbildung";
  #"<U>E</U>ducation";
  $Prescription                 = "<U>A</U>nordnung";
  #"p<U>R</U>escription";

  $Add                          = "Neu";
  $Clear                        = "Löschen";
  $Abort_Addition               = "Hinzufügen abbrechen";
  $Adding                       = "Hinzufügen";
  $Done                         = "Fertig";
  $FAILED                       = "Fehlgeschlagen";
  $Must_Call_With_Patient_ID    = "Sie müssen dies Funktion aufrufen mit:";

  #"You must call this function with a ".
                                  "Patient ausgewählt";
  #"patient selected.";
  $Modify                       = "Verändern";
  $Change                       = "Ändern";
  $Restore                      = "Wiederherstellen";
  $Modifying                    = "wird verändert";
  $View                         = "Anzeigen";
  $Menu                         = "Übersicht";
  $Specify_Notes_to_Display     = "Sie müssen den Krankheitsverlauf benennen damit er angezeigt wird";
  #"You must specify the progress notes to ".
  #"be displayed.";
  $Modify_Notes                 = Anmerkungen zu den Veränderungen";
  #"Modify Notes";
  $Patient                      = "Patient";
  $This_Patient_Has_No_Notes    = "Für diesen Patienten wurde kein Krankheitsverlauf angelegt.";
  #"This patient has no notes to date.";
  $Existing                     = "Bestehend";
  #"Existing";
?>
