<?php
  # file: lang/DE/roomequip.php3.DE.inc
  # desc: room equipment german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translated by Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name                       = "Zimmer Inventar";
  $Name_of_Equipment                 = "Bezeichnung des Gerätes";
  $Description                       = "Beschreibung";
  $Equipment                         = "Inventar";
?>
