<?php
  # file: lang/DE/room.php3.DE.inc
  # desc: room (scheduling location) german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translated by Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name = "Zimmer Inventar";

  $Room_Name                      = "Name oder Nr des Zimmers";
  $Location                       = "Lage des Zimmers";
  $Room_Description               = "Zimmerbeschreibung";
  $Default_Physician              = "Voreingestellter Arzt";
  $Surgery_Equipped               = "Ausgestattet für chirurgische Eingriffe?";
  #"Surgery Equipped?";
  $Is_Booking_Enabled             = "Ist die Vergabe möglich?";
  #"Is Booking Enabled?";
  $IP_Address                     = "IP Address (nicht übersetzt)";
  #question (j.krau@teleweb.at): what do you mean with IP Adress?
  #Internet Protocol Adress?? or does it mean a medical special expression??
  $For_Future_Use                 = "Zur zukünftigen Benutzung";
  $For_Scheduling                 = "Zur Planung";
  $Description                    = "Beschreibung";
?>
