<?php
  # file: lang/DE/Rx.php3.DE.inc
  # desc: prescription module german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004
  # lic : GPL

  $record_name = "Anordnung";

  $Must_Have_Patient_For_Prescriptions =
    "Bevor Sie das Anordnungsmodul verwenden <BR>
     müssen Sie die Patientdaten eingeben.";     
  $No_Access_To_This_Patient           =
    "Sie haben keine Zugriffsberichtigung zu diesen Patientendaten.";
  # "You don't have access to this patients' record.";
  $Display                             = "Anzeigen";
  $Patient                             = "Patient";
  $Drug                                = "Medikament";
  $Dosage                              = "Dosierung";
  $Starting_Date                       = "Datum des Behandlungsbeginns";
  $In_Days                             = "in Tagen";
  $Infinite                            = "0 = Behandlungsende";
  #"0 =infinite";   
  $Refills                             = "Anzahl der Applikationen"; 
  #"Refills";
  $Substitution                        = "Substitution";
  $May_Not_Substitute                  = "ist nicht zu substituieren";
# "may not substitute";
  $May_Substitute                      = "ist zu substituieren";
# "May substitute";
  $Manage_Prescriptions                = "Anordnungen durchführen";
?>
