<?php
  # file: lang/DE/simplerep.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translated by Johann KRAUTINGER <j.krau@tleweb.at> 19991004

  $record_name = "Einfache Einstellungen";
  #"Simple Template";

  $Add                     = "NEU";
  $Clear                   = "LÖSCHEN"; 
  $Label                   = "BEZEICHNUNG";
  #"Label";
  $Category                = "KATEGORIE";
  $Text                    = "TEXT";
  $Abandon_Addition        = "Hinzufügen abbrechen";
  $Adding                  = "Hinzufügen";
  $Return_to               = "Zurück zum";
  $Modify                  = "Verändern";
  $Please_use_MODIFY       = "Bitte verwenden Sie das Berichtigungsformular, zur Veränderung von";      
  #"Please use the MODIFY form to MODIFY a";
  $Return_to_the_Main_Menu = "Zurück zum Hauptmenü";
  $Update                  = "Update";
  $Remove_Changes          = "Änderungen entfernen";
  $Abandon_Modification    = "Veränderungen abbrechen";
  #"Abandon Modification";
  $Modifying               = "Wird Verändert";
  $Done                    = "FERTIG";
  $ERROR                   = "FEHLER";
  $Menu                    = "Übersicht";
  $Deleting                = "Wird Gelöscht";
  $Deleted                 = "Gelöscht";
  $Update_Delete_Another   = "Anderes Updaten/Löschen";
  #"Update/Delete Another";
  $Must_Have_Patient_to_Make_Reports = "Bevor Sie einen Bericht beginnen, müssen Sie die Patientendaten eingeben";
  #"You must have a patient to make reports!";
  $Choose_Report_for_Patient = "Wählen Sie den Bericht für:";
  #"Choose Report for Patient";
  $Patient                 = "Patient";
  $Manage_Patient          = "Patientendaten verwalten";
  #"Manage Patient";
  $Action                  = "Durchführen";
?>
