<?php
  # file: lang/DE/specialties.php3.DE.inc
  # desc: specialties german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translated by Johann KRAUTINGER <j.krau@teleweeb.at> 19991004

  $record_name = "Medizinische Sonderfächer";

  $Specialty_Name                        = "Bezeichnung des Sonderfaches";
  $Specialty_Description                 = "Beschreibung des Sonderfaches";
  #"Specialty Description";
  $Name                                  = "Bezeichnung";
  $Description                           = "Beschreibung";
?>
