<?php
  # file: lang/DE/TEMPLATE.DE.inc
  # desc: TEMPLATE for language files
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # Übersetzung: Johann KRAUTINGER <j.krau@teleweb.at> 19991004
  # lic : GPL

  // language variables always have underscores and
  //  are either all caps or start with a capital
  //  letter -- jeff

  // you also must have the $record_name variable for ancillary dbs:
  // $record_name = "Zimmer Inventar";
  // $Username = "Benutzername";
  // $Password = "Passwort";
  // $Enter_the_database = "Daten eingeben";
?>
