<?php
  # file: lang/DE/tos.php3.DE.inc
  # desc: type of service german (DE) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translated by Johann KRAUTINGER <j.krau@teleweb.at> 19991004

  $record_name = "Art der Dienstleistung (ADD)";

  $Type_of_Service_Name        = "Bezeichnung der Dienstleistung";
  #"Type of Service Name";
  $Type_of_Service_Description = "Beschreibung der Dienstleistung";
  #"Type of Service Description";
?>
