<?php
  # file: lang/DE/user.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Johann KRAUTINGER <j.krau@teleweb.at> 19991004
  # mod: 19990917
  # mod: 20000407 by schwindp

  $record_name                  = "Benutzer";

  $phrase[User_name]            = "Benutzername" ;
  $phrase[Password]             = "Passwort" ;
  $phrase[Verify]               = "Bestätigen" ;
  $phrase[Description]          = "Beschreibung" ;
  $phrase[Physician_group]      = "Ärztliche Fachrichtung" ;
  $phrase[User_level]           = "Benutzereigenschaft";
  #"User level" ;
  $phrase[Locked_out]           = "!!! ZUGRIFF VERLOREN !!!" ;
  $phrase[Undefined]            = "NICHT DEFINIERT" ;
  $phrase[Delete_privs]         = "Benutzerrechte Löschen" ;
  $phrase[Superuser]            = "Haupbenutzer/Administrator." ;
  $phrase[Abandon_addition]     = "Diesen Vorgang abbrechen" ; # Just say no ;-)   
  $phrase[Passwords_must_match] = "Passwort richtig eingeben!" ;
  #"Password must match!";
  $phrase[Go_back_to_user_menu] = "Gehen Sie zurück zum Benutzermenü";
  #"Go back to the User Menu" ;
  
  $phrase[Please_use_the_modify_form]
               = "Bitte verwenden Sie das Berichtigungsformular um das zu tun";
  #"Please use the MODIFY form to do this" ;
  $phrase[Result]               = "ERGEBNIS" ;
  $phrase[You_cannot_modify_root]
         = "Sie sind nicht zu Änderungen an \"root\" Einstellungen berechtigt"; 
  #"You cannot modify the SuperUser" ;
  $phrase[You_cannot_delete_root]
                        = "Es ist nicht möglich den Hauptbenutzer zu löschen" ;
  $phrase[Query_result]         = "Abfrage Ergebnis";
  #"Query result" ;
  $phrase[Query_string]         = "Abfrage Kriterien";
  #"Query string" ;
  $phrase[Actual_query_result]  = "aktuelles Abfrageergebnis";
  #"Actual query result" ;
  $phrase[Another]              = "Andere" ;
  $phrase[Maintenance]          = "Verwaltung";
  #"Maintenance" ;
  $phrase[Action]               = "Durchführen" ;
  $phrase[No]                   = "Nein" ;
  $phrase[Found_with_that_criteria] = "mit diesen Kriterien gefunden";
  #"found with that criteria" ;
  $phrase[Try_Again]             = "wiederholen";
  $phrase[Authorized_facilities] = "Berechtigte Einrichtungen";
  #"Authorized Facilities";
  $phrase[Authorized_physicians] = "Berechtigte Ärzte";
  #"Authorized Physicians";
  $phrase[Authorized_phy_groups] = "Berechtigte Fachrichtungen";
  #"Authorized Phy. Groups";
    // 19990909
  $phrase[User_type]            = "Art des Benutzers";
  $phrase[Physician]            = "Arzt";
  $phrase[Miscellaneous]        = "Gemischt";
?>
