<?php
  # file: lang/DE/user.php3.DE.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Johann KRAUTINGER <j.krau@teleweb.at> 19991004
  # mod: 19990917
  # mod: 20000407 by schwindp

  $record_name                         = "Benutzer";

  $User_name                           = "Benutzername" ;
  $Password                            = "Passwort" ;
  $Verify                              = "Bestätigen" ;
  $Description                         = "Beschreibung" ;
  $Physician_group                     = "Ärztliche Fachrichtung" ;
  $User_level                          = "Benutzereigenschaft";
  #"User level" ;
  $Locked_out                          = "!!! ZUGRIFF VERLOREN !!!" ;
  $Undefined                           = "NICHT DEFINIERT" ;
  $Delete_privs                        = "Benutzerrechte Löschen" ;
  $Superuser                           = "Haupbenutzer/Administrator." ;
  $Abandon_addition                    = "Diesen Vorgang abbrechen" ; # Just say no ;-)   
  $Passwords_must_match                = "Passwort richtig eingeben!" ;
  #"Password must match!";
  $Go_back_to_user_menu                = "Gehen Sie zurück zum Benutzermenü";
  #"Go back to the User Menu" ;
  
  $Please_use_the_modify_form          = "Bitte verwenden Sie das Berichtigungsformular um das zu tun";
  #"Please use the MODIFY form to do this" ;
  $Result                              = "ERGEBNIS" ;
  $You_cannot_modify_root              = "Sie sind nicht zu Änderungen an \"root\" Einstellungen berechtigt"; 
  #"You cannot modify the SuperUser" ;
  $You_cannot_delete_root              = "Es ist nicht möglich den Hauptbenutzer zu löschen" ;  
  $Query_result                        = "Abfrage Ergebnis";
  #"Query result" ;
  $Query_string                        = "Abfrage Kriterien";
  #"Query string" ;
  $Actual_query_result                 = "aktuelles Abfrageergebnis";
  #"Actual query result" ;
  $Another                             = "Andere" ;
  $Maintenance                         = "Verwaltung";
  #"Maintenance" ;
  $Action                              = "Durchführen" ;
  $No                                  = "Nein" ;
  $Found_with_that_criteria            = "mit diesen Kriterien gefunden";
  #"found with that criteria" ;
  $Try_Again                           = "wiederholen";
  $Authorized_facilities               = "Berechtigte Einrichtungen";
  #"Authorized Facilities";
  $Authorized_physicians               = "Berechtigte Ärzte";
  #"Authorized Physicians";
  $Authorized_phy_groups               = "Berechtigte Fachrichtungen";
  #"Authorized Phy. Groups";
    // 19990909
  $User_type                           = "Art des Benutzers";
  $Physician                           = "Arzt";
  $Miscellaneous                       = "Gemischt";
?>
