-- tests/security/evidence/seed-verify.sql
--
-- Task 2.6e, fix round 1. Deterministic reduced seed for
--   tests/security/module_smoke.php   (the sweep's functional gate)
-- against the reduced Phase 0.3 scratch database (MariaDB 10.11, schema
-- `freemed`, loaded from data/schema/mysql by scripts/load_schema.sh).
--
-- WHY THIS FILE EXISTS
-- The recorded seed state behind tests/security/evidence/module-smoke-before.json
-- and module-smoke-after.json was not reconstructible from anything in the tree:
-- it was applied ad hoc, the `payrec` row was later deleted by a foreign-key
-- CASCADE and restored by hand, and the AUTO_INCREMENT counters (which decide the
-- id the payrec companion row gets) were left wherever the run had put them. The
-- smoke DOES observe row counts: `PaymentModule` reports
--   "SKIP: GetList() returned 1 rows, none with an id"
-- for the single `payrec` row, so a re-seed that produces 0 rows or 2 rows moves
-- an entry and manufactures a spurious delta against the committed baseline.
-- This file pins the seed side of that environment; seed-fingerprint.md records
-- the counts and ids it must produce.
--
-- WHAT THIS FILE DOES **NOT** CONTAIN
-- * The 133 registry rows derived from lib/org/freemedsoftware/module/*.php.
--   They are generated by the harness itself, deterministically in every column
--   the smoke reads: module_uid = md5(module_class) formatted as a UUID, and
--   module_class / module_path are derived from the file name. Only module_stamp
--   (= filemtime) varies between checkouts, and no smoke outcome reads it:
--       cd <served copy> && php tests/security/module_smoke.php --register
--   Run that ONCE on a fresh database, then this file. 133 register rows + the 2
--   registry rows below = the 135 rows recorded in seed-fingerprint.md.
-- * The 2 pre-existing `user` rows (ids 1 and 2). They belong to the
--   deployment seed, not to this harness seed; the fingerprint records them and
--   the smoke only needs *a* patient id, not a user id.
-- * Any patient/procrec/vitals row. Those tables are EMPTY in the recorded
--   baseline (0 rows) and must stay empty: seeding vitals is what the 2.6e live
--   probes did, and the companion `patient` row they needed is what deleted the
--   payrec row through payrec_ibfk_1 (see sweep-notes.md section 7).
--
-- IDEMPOTENCE
-- Every INSERT is ON DUPLICATE KEY UPDATE, so re-running the file on an already
-- seeded database is a no-op in row count and in ids. It never DELETEs anything.
--
-- APPLY
--   docker exec -i freemed-verify-db mysql -ufreemed -pfreemed freemed < seed-verify.sql
--   (or, for the stack in verify-env.md: mysql -h127.0.0.1 -P33306 -ufreemed -pfreemed freemed)
--
-- EXPECTED RESULT (asserted at the end of this file, recorded in seed-fingerprint.md)
--   entemplate 1 row, id 1  |  payrec 1 row, id 3  |  patient_emr 1 row, id 5
--   modules 135 rows, 134 distinct module_class

-- 1. entemplate (Task 2.3 seed: the EncounterNotesTemplate listing table).
--    Explicit id 1: the smoke's `EncounterNotesTemplate` entries are `OK`
--    because this row exists and carries id 1.
INSERT INTO entemplate (id, pnotestname, pnotesttype, pnotestuser)
VALUES (1, 'Demo Progress Template', 'Progress Note', 0)
ON DUPLICATE KEY UPDATE
  pnotestname = VALUES(pnotestname),
  pnotesttype = VALUES(pnotesttype);

-- 2. The two `modules` registry rows the smoke needs that --register does NOT
--    produce. `modules` has no AUTO_INCREMENT column - the explicit id IS the
--    primary key, `module_uid` (char(36)).
--    (a) the DemoPayments row: module_path='/tmp' deliberately, because it is the
--        smoke's proof that a registry row which does not resolve to a file is
--        reported EXC rather than silently skipped. module_uid is the
--        hand-written all-ones uuid, NOT md5('DemoPayments').
INSERT INTO modules
  (module_uid, module_name, module_class, module_table, module_version,
   module_version_installed, module_category, module_path, module_stamp,
   module_associations, module_hidden)
VALUES
  ('11111111-1111-1111-1111-111111111111', 'Demo Payments Module', 'DemoPayments',
   'demo', '1.0', 0, 'test', '/tmp', 0, 'billing', 0)
ON DUPLICATE KEY UPDATE
  module_path = VALUES(module_path),
  module_table = VALUES(module_table);
--    (b) the entemplate-backed EncounterNotesTemplate row. This is a SECOND
--        registry row for the same module_class (the --register row is the
--        md5-derived 0b51a566-...), which is why the baseline carries both
--        `EncounterNotesTemplate` and `EncounterNotesTemplate#2` - the harness
--        keys a duplicate class as `<class>#2`. Dropping this row silently
--        changes the entry count from 136 to 135.
INSERT INTO modules
  (module_uid, module_name, module_class, module_table, module_version,
   module_version_installed, module_category, module_path, module_stamp,
   module_associations, module_hidden)
VALUES
  ('709a8d12-3799-46a7-8648-567b904349f2', 'Encounter Notes Template',
   'EncounterNotesTemplate', 'entemplate', '0.1', 0, 'encounter',
   'lib/org/freemedsoftware/module/EncounterNotesTemplate.class.php', 0,
   'encounter', 0)
ON DUPLICATE KEY UPDATE
  module_table = VALUES(module_table),
  module_path = VALUES(module_path);

-- 3. payrec (Task 2.5 seed) and its `patient_emr` companion.
--
--    Explicit id 3 for payrec. The FK checks are off because the recorded
--    baseline has NO patient row (0 rows) while both payrec FKs point at
--    `patient` and `procrec` - which is exactly the state the recorded row was
--    created in, and the state later tasks must not "clean up" by seeding a
--    patient.
--
--    EXPLICIT id 5 for patient_emr. payrec_Insert (AFTER INSERT) writes that
--    companion row itself -
--      INSERT INTO patient_emr (module, patient, oid, stamp, summary, locked,
--                               user, status)
--        VALUES ('payrec', NEW.payrecpatient, NEW.id, NOW(),
--                NEW.payrecdescrip, NEW.payreclock, NEW.user, NEW.active)
--    - so the row cannot ALSO be hand-inserted: that would leave two companion
--    rows, and a DELETE of the trigger's row afterwards is exactly the kind of
--    destructive step this file exists to remove. The id is pinned instead, with
--    the UPDATE below: on a fresh reduced seed the trigger's row lands on id 1
--    and is renumbered to the recorded 5; on an already-seeded database it is
--    already id 5 and the statement is a no-op (its WHERE clause excludes it).
--    Nothing references patient_emr.id by foreign key (verified: no row in
--    information_schema.KEY_COLUMN_USAGE has REFERENCED_TABLE_NAME='patient_emr'),
--    and on a fresh reduced seed no other table has rows at all.
--    `locked` comes out 1: NEW.payreclock is an ENUM('unlocked','locked') and
--    MariaDB converts the enum to its 1-based index on assignment to the tinyint
--    column, so 'unlocked' -> 1 as well. `stamp` is NOW() by construction and is
--    not comparable between runs.
--
--    NOTE: this file deliberately does not touch AUTO_INCREMENT counters. The
--    counters at the time the artifacts were made are not reconstructible (the
--    companion row below was written by a trigger, and later probe runs consumed
--    further ids), so nothing here may depend on them.
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO payrec
  (id, payrecpatient, payrecproc, payreccat, payrecsource, payrecamt,
   payreclink, payrecdt, payreclock, user, active)
VALUES
  (3, 1, 5, 0, 0, 150.25, 0, '2026-01-15', 'unlocked', 1, 'active')
ON DUPLICATE KEY UPDATE
  payrecpatient = VALUES(payrecpatient),
  payrecproc    = VALUES(payrecproc),
  payreccat     = VALUES(payreccat),
  payrecsource  = VALUES(payrecsource),
  payrecamt     = VALUES(payrecamt),
  payreclink    = VALUES(payreclink),
  payrecdt      = VALUES(payrecdt),
  payreclock    = VALUES(payreclock),
  user          = VALUES(user),
  active        = VALUES(active);

-- EXPLICIT id 5 for the trigger-written patient_emr companion row (see above).
-- Fresh reduced seed: renumbers the row the trigger just wrote. Already-seeded
-- database: no-op, because the WHERE clause excludes the row that is already 5.
UPDATE patient_emr SET id = 5
  WHERE module = 'payrec' AND oid = 3 AND id <> 5;
SET FOREIGN_KEY_CHECKS = 1;

-- 4. The count/id assertion. Compare against seed-fingerprint.md; a difference
--    here is seed drift, and the two committed smoke artifacts must NOT be
--    re-baselined to absorb it without saying so (see sweep-notes.md section 9).
SELECT 'entemplate' AS tbl, COUNT(*) AS n, GROUP_CONCAT(id ORDER BY id) AS ids FROM entemplate
UNION ALL SELECT 'payrec', COUNT(*), GROUP_CONCAT(id ORDER BY id) FROM payrec
UNION ALL SELECT 'patient_emr', COUNT(*), GROUP_CONCAT(id ORDER BY id) FROM patient_emr
UNION ALL SELECT 'modules', COUNT(*), CONCAT(COUNT(DISTINCT module_class), ' distinct module_class') FROM modules
UNION ALL SELECT 'patient', COUNT(*), GROUP_CONCAT(id ORDER BY id) FROM patient
UNION ALL SELECT 'procrec', COUNT(*), GROUP_CONCAT(id ORDER BY id) FROM procrec
UNION ALL SELECT 'vitals', COUNT(*), GROUP_CONCAT(id ORDER BY id) FROM vitals
UNION ALL SELECT 'user', COUNT(*), GROUP_CONCAT(id ORDER BY id) FROM user;
