#!/bin/sh
# $Id$
#
# Authors:
#      Jeff Buchbinder <jeff@freemedsoftware.org>
#
# FreeMED Electronic Medical Record and Practice Management System
# Copyright (C) 1999-2009 FreeMED Software Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


APPDIR=`dirname $0`;
MODE="OBFUS"; # MODE=(PRETTY|OBFUS|DETAILED)
CP="$APPDIR/src:$APPDIR/bin:/opt/gwt/gwt-user.jar:/opt/gwt/gwt-dev-linux.jar:/usr/lib/gwt/gwt-user.jar:/usr/lib/gwt/gwt-dev-linux.jar"
for JAR in lib/*.jar; do
	CP="${CP}:$APPDIR/lib/$(basename "$JAR")"
done
echo "Compiling GWT portion of application ... "
java -Xmx1536M -Xms128M -cp "$CP" com.google.gwt.dev.GWTCompiler -style ${MODE} -out "$APPDIR/www" "$@" org.freemedsoftware.gwt.FreemedInterface;

