<?php
  # file: lang/IT/admin.php3.IT.inc
  # code: Stefano Fava <ste@sirius.ccii.unipi.it>
  # e pure mak k <amk@span.ch>
  # lic : GPL
  # ver : 19990921

  $No_admin_menu_access 	= "Non hai accesso al menu di amministrazione" ; 
  $Icd_code_type 		= "Codice ICD" ;
  $Graphics_enhanced 		= "Modalita' grafica" ;
  $Disabled 			= "Disattivo" ;
  $Enabled 			= "Attivo" ;
  $Scheduling_start_time 	= "Avvio procedura" ;
  $Scheduling_end_time 		= "Fine procedura" ;
  $Configure 			= "Configurare" ;
  $Reset 			= "Reinizializzare" ;
  $Configuration_complete 	= "Configurazione completa" ;
  $Return_adm_menu 		= "Ritorno al Menu di Amministrazione" ;
  $Reinitialize_database 	= "Reinizializza il database" ;
  $Are_you_sure 		= "Sei SICURO di volere" ;
  $Irreversable_process 	= "Questo e' un processo irreversibile!" ;
  $First_initialization 	= "Clicca qui' se e' una prima inizializzazione" ;
  $Continue 			= "Continua" ;
  $Cancel 			= "Annulla" ;
  $Erasing_old_db 		= "Cancella il vecchio database" ;
  $Error_accessing_sql 		= "Errore nell' accesso al database SQL " ;
  $Done 			= "Fatto" ;
  $Creating_new_db 		= "Creazione di un nuovo database" ;
  $Creating_tables 		= "Creazione delle tabelle" ;
  $Administration_menu 		= "Menu di Amministrazione" ;
  $Update_config 		= "Aggiorna la configurazione" ;
  $User_maintenance 		= "Gestione Utenti" ;
  $Return_main_menu 		= "Ritorna al Menu Principale" ;
  $DEFAULT 			= "DEFAULT";
  $SELECTED 			= "SELEZIONATO";
  $Update_Configuration 	= "Aggiorna la configurazione";
?>
