<?php
  # file: lang/IT/API.IT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Stefano Fava <ste@sirius.ccii.unipi.it>
  # E pure anche Max Klohn <amk@span.ch>
  # Ver : 19990921

  $DEBUG_IS_ON = "DEBUG IS ON";
  $Return_to_the_Main_Menu = "Ritorna al Menu Princopale";
  $Return_to_Previous_Menu = "Ritorna al Menu Pecedente";
  $lang_main = "principale"; // alt tag for main menu button
  $lang_exit = "esci"; // alt tag for logout button
  $RETURN_TO_MENU          = "RITORNA AL MENU";
  $ADD                     = "AGGIUNGI";
  $NONE_SELECTED           = "NESSUNO SELEZIONATO";
  $SELECTED                = "SELEZIONATO";
  $lang_coded_by           = "codificato da"; 
  $NO_RESULT_OF_QUERY      = "NESSUN RISULTATO DI QUERY";
  $Entered_incorrect_NamePasswd =
    "Hai inserito un nome di utente o una password errati";
  $Possible_Cookies_Have_Expired =
    "Forse  i tuoi cookies sono scaduti. Per favore <BR>
     riprova a entrare , o chiedi al tuo amministratore di sistema<BR> di aumentare la vita del cookie.";
  $Login_Screen            = "Login Screen";
    // 19990824
  $Add                     = "Aggiungere";
  $Adding                  = "Aggiungendo";
  $Clear                   = "Togliere";
    // 19990917
  $Return_to               = "Ritorna a";
  $Main_Menu               = "Menu principale";
  $Modify                  = "Modifica";
  $Modifying               = "Modificando";
  $Done                    = "Finito";
  $Menu                    = "Menu";
  $Deleting                = "Togliendo";
  $Update_Delete_Another   = "Modifica/Toglie un altro";
  $Deleted                 = "Tolto";
  $Abandon_Addition        = "Abandona l'aggiunzione";
  $Abandon_Modification    = "Abandona la modificazione";
  $Update                  = "Attualiza";
  $Remove_Changes          = "Rimovi modificazioni";
  $Exporting_data          = "Esportando informazioni";
  $Export                  = "Esporta";
  $ERROR                   = "ERRORE";
  $Action                  = "Azione";
  // 19990920
  $lang_ALL                = "TUTTO";
?>
