<?php
  # file: lang/IT/call-in.php3.IT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by 
  # Mod : 19990830

$Call_In              = "Chiamate";
$Add                  = "Nuova";
$Adding               = "Adding";
$Clear                = "Togliere";
$Name                 = "Nomine";
$Last                 = "Patronimo";
$First                = "Primo";
$Middle               = "Suppl.";
$Contact_Information  = "Informazioni Contatto";
$Home_Phone           = "Home Phone";
$Work_Phone           = "Work Phone";
$Took_Call            = "Took Call";
$Date_of_Birth        = "Date of Birth";
$Complaint            = "Messaggio";
$Facility             = "Locale";
$Physician            = "Medico";
$Patient_Menu         = "Menu Pazienti";
$Call_In_Menu         = "Menu Chiamate";
$Main_Menu            = "Menu Principale";
$NOT_IMPLEMENTED_YET  = "NON E ANCORA PRESTO";
$Date_of_Call         = "Bisogna traduzione";
$Home_Work_Phone      = "Si chercano voluntari";
$Action               = "Action";
$VIEW                 = "VEDE";
$BOOK                 = "APPUNT.";



?>
