<?php
  # file: lang/IT/index.php3.IT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Stefano Fava <ste@sirius.ccii.unipi.it>
  # mod: 19990822

  $Username              = "Username";
  $Password              = "Password";
  $Enter_the_database    = "Accesso al database";
  $Clear                 = "Annulla";
  $Language              = "Lingua";
  $Default               = "Per omissione";
  $Facility              = "Locale";  //da vere -mk-
  $Login                 = "Login";   //anche questo

?>
