<?php
  # file: lang/IT/main.php3.IT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Stefano Fava <ste@sirius.ccii.unipi.it>
  # and Max Klohn <amk@span.ch>
  # Mod: 19990827

  $Main_menu             = "Menu Principale" ;
  $Administration_menu   = "Menu di Amministrazione" ;
  $Billing_functions     = "Funzioni di Fatturazione" ;
  $Database_maintenance  = "Manutenzione Database" ;
  $Patient_functions     = "Funzioni Pazienti" ;
  $Help_main_menu        = "Aiuto per il Menu Principale" ;
  $Logout_of             = "Uscita di" ;
  $Quickjump             = "ANDARE A" ;
  $User_level            = "LIVELLO UTENTE" ;
  $User_description      = "DESCRIZIONE UTENTE" ;
  $Call_in               = "Messaggi Telefonici";
  $Entry                 = "Nuovo";
  $Menu                  = "Menu"; 
?>
