<?php
  # file: lang/IT/manage.php3.IT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Stefano Fava <ste@sirius.ccii.unipi.it>
  # mod: 19990813

  $Attach_to_Guarantor           = "Collega a un Garante";
  $Must_select_a_patient         = "Devi selezionare un Paziente.";
  $Select_Guarantor_to_Attach_to = "Seleziona un Garante a cui collegarlo:";
  $detach                        = "Scollega";
  $Attach                        = "Collega";
  $Return_to_Patient_Management  = "Ritorna alla Gestione Pazienti";
  $Attaching_Guarantor           = "Sto collegando un  Garante";
  $Detaching_current_dependants  = "Scollega i dipendenti correnti";
  $lang_done                     = "fatto.";
  $Manage_Patient                = "Modifica paziente";
  $Select_a_patient              = "Seleziona un paziente";
  $Patient_Information           = "Informazioni sul paziente";
  $Modify                        = "Modifica";
  $Add                           = "Aggiungi";
  $View_Manage                   = "Vedi/Modifica";
  $Prescriptions                 = "Prescrizioni";
  $Procedures                    = "Terapie";
  $Progress_Notes                = "Note di Progresso";
  $Reports_and_certificates      = "Bisogna traduzione";             //19990813
  $Choose                        = "Bisogna traduzione anche cui";   //19990813   
  $Show_Dependants               = "Mostra Dipendenti";
  $Show_Guarantor                = "Mostra Garante";
  $Attach_to_Guarantor           = "Collega a un  Garante";
  $Last_Name                     = "Cognome";
  $All                           = "Tutti";
  $Select_Another_Patient        = "Seleziona un altro paziente";
?>
