<?php
  # file: lang/PT/admin.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>
  # ver : 19990921

  $No_admin_menu_access 	= "Você nâo tem acesso ao menu de administração" ; 
  $Icd_code_type 		= "Códigos CIE" ;
  $Graphics_enhanced 		= "Gráficos" ;
  $Disabled 			= "inativos" ;
  $Enabled 			= "ativos" ;
  $Scheduling_start_time 	= "Inicio do agendamento" ;
  $Scheduling_end_time 		= "Fim do agendamento" ;
  $Configure 			= "Configurar" ;
  $Reset 			= "Reinicializar" ;
  $Configuration_complete 	= "Fim da configuração" ;
  $Return_adm_menu 		= "Voltar par o menu de administração" ;
  $Reinitialize_database 	= "Reinicializar a base de dados" ;
  $Are_you_sure 		= "Você tem certeza?" ;
  $Irreversable_process 	= "É um processo irreversivel!" ;
  $First_initialization 	= "Clique aqui se for a primera inicialização" ;
  $Continue 			= "Continuar" ;
  $Cancel 			= "Cancelar" ;
  $Erasing_old_db 		= "Retornar dados antigos" ;
  $Error_accessing_sql 		= "Erro durante o acceso a  base de dados SQL" ;
  $Done 			= "Concluído" ;
  $Creating_new_db 		= "Criar uma nova base de dados" ;
  $Creating_tables 		= "Criar tabelas" ;
  $Administration_menu 		= "Menu de Administração" ;
  $Update_config 		= "Atualizar configuração" ;
  $User_maintenance 		= "Configurar  usuarios" ;
  $Return_main_menu 		= "Voltar par o menu principal" ;
  $DEFAULT 			= "DEFAULT" ;
  $SELECTED 			= "SELECTED" ;
  $Update_Configuration 	= "Atualizar configuração";
?>
