<?php
  # file: lang/PT/API.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br> 
  # and Max Klohn <amk@span.ch>
  # ver : 19990921

  $DEBUG_IS_ON = "DEBUG ATIVO";
  $Return_to_the_Main_Menu = "Voltar para o  menu principal";
  $Return_to_Previous_Menu = "Voltar para o  menu anterior";
  $lang_main = "principal"; // alt tag for main menu button
  $lang_exit = "sair"; // alt tag for logout button
  $RETURN_TO_MENU          = "VOLTAR PARA O MENU";
  $ADD                     = "ADICIONAR";
  $NONE_SELECTED           = "SEM SELEÇÃO";
  $SELECTED                = "SELECIONADO";
  $lang_coded_by           = "programado por"; 
  $NO_RESULT_OF_QUERY      = "SEM RESULTADO PARA A SELEÇÃO";
  $Entered_incorrect_NamePasswd =
    "Nome do usuário ou senha incorretos";
  $Possible_Cookies_Have_Expired =
    "Possivelmente seus cookies expiraram. Por favor<BR>
     refaça a autenticação, ou  peça para o seu administrador de sistemas<BR>
     para aumentar o tempo de duração dos cookies.";
  $Login_Screen            = "Autenticação";
    // 19990824
  $Add                     = "Adicionar";
  $Adding                  = "Adicionando";
  $Clear                   = "Limpiar";
    // 19990917
  $Return_to               = "Retornar para";
  $Main_Menu               = "Menu Principal";
  $Modify                  = "Modifica";
  $Modifying               = "Modificando";
  $Done                    = "Concluído";
  $Menu                    = "Menu";
  $Deleting                = "Excluíndo";
  $Update_Delete_Another   = "Modificar/Excluir Outro";
  $Deleted                 = "Excluído";
  $Abandon_Addition        = "Abandonar Adicion";
  $Abandon_Modification    = "Abandonar Modificacion";
  $Update                  = "Atualizar";
  $Remove_Changes          = "Excluindo modificações";
  $Exporting_data          = "Exportando informações";
  $Export                  = "Exporta";
  $ERROR                   = "ERRO";
  $Action                  = "Accion";
  // 19990920
  $lang_ALL                = "TODO";
?>
