<?php
  # file: lang/PT/call-in.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>
  # Mod : 19990830

$Call_In              = "Chamada";
$Add                  = "Adicionar";
$Adding               = "Adicionando";
$Clear                = "Limpar";
$Name                 = "Nome";
$Last                 = "Sobrenome";
$First                = "Nome";
$Middle               = "Segundo nome";
$Contact_Information  = "Informações de Contato";
$Home_Phone           = "Fone Residencial";
$Work_Phone           = "Fone Comercial";
$Took_Call            = "Recibo da chamada";
$Date_of_Birth        = "Data de Nascimento";
$Complaint            = "Mensagem";
$Facility             = "Local";
$Physician            = "Médico";
$Patient_Menu         = "Menu Pacientes";
$Call_In_Menu         = "Menu Chamadas";
$Main_Menu            = "Menu Principal";
$NOT_IMPLEMENTED_YET  = "NÃO IMPLEMENTADO AINDA";
$Date_of_Call         = "Data da Chamada";
$Home_Work_Phone      = "Fone Residencial/Comercial";
$Action               = "Ação";
$VIEW                 = "VER";
$BOOK                 = "AGENDA";



?>
