<?php
  # file: lang/PT/main.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>

  $Main_menu                 = "Menu Principal" ;
  $Administration_menu       = "Menu de Administração" ;
  $Billing_functions         = "Faturas" ;
  $Database_maintenance      = "Configuração da base de dados" ;
  $Patient_functions         = "Pacientes" ;
  $Help_main_menu            = "Ajuda para o menu principal" ;
  $Logout_of                 = "Sair de" ;
  $Quickjump                 = "IR PARA" ;
  $User_level                = "NIVEL DO USUARIO" ;
  $User_description          = "DESCRIÇÂO" ;
  $Call_in                   = "Chamadas";
  $Entry                     = "Nona";
  $Menu                      = "Menu"; 
  
?>
