<?php
  # file: lang/PT/manage.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>


  $Attach_to_Guarantor           = "Anexar Fiador";
  $Must_select_a_patient         = "Você deve selecionar um paciente.";
  $Select_Guarantor_to_Attach_to = "Selecionar Fiador para anexação:";
  $detach                        = "desanexar";
  $Attach                        = "anexar";
  $Return_to_Patient_Management  = "Retornar para a administração de Pacientes";
  $Attaching_Guarantor           = "Anexando Fiador";
  $Detaching_current_dependants  = "Desligando os atuais dependentes";
  $lang_done                     = "terminado.";
  $Manage_Patient                = "Administrar o Paciente";
  $Select_a_patient              = "Selecionar um paciente";
  $Patient_Information           = "Informação sobre o paciente";
  $Modify                        = "Modificar";
  $Add                           = "Adicionar";
  $View_Manage                   = "Ver/Administrar";
  $Prescriptions                 = "Receitas";
  $Procedures                    = "Processos";
  $Progress_Notes                = "Apontes Clinicos";
  $Reports_and_certificates      = "Informes e certificados";  //19990813
  $Choose                        = "Escolher";                   //19990813
  $Show_Dependants               = "Ver os Dependentes";
  $Show_Guarantor                = "Exibir Fiador";
  $Last_Name                     = "Sobrenome";
  $All                           = "Todos";
  $Select_Another_Patient        = "Selecionar outro Paciente";// 19990809
  $Appointments                  = "Apontamentos";
  $Book                          = "Prontuário";
  $Patient                       = "Paciente";

?>
