<?php
  # file: lang/PT/user.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>

  $record_name                             = "Usuário";  

  // add/mod/etc are in API.inc
  //$Add                                     = "Adicionar";
  //$Adding                                  = "Adicionando";
  //$Modify                                  = "Modificar" ;
  //$Modifying                               = "Modificando" ;
  $phrase[User_name]               = "Usuário" ;
  $phrase[Password]                = "Senha" ;
  $phrase[Verify]                  = "verificar" ;
  $phrase[Description]             = "Descrição" ;
  $phrase[Physician_group]         = "Grupo de Médicos" ;
  $phrase[User_level]              = "Nível de acceso" ;
  $phrase[Locked_out]              = "!!! Excluido !!!" ;
  $phrase[Undefined]               = "INDEFINIDO" ;
  $phrase[Delete_privs]            = "Pode Excluir" ;
  $phrase[Superuser]               = "SuperUsuario/Admin." ;
  $phrase[Update]                  = "Atualizar" ;
  $phrase[Remove_changes]          = "Excluir mudanças" ;
  $phrase[Abandon_addition]        = "Abandonar a operação" ; # Just say no ;-)
  $phrase[Passwords_must_match]    = "Senhas não conferem!" ;
  $phrase[Done]                    = "Terminado" ;
  $phrase[Go_back_to_user_menu]    = "Retornar ao menu de usuários" ;
  $phrase[Please_use_the_modify_form]  
                       = "Por favor use o formulário MODIFICAR para mudanças" ;
  $phrase[Return_to_main_menu]     = "Retornar para o menu principal" ;
  $phrase[Result]                  = "RESULTADO" ;
  $phrase[Error]                   = "ERRO" ;
  $phrase[You_cannot_modify_root]  = "Você não pode modificar o superusuario" ;
  $phrase[You_cannot_delete_root]  = "Você não pode remover o superusuario" ;
  $phrase[Query_result]            = "Resultado da pesquisa" ;
  $phrase[Query_string]            = "variável da pesquisa" ;
  $phrase[Actual_query_result]     = "Resultado atual da pesquisa" ;
  $phrase[Deleting]                = "Excluindo" ;
  $phrase[Delete]                  = "Excluir" ;
  $phrase[Another]                 = "Outro" ;
  $phrase[Maintenance]             = "Manutenção" ;
  $phrase[Action]                  = "Ação" ;
  $phrase[No]                      = "Nada" ;
  $phrase[Found_with_that_criteria]= "encontrado com estes critérios" ;
  $phrase[Try_Again]               = "Tentar novamente";     //19990813
  $phrase[Authorized_facilities]   = "Locais autorizados";
  $phrase[Authorized_physicians]   = "Médicos autorizados";
  $phrase[Authorized_phy_groups]   = "Grupos de médicos autorizados"; 

?>
