# $Id$
# $Author$

THISDIR=doc

all:
	# Nothing

install:
	mkdir -p $(INSTDIR)/$(THISDIR)
	cp -vf [A-B]* {CH,Ch}* [D-Z]* $(INSTDIR)/$(THISDIR)
	mkdir -p $(DESTDIR)/etc/apache/conf.d
	cp -vf freemed.apache.conf $(DESTDIR)/etc/apache/conf.d/freemed.conf

clean:
	# Nothing

dist-clean:
	# Nothing
	
