<?php
  # file: lang/ES/admin.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Ver: 19991007

  $No_admin_menu_access 	= "No tiene acceso al menu de administracion" ; 
  $Icd_code_type 		= "Codigos CIE" ;
  $Graphics_enhanced 		= "Graficos" ;
  $Disabled 			= "inactivos" ;
  $Enabled 			= "activos" ;
  $Scheduling_start_time 	= "Principio de las citas" ;
  $Scheduling_end_time 		= "Fin de las citas" ;
  $Configure 			= "Configurar" ;
  $Reset 			= "Reinicializar" ;
  $Configuration_complete 	= "Fin de la configuracion" ;
  $Return_adm_menu 		= "Volver al menu de administracion" ;
  $Reinitialize_database 	= "Reinicializar la base de datos" ;
  $Are_you_sure 		= "Esta seguro de querer" ;
  $Irreversable_process 	= "Es un proceso irreversible!" ;
  $First_initialization 	= "Clic aqui si es la primera inicializacion" ;
  $Continue 			= "Proseguir" ;
  $Cancel 			= "Anular" ;
  $Erasing_old_db 		= "Se borran los antiguos datos" ;
  $Error_accessing_sql 		= "Error durante el acceso a la base de datos SQL" ;
  $Done 			= "Terminado" ;
  $Creating_new_db 		= "Creacion de una nueva base de datos" ;
  $Creating_tables 		= "Creacion de tablas" ;
  $Administration_menu 		= "Menu de Administración" ;
  $Update_config 		= "Poner al dia la configuración" ;
  $User_maintenance 		= "Configurar los usuarios" ;
  $Return_main_menu 		= "Volver al menu principal" ;
  $DEFAULT 			= "POR OMISION" ;
  $SELECTED 			= "SELECCIONADO" ;
  $Update_Configuration 	= "Poner al día la configuración";
  $Calendar_overbooking         = "Superposición de citas en el Calendario";

?>
