<?php
  # file: lang/ES/API.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch> 
  # Ver : 19991102

  $DEBUG_IS_ON             = "BUSCABUGS ACTIVO";
  $Return_to_the_Main_Menu = "Volver al menu principal";
  $Return_to_Previous_Menu = "Volver al menu anterior";
  $lang_main               = "principal"; // alt tag for main menu button
  $lang_exit               = "salir"; // alt tag for logout button
  $RETURN_TO_MENU          = "VOLVER AL MENU";
  $ADD                     = "AGREGAR";
  $NONE_SELECTED           = "NINGUNO SELECCIONADO";
  $SELECTED                = "SELECTED"; // must NOT be translated
  $lang_coded_by           = "programado por"; 
  $NO_RESULT_OF_QUERY      = "NINGUN RESULTADO A LA INTERROGACION";
  $Entered_incorrect_NamePasswd =
    "Ud. ha introducido un nombre o clave errados";
  $Possible_Cookies_Have_Expired =
    "Es igualmente posible que sus cookies hayan expirado. Por favor<BR>
     autentifiquese de nuevo, o pidale a su administrador de sistema<BR>
     de aumentar el tiempo para las cookies.";
  $Login_Screen            = "Autentificacion";
    // 19990824
  $Add                     = "Agregar";
  $Adding                  = "Agregando";
  $Clear                   = "Borrar";
    // 19990917
  $Return_to               = "Volver a";
  $Main_Menu               = "Menu principal";
  $Modify                  = "Modificar";
  $Modifying               = "Modificando";
  $Done                    = "Terminado";
  $Menu                    = "Menu";
  $Deleting                = "Suprimiendo";
  $Update_Delete_Another   = "Modificar/suprimir otro";
  $Deleted                 = "Suprimido";
  $Abandon_Addition        = "Abandonar la adición";
  $Abandon_Modification    = "Abandonar la modificación";
  $Update                  = "Poner al día";
  $Remove_Changes          = "Borrar las modificaciones";
  $Exporting_data          = "Exportando datos";
  $Export                  = "Exportar";
  $ERROR                   = "ERROR";
  $Action                  = "Acción";
  // 19990920
  $lang_ALL                = "TODO";
  // 19990921
  $lang_ADD                = "AGR";
  $lang_MOD                = "MOD";
  $lang_DEL                = "SUP";
  // 19990922
  $No_Record_Found         = "Ningún $record_name corresponde a aquéllos criterios.";
  $lang_back               = "volver";
  // 19990924
  $lang_HELP               = "AYUDA";
  $Module                  = "Módulo";
  $Manage_Patient          = "Gestion de Paciente";
  // 19991005
  $Week_Of                 = "Semana de";
  // 19991013
  $Export_Database         = "Exportar los datos";
?>
