<?php
  # file: lang/ES/authenticate.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>

  $Error = "ERROR" ;
  $Return_to_the_login_screen = "Volver al formulario de Autentificacion" ;
  $Incorrect_name_password= "Ud. ha introducido un nombre o una clave erroneos. <BR>
   En caso en que este mensaje siguiera apareciendo, notifique a su <BR>
   administrador de sistema. Favor tomar nota de las circunstancias en las que<BR>
   este mensaje aparecio, y comuniquelas igualmente a su adminisrador de<BR>
   sistema. seran utiles para senalar un bug." ;

?>
