<?php
  # file: lang/FR/book_appointment.php3.FR.inc
  # desc: book appointment french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991008

  $Add_Appointment                     = "Agregar Cita";
  $lang_day                            = "día";
  $lang_week                           = "semana";
  $lang_prev                           = "previa";
  $lang_next                           = "próxima";
  $Current_Date_is                     = "Fecha actual";
  $this_date_occurs_in_the_past        = "Esta fecha se situa en el pasado";
  $Current_Patient                     = "Paciente Actual";
  $Room                                = "Sala";
  $Check_Room                          = "Verificar la Sala";
  $Try_Again                           = "Ensayar una nueva vez";
  $Date                                = "Fecha";
  $The_selected_room_is_free_all_day   = "La sala seleccionada está libre todo el día.";
  $TIME                                = "HORA";
  $NO_PREFERENCE                       = "SIN PREFERENCIA";
  $Patient                             = "Paciente";
  $Time                                = "Hora";
  $lang_hour                           = "hora";  // singular
  $lang_hours                          = "horas"; // plural
  $lang_min_abbrev                     = "min";    // abbreviated minutes
  $lang_h                              = "h";      // single letter for hours
  $lang_m                              = "m";      // single letter for minutes
  $Duration                            = "Dura";
  $Physician                           = "Médico";
  $Note                                = "Apúnte";
  $Adding_Appointment                  = "Agregando la Cita";
?>