<?php
  # file: lang/ES/call-in.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # Mod : 19990922

$Call_In              = "Llamada";
$Add                  = "Agregar";
$Adding               = "Agregando";
$Clear                = "Borrar";
$Name                 = "Nombre";
$Last                 = "Apellido";
$First                = "Nombre";
$Middle               = "Suplemento";
$Contact_Information  = "Informaciones de Contacto";
$Home_Phone           = "Fono Domicilio";
$Work_Phone           = "Fono Trabajo";
$Took_Call            = "Recibio la llamada";
$Date_of_Birth        = "Fecha de Nacimiento";
$Complaint            = "Mensaje";
$Facility             = "Local";
$Physician            = "Médico";
$Patient_Menu         = "Menu Pacientes";
$Call_In_Menu         = "Menu Llamadas";
$Main_Menu            = "Menu Principal";
$NOT_IMPLEMENTED_YET  = "NO HA SIDO IMPLEMENTADO AUN";
$Date_of_Call         = "Fecha de la Llamada";
$Home_Work_Phone      = "Fono Domicilio/Trabajo";
$Action               = "Accion";
$VIEW                 = "VER";
$BOOK                 = "CITA";
  // 19990920
$Old                  = "Antiguas";
$All                  = "Todas";
$Current              = "Actuales";


?>
