<?php
  # file: lang/ES/cpt.php3.ES.inc
  # desc: CPT codes spanish (ES) language module
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver : 19990921

  $record_name                      = "Códigos de actos";

  $CPT_Code                         = "Código de acto";
  $CPT_Name_Internal                = "Nombre C.A. (Interno)";
  $CPT_Name_External                = "Nombre C.A. (Externo)";
  $Relative_Value                   = "Valor relativo";
  $Example                          = "ej.";
  $Type_of_Service                  = "Tipo de Servicio";
  $Internal_Name                    = "Nombre Interno";
?>
