<?php
  # file: lang/ES/db_maintenance.php3.ES.inc
  # desc: database maintenance menu spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991102

  $Database_Maintenance            = "Configuración de la base de datos";
  $CPT_Procedural_Codes            = "CPT/Códigos de Procesos";
  $CPT_Procedural_Modifiers        = "CPT/Modificadores de Códigos";
  $Formulary_Pharmacy_Module       = "Módulo de Farmacia";
  $ICD_Codes                       = "Códigos CIE";
  $Insurance_Companies             = "Compañías de segúros";
  $Insurance_Company_Groups        = "Grupos de Compañías de segúros";
  $Physicians                      = "Médicos";
  $Physician_Degrees               = "Títulos de Médicos";
  $Physician_Groups                = "Grupos de Médicos";
  $Physician_Specialties           = "Especialidades de Médicos";
  $Physician_Statuses              = "Estatutos de Médicos";
  $Place_of_Service_Facilities     = "Locales y Lugares de ejercicio";
  $Rooms                           = "Cuartos";
  $Scheduling_Locations            = "Locales para citas";
  $Type_of_Service                 = "Tipo de Servicio";
  $Templates_for_Simple_Reports    = "Modelos de Informes";
  $You_dont_have_access_for_this_menu = "Ud. no tiene acceso a este menu." ;
  $Selectable_Printers             = "Impresoras Disponibles"              ;
  $Fixed_Forms                     = "Formularios" ;
  $Custom_Patient_Record_Templates = "Modelos de Fichas de Información" ;
  $Diagnosis_Families              = "Famílias de Diagnósticos" ;
?>
