<?php
  # file: lang/FR/degrees.php3.FR.inc
  # desc: physician degrees spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name                         = "Títulos y Grados";

  $Degree_Title                        = "Título";
  $Degree_Title_Example                = "Especialista en Reumatología, etc";
  $Degree_Name                         = "Abreviación";
  $Degree_Name_Example                 = "MD, DPM, etc";
  $Date_Last_Modified                  = "Fecha de la última modificación";
  $Degree                              = "Título";
  $Description                         = "Descripción";
  $No_degrees_are_currently_in_the_database =
     "No hay actualmente ningún título en la base de datos.";
?>
