<?php
  # file: lang/ES/facility.php3.ES.inc
  # desc: facility (place of service) spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver: 19991005

  $record_name = "Locales de práctica";

  $Facility_Name                  = "Denominación";
  $Address_Line_1                 = "Dirección, línea 1";
  $Address_Line_2                 = "Dirección, línea 2";
  $City                           = "Ciudad";
  $State                          = "Estado/Región";
  $Zip                            = "Código Postal";
  $Description_Note               = "Descripción";
  $Default_Physician              = "Médico por omisión";
  $Phone_Number                   = "Número Tel.";
  $Fax_Number                     = "Número Fax.";
  $Email_Address                  = "Correo Electrónico";
  $Date_of_Entry                  = "Fecha de entrada";
  $Country                        = "País";   // 19991005
?>