<?php
  # file: lang/FR/frmlry.php3.FR.inc
  # desc: formulary/pharmacy french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation : max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name = "Recetario";

  $Class                          = "Clase";
  $Generic_Name                   = "Nombre Genérico";
  $Trademark_Name                 = "Nombre Comerciál";
  $Indication_1                   = "Indicación 1";
  $Indication_2                   = "Indicación 2";
  $Indication_3                   = "Indicación 3";
  $Date_Added                     = "Agregado el";
?>
