<?php
  # file: lang/ES/index.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod : 19990924

  $Username                  = "Usuario";
  $Password                  = "Clave";
  $Enter_the_database        = "Acceso a la base de datos";
  $Clear                     = "Borrar";
  $Language                  = "Idioma";
  $Default                   = "Valor por omisión";
  $Facility                  = "Local";
  $Login                     = "Login";
    // 19990922
  $Resume                    = "Retornar a edición";
  $Reset_Resume              = "Borrar punto de retorno";
?>
