<?php
  # file: lang/ES/main.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod : 19991008

  $Main_menu                 = "Menu Principal" ;
  $Administration_menu       = "Menu de Administracion" ;
  $Billing_functions         = "Facturas" ;
  $Database_maintenance      = "Configuracion de la BD" ;
  $Patient_functions         = "Pacientes" ;
  $Help_main_menu            = "Ayuda para el menu principal" ;
  $Logout_of                 = "Salir de" ;
  $Quickjump                 = "IR A" ;
  $User_level                = "NIVEL USUARIO" ;
  $User_description          = "DESCRIPCION" ;
  $Call_in                   = "Llamadas";
  $Entry                     = "Nueva";
  $Menu                      = "Menu"; 
  // 19990929
  $Day_View                  = "Vista del Día";  
  $Week_View                 = "Vista Semanal (Calendario)";
?>
