<?php
  # file: lang/ES/manage.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod : 19990921

  $Attach_to_Guarantor           = "Ligar al Garante";
  $Must_select_a_patient         = "Ud. debe seleccionar un paciente.";
  $Select_Guarantor_to_Attach_to = "Seleccionar Garante de referencia:";
  $detach                        = "desligar";
  $Attach                        = "Ligar";
  $Return_to_Patient_Management  = "Volver a la Gestion de Paciente";
  $Attaching_Guarantor           = "Ligando el Garante";
  $Detaching_current_dependants  = "Desligando los actuales dependientes";
  $lang_done                     = "terminado.";
  $Manage_Patient                = "Administrar el Paciente";
  $Select_a_patient              = "Seleccionar un paciente";
  $Patient_Information           = "Informacion sobre el paciente";
  $Modify                        = "Modificar";
  $Add                           = "Agregar";
  $View_Manage                   = "Ver/Administrar";
  $Prescriptions                 = "Recetas";
  $Procedures                    = "Procesos";
  $Progress_Notes                = "Apuntes Clinicos";
  $Reports_and_certificates      = "Informes y certificados";  //19990813
  $Choose                        = "Elegir";                   //19990813
  $Show_Dependants               = "Ver los Dependientes";
  $Show_Guarantor                = "Ver el Garante";
  $Last_Name                     = "Apellido";
  $All                           = "Todos";
  $Select_Another_Patient        = "Seleccionar otro Paciente";
    // 19990809
  $Appointments                  = "Citas";
  $Book                          = "Libro";
  $Patient                       = "Paciente";
  $Show_Today                    = "Mostrar Hoy";
?>
