<?php
  # file: lang/FR/phy_avail_map.FR.inc
  # desc: physician available map french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation : max k <amk@span.ch>
  # ver : 19991006

  $record_name = "Disonibilidad del médico";

  $Must_specify_physician          = "Ud. debe precisar un médico!";
  $Absence_date_from               = "Cambio de disponibilidad (Fecha principio)";
  $Absence_date_to                 = "Cambio de disponibilidad (Fecha fin)";
  $Time_beginning                  = "Comienzo de actividad";
  $Time_ending                     = "Fin de actividad";
  // 19991005
  $lang_to                         = "a";
  $Comment                         = "Comentario";
  $Physician                       = "Médico";
  $Availability                    = "Disponibilidad";

?>