<?php
  # file: lang/ES/phystatus.php3.ES.inc
  # desc: physician status spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name               = "Estatutos de Médicos";

  $Status                    = "Estatuto";
  $Update                    = "Poner al día";
  $Remove_Changes            = "Anular las modificaciones";
  $Abandon_Modification      = "Abandonar la Modificación";
  $Modifying                 = "Modificando";
  $Done                      = "Terminado";
  $Return_to_Previous_Menu   = "Volver al menú precedente";
  $Return_to_the_Main_Menu   = "Volver al menu principal";
  $Deleting                  = "Borrando";
  $Deleted                   = "Borrado";
  $RESULT                    = "RESULTADO";
  $Update_Delete_Another     = "Ponér al día o borrár otro";
  $Return_to                 = "Volver a";
  $RETURN_TO_MENU            = "VOLVER AL MENU";
  $No_Record_Found           = "Ningún dato encontrado";


?>
