<?php
  # file: lang/ES/physician_day_view.php3.ES.inc
  # desc: physician daily view french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver: 19991004

  $Physician_Daily_View                    = "Jornada del médico";
  $back_one_day                            = "anterior";
  $forward_one_day                         = "siguiente";
  $No_Physician_Selected                   = "Ningún médico seleccionado"; 
  $Physician                               = "Médico";
?>