<?php
  # file: lang/ES/physician.php3.ES.inc
  # desc: physician maintenance menu spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation : max k <amk@span.ch>
  # lic : GPL
  # ver : 19991102

  $Add_Physician                   = "Agregar un Médico"  ;
  $Last_name                       = "Apellido"           ;
  $First_name                      = "Nombre"             ;
  $Title                           = "Título"             ;
  $Middle_Name                     = "Complemento"        ;
  $Practice_Name                   = "Nombre de Práctica" ;
  $Primary_Address_Line            = "Dirección Principal Línea"  ;
  $Primary_Address_City            = "Dirección Principal Ciudad" ;
  $Primary_Address_State           = "Dirección Principal Estado" ;
  $Primary_Address_Zip             = "Dirección Principal Código Postal" ;
  $Primary_Address_Phone           = "Dirección Principal Fono"   ;
  $Primary_Address_Fax             = "Dirección Principal Fax"    ;
  $Secondary_Address_Line          = "Dirección Secundaria Línea" ;
  $Secondary_Address_City          = "Dirección Secundaria Ciudad";
  $Secondary_Address_State         = "Dirección Secundaria Línea" ;
  $Secondary_Address_Zip           = "Dirección Secundaria Código Postal" ;
  $Secondary_Address_Phone         = "Direccin Secundaria Fono"   ;
  $Email_Address                   = "Correo Electrónico"         ;
  $Cellular_Phone                  = "Fono Celular"               ;
  $BeeperPager                     = "Pager o similar"            ;
  $UPIN_Number                     = "Número de Convención"       ;
  $Social_Security                 = "Nmero de Seguridad Social"  ;
  $Degree                          = "Diploma"             ;
  $Specialty                       = "Especialidad"        ;
  $Internal_ID                     = "Nmero Interno"       ;
  $Status                          = "Estatuto"            ;
  $Reference                       = "Referencia"          ;
  $Number_of_Referrals             = "Número de Pacientes Referidos" ;
  $Primary_care_provider           = "Médoco Primario"     ;
  $Referring                       = "Referente"           ;
  $NULL                            = "NINGUNO"             ;
  $Referral_Amount                 = "Suma de Referencias" ;
  $S_charged                      = "\$ facturados"       ;
  $S_received                     = "\$ recibidos"        ;
  $Add                             = "Agregar"             ;
  $Clear                           = "Borrar"              ;
  $Adding_Physician                = "Agregando un Médico" ;
  $Adding                          = "Agregando"           ;
  $Done                            = "Terminado"           ;
  $ERROR                           = "ERROR"               ;
  $Physician                       = "Médico"              ;
  $Modify_Physician                = "Modificar un Médico" ;
  $Please_use_the_MODIFY_form_to_MODIFY_someone = "Por favor use el formulario MODIFICAR para esta acción" ;
  $Return_to_the_Main_Menu         = "Volver al Menú Principál";
  $Update                          = "Poner al Día"            ;
  $Abandon_Modification            = "Abandonar la Modificación" ;
  $Modifying_Physician             = "Modificando el Médico"     ;
  $Modifying                       = "Modificando"               ;
  $Deleting_Physician              = "Suprimiendo el Médico"     ;
  $RESULT                          = "RESULTADO"                 ;
  $Delete_Another                  = "Borrar Otro"               ;
  $Physician_Display               = "Mostrar los Médicos"       ;
  $You_must_specify_an_id          = "Ud. debe especificar un número"  ;
  $Return_to_the_Physician_Menu    = "Volver al Menú de Médicos" ;
  $NONE_SELECTED                   = "NINGUNO SELECCIONADO"      ;
  $Physicians                      = "Médicos"                   ;
  $Last_Name                       = "Apellido"                  ;
  $First_Name                      = "Nombre"                    ;
  $Degrees                         = "Diplomas"                  ;
  $Action                          = "Acción"                    ;
  $VIEW                            = "VER"                       ;
  $MOD                             = "MOD"                       ;
  $DEL                             = "SUPR"                      ;
  $No_physicians_found_with_that_criteria = "Ningn médico encontrado con aquéllos criterios" ;



?>