<?php
  # file: lang/ES/physician_week_view.php3.ES.inc
  # desc: physician weekly view spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation: max k <amk@span.ch>
  # ver : 19991006 

  $Physician_Weekly_View                   = "Vista hebdomadaria médico";
  $back_one_week                           = "Semana previa";
  $forward_one_week                        = "Semana siguiente";
  $No_Physician_Selected                   = "Ningún médico seleccionado"; 
  $Physician                               = "Médico";

?>
