<?php
  # file: lang/ES/progress_notes.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver: 1990921

  $record_name                  = "Apuntes Clínicos";
  $Module                       = "Modulo";
  $ERROR                        = "ERROR";
  $Must_Specify_A_Patient       = "Ud. debe especificar un paciente!";
  $Entry                        = "Entrar";
  $Manage_Patient               = "Administrar Paciente";
  $View_Modify                  = "Ver/Modificar";
  $Applicable_Date              = "Fecha Aplicable";

    // the actual progress parts (with underlines)
  $Subjective                   = "<U>S</U>ubjetivamente";
  $Objective                    = "<U>O</U>bjetivemente";
  $Assessment                   = "ev<U>A</U>luacion";
  $Plan                         = "<U>P</U>lano";
  $Interval                     = "<U>I</U>ntervalo";
  $Education                    = "<U>E</U>ducación";
  $Prescription                 = "p<U>R</U>escripción";

  $Add                          = "Agregar";
  $Clear                        = "Borrar";
  $Abort_Addition               = "Anular Operación";
  $Adding                       = "Agregando";
  $Done                         = "Terminado";
  $FAILED                       = "FRACASO";
  $Must_Call_With_Patient_ID    = "ud. debe llamar a esta función con un ".
                                  "paciente seleccionado.";
  $Modify                       = "Modificar";
  $Change                       = "Cambiar";
  $Restore                      = "Restablecer";
  $Modifying                    = "Modificando";
  $View                         = "Ver";
  $Menu                         = "Menu";
  $Specify_Notes_to_Display     = "Ud. debe precisar que apuntes mostrar";
  $Modify_Notes                 = "Modificar los Apuntes";
  $Patient                      = "Paciente";
  $This_Patient_Has_No_Notes    = "Este paciente no tiene apúntes hasta este día.";
  $Existing                     = "Existientes";
?>
