<?php
  # file: lang/FR/room.php3.FR.inc
  # desc: room (scheduling location) spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991007

  $record_name = "Salas";

  $Room_Name                      = "Nombre de la Sala";
  $Location                       = "Localisación";
  $Room_Description               = "Descripción de la Sala";
  $Default_Physician              = "Médico por Omisión";
  $Surgery_Equipped               = "Equipo de Cirugía?";
  $Is_Booking_Enabled             = "Las citas activas?";
  $IP_Address                     = "Dirección IP";
  $For_Future_Use                 = "Para futuros usos";
  $For_Scheduling                 = "Para las citas";
  $Description                    = "Descriptivo";
?>
