<?php
  # file: lang/ES/roomequip.php3.ES.inc
  # desc: room equipment spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19990921

  $record_name                       = "Equipo de Cuartos";
  $Name_of_Equipment                 = "Nombre";
  $Description                       = "Descripción";
  $Equipment                         = "Equipo";

?>
