<?php
  # file: lang/FR/Rx.php3.FR.inc
  # desc: prescription module french (FR) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # translation : max k <amk@span.ch>
  # ver : 19991006

  $record_name = "Receta";

  $Must_Have_Patient_For_Prescriptions =
    "Ud. debe haber seleccionado un paciente para utilizar este módulo de recetas.";
  $No_Access_To_This_Patient           =
    "Ud. no tiene acceso a este paciente.";
  $Display                             = "Mostrar";
  $Patient                             = "Paciente";
  $Drug                                = "Medicamento";
  $Dosage                              = "Dosis";
  $Starting_Date                       = "Fecha principio";
  $In_Days                             = "en días";
  $Infinite                            = "0 = infinito";
  $Refills                             = "Repeticiones";
  $Substitution                        = "Substitución";
  $May_Not_Substitute                  = "No substituír";
  $May_Substitute                      = "Puede ser substituído";
  $Manage_Prescriptions                = "Gestion de recetas";
  // 19991002
  $Duration                            = "Durante";
?>
