<?php
  # file: lang/ES/select_printer.php3.ES.inc
  # desc: Selectable printer management spanish (ES) language file
  # code: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991020

  $record_name = "Impresoras Disponibles" ;

  $Selectable_Printer    = "Impresora Disponible" ;
  $Printer_Name          = "Nombre de la Impresora" ;
  $Printer_Host          = "Máquina"              ;
  $Access_Level          = "Nivel de Acceso"      ;
  $Description           = "Descripción"          ;
  $Add                   = "Agregar"              ;
  $Clear                 = "Borrar"               ;
  $Adding                = "Agregando"            ;
  $Done                  = "Terminado"            ;
  $ERROR                 = "ERROR"                ;
  $Return_to             = "Volver a"             ;
  $Menu                  = "Menu"                 ;
  $Modify                = "Modificar"            ;
  $Please_use_MODIFY     = "Por Favor use el formulario de MODIFICACION" ;
  $Return_to_the_Main_Menu = "Volver al Menu Principal" ;
  $RESULT                = "RESULTADO"                  ;
  $Abandon_Addition      = "Abandonar la Adición"       ;
  $Update                = "Poner al Día"               ;
  $Remove_Changes        = "Anular los Cámbios"         ;
  $Abandon_Modification  = "Abandonar la Modificación"  ;
  $Modifying             = "Modificando"                ;
  $Deleting              = "Suprimiendo"                ;
  $Deleted               = "Suprimida"                  ;
  $Update_Delete_Another = "Modificar o Suprimir Otra"  ;
  $Export                = "Exportar"             ;
  $Exporting_data        = "Exportando datos"     ;
  $Action                = "Acción"               ;
  $Printer               = "Impresora"            ;
  $Host                  = "Máquina"              ;
  $MOD                   = "MOD"                  ;
  $DEL                   = "SUPR"                 ;
  $No_Record_Found       = "Ningún Dato Encontrado" ;
  $Current_Contents      = "Contiene Actualmente"   ;
  $For_Reference         = "Para Información"       ;

?>
