<?php
  # file        : lang/FR/simplerep.php3.FR.inc
  # code        : jeff b <jeff@univrel.pr.uconn.edu>
  # Translation : max k <amk@span.ch>
  # lic         : GPL
  # ver         : 19991103

  $record_name = "Informes";

  $Add                     = "Agregar";
  $Clear                   = "Borrar"; 
  $Label                   = "Identificador";
  $Category                = "Categoria";
  $Text                    = "Texto";
  $Abandon_Addition        = "Renunciar a agregar";
  $Adding                  = "Agregando";
  $Return_to               = "Volver a";
  $Modify                  = "Modificar";
  $Please_use_MODIFY       = "Por favor utilize la funcion MODIFICAR para esto";
  $Return_to_the_Main_Menu = "Volver al menu principal";
  $Update                  = "Poner al día";
  $Remove_Changes          = "Anular los cambios";
  $Abandon_Modification    = "Renunciar a la modificación";
  $Modifying               = "Modificando";
  $Done                    = "Terminado";
  $ERROR                   = "ERROR";
  $Menu                    = "Menu";
  $Deleting                = "Borrando";
  $Deleted                 = "Borrado";
  $Update_Delete_Another   = "Poner al día/suprimir otro";
  $Must_Have_Patient_to_Make_Reports =
    "Ud. debe seleccionar primero un paciente para hacer el informe!";
  $Choose_Report_for_Patient   = "Elejir un informe para este paciente";
  $Patient                     = "Paciente";
  $Manage_Patient              = "Administrar paciente";
  $Action                      = "Acción";
  $Mr                          = "Sr";   // 19990926
  $Mrs                         = "Sra";
  $Report                      = "Informe";
  $Physician                   = "Médico";
  $Facility                    = "Local";
  $Proceeding                  = "proseguir";  //  19990927
  $Proceed                     = "Proseguir";
  $Please_choose               = "Por favor elegir";  // 19990927
  $Before                      = "antes de";
  $Return_to_report_selection  = "Volver a la Seleccion de Informes"; // 19990928
  $Destinatary_is              = "El destinatario es";
  $Delivery_Method             = "Modo de entrega";
  $NONE_SELECTED               = "NINGUNO SELECCIONADO";
  $The_Patient                 = "El Paciente";
  $A_Physician                 = "Un Médico";
  $An_Insurer                  = "Un Seguro";
  $Other                       = "Otro";
  $Printer                     = "Imprimir";
  $Fax                         = "Fax"; 
  $E_mail                      = "E-mail";
  $Edit_report_for_patient     = "Editár el informe para el paciente";
  $Phone                       = "Fono";
  $Datequalif                  = "el";
  $Help_for_simple_reports     = "Ayuda para creación de informes";
  $Edit_add_simple_reports     = "Agregar o Editar Informes";  // 19991007
  $Patients_primary_insurer    = "Primer Seguro del Paciente";   // 19991008
  $Patients_secundary_insurer  = "Segundo Seguro del Paciente";
  $Patients_tertiary_insurer   = "Tercer Seguro del Paciente";
  $Select_from_contact_list    = "Elegir en la lista de contactos";
  $Patients_primary_employer   = "Primer Empleador del Paciente";
  $Patients_secundary_employer = "Segundo Empleador del Paciente";
  $No_delivery_method_selected = "Ningúna manera de enviar seleccionada!"; // 19991008
  $Print                       = "Imprimir";
  $To                          = "Destinado a";                      // 19991009
  $Patient_has_no_fax          = "Este paciente no tiene número de fax...";
  $Send                        = "Enviar este";
  $Patient_has_no_email        = "Este paciente no tiene dirección e-mail";
  $A_physician_must_sign_his_own_name = "Un médico debe firmar con su propio nombre";
  $Verification_Key            = "Clave de autenticidad";
  $Suppress_headers            = "No mostrar el encabezado";
  $Show_full_titles            = "Mostrar todos los títulos del Médico";
  $Mailed                      = "Mensaje Enviado" ;
  $From                        = "De" ;
  $Copy_to                     = "Copia a" ;
  $Subject                     = "Objeto" ;
  $Male                        = "Masculino"  ;
  $Female                      = "Femenino"   ;
  $Adult                       = "Adulto"     ;
  $Child                       = "Menor"      ;
  $Return_to_reports_menu      = "Volver al Menú de los Informes" ;  



?>
