<?php
  # file: lang/ES/simplerep_lout.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # module: max k <amk@span.ch>
  # lic : GPL
  # ver: 19991026


  $Verification_Key            = "Clave de verificación" ;
  $To                          = "Destinado a"           ;
  $Generate_lout_for           = "Genera lout para"      ;
  $Sr_page                     = "Página"                ;
  $From                        = "De"                    ;
  $Of                          = "de"                    ;
  $Page                        = "Página"                ;
  $Return_to_report_selection  = "Volver a la Seleccion de Informes" ;

?>