<?php
  # file: lang/ES/specialties.php3.ES.inc
  # desc: specialties spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19990924

  $record_name = "Especialidades";

  $Specialty_Name                        = "Nombre de la Especialidad";
  $Specialty_Description                 = "Descripción de la Especialidad";
  $Name                                  = "Nombre";
  $Description                           = "Descripción";
?>
