<?php
  # file: lang/ES/tos.php3.ES.inc
  # desc: type of service spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991015

  $record_name = "Tipos de Servicios (TdS)";

  $Type_of_Service_Name        = "Nombre TdS";
  $Type_of_Service_Description = "Descripción TdS";
  // 19991013
  $Name                        = "Nombre";
  $Description                 = "Descripción";

?>
