<?php
  # file: lang/ES/tos.php3.ES.inc
  # desc: type of service spanish (ES) language file
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # translation: max k <amk@span.ch>
  # lic : GPL
  # ver : 19991015

  $record_name = "Tipos de Servicios (TdS)";

  $phrase[Type_of_Service_Name]        = "Nombre TdS";
  $phrase[Type_of_Service_Description] = "Descripción TdS";
  // 19991013
  $phrase[Name]                        = "Nombre";
  $phrase[Description]                 = "Descripción";

?>
