<?php
  # file: lang/ES/user.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod: 20000528

  $record_name                             = "Usuario";  

    // this is in API.inc
  //$Add                                     = "Agregar" ;
  //$Adding                                  = "Agregando" ;
  //$Modify                                  = "Modificar" ;
  //$Modifying                               = "Modificando" ;
  $phrase[User_name]            = "Usuario" ;
  $phrase[Password]             = "Clave" ;
  $phrase[Verify]               = "verificar" ;
  $phrase[Description]          = "Descriptivo" ;
  $phrase[Physician_group]      = "Grupo de Médicos" ;
  $phrase[User_level]           = "Nivel de acceso" ;
  $phrase[Locked_out]           = "!!! Excluido !!!" ;
  $phrase[Undefined]            = "INDEFINIDO" ;
  $phrase[Delete_privs]         = "Puede Borrar" ;
  $phrase[Superuser]            = "SuperUsuario/Admin." ;
  $phrase[Update]               = "Actualizar" ;
  $phrase[Remove_changes]       = "Anular cambios" ;
  $phrase[Abandon_addition]     = "Abandonar la operacion" ; # Just say no ;-)
  $phrase[Passwords_must_match] = "Error en la repeticion de la clave!" ;
  $phrase[Done]                 = "Terminado" ;
  $phrase[Go_back_to_user_menu] = "Volver al menu de usuarios" ;
  $phrase[Please_use_the_modify_form] 
                            = "Favor use el formulario MODIFICAR para cambiar" ;
  $phrase[Return_to_main_menu]  = "Volver al menu principal" ;
  $phrase[Result]               = "RESULTADO" ;
  $phrase[Error]                = "ERROR" ;
  $phrase[You_cannot_modify_root] = "Ud. no puede modificar el superusuario" ;
  $phrase[You_cannot_delete_root] = "Ud. no puede borrar el superusuario" ;
  $phrase[Query_result]         = "Resultado de la interrogacion" ;
  $phrase[Query_string]         = "Cadena de la interrogacion" ;
  $phrase[Actual_query_result]  = "Verdadero resultado de la interrogacion" ;
  $phrase[Deleting]             = "Borrando" ;
  $phrase[Delete]               = "Borrar" ;
  $phrase[Another]              = "otro" ;
  $phrase[Maintenance]          = "Mantencion" ;
  $phrase[Action]               = "Accion" ;
  $phrase[No]                   = "Ningun" ;
  $phrase[Found_with_that_criteria] = "encontrado con aquéllos criterios" ;
  $phrase[Try_Again]             = "Ensayar de nuevo";     //19990813
  $phrase[Authorized_facilities] = "Locales autorizados";
  $phrase[Authorized_physicians] = "Médicos autorizados";
  $phrase[Authorized_phy_groups] = "Grupos de médicos autorizados"; 
  $phrase[User_type]            = "Tipo de usuario";
  $phrase[Physician]            = "Médico";
  $phrase[Miscellaneous]        = "Diversos";
  $phrase[MOD]                  = "MOD" ;
  $phrase[DEL]                  = "SUPR" ;
  $phrase[Actual_physician]     = "Médico real";
?>
