<?php
  # file: lang/ES/user.php3.ES.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by max k <amk@span.ch>
  # mod: 19991004

  $record_name                             = "Usuario";  

  $Add                                     = "Agregar" ;
  $Adding                                  = "Agregando" ;
  $Modify                                  = "Modificar" ;
  $Modifying                               = "Modificando" ;
  $User_name                               = "Usuario" ;
  $Password                                = "Clave" ;
  $Verify                                  = "verificar" ;
  $Description                             = "Descriptivo" ;
  $Physician_group                         = "Grupo de Médicos" ;
  $User_level                              = "Nivel de acceso" ;
  $Locked_out                              = "!!! Excluido !!!" ;
  $Undefined                               = "INDEFINIDO" ;
  $Delete_privs                            = "Puede Borrar" ;
  $Superuser                               = "SuperUsuario/Admin." ;
  $Update                                  = "Actualizar" ;
  $Remove_changes                          = "Anular cambios" ;
  $Abandon_addition                        = "Abandonar la operacion" ; # Just say no ;-)
  $Passwords_must_match                    = "Error en la repeticion de la clave!" ;
  $Done                                    = "Terminado" ;
  $Go_back_to_user_menu                    = "Volver al menu de usuarios" ;
  $Please_use_the_modify_form              = "Favor use el formulario MODIFICAR para cambiar" ;
  $Return_to_main_menu                     = "Volver al menu principal" ;
  $Result                                  = "RESULTADO" ;
  $Error                                   = "ERROR" ;
  $You_cannot_modify_root                  = "Ud. no puede modificar el superusuario" ;
  $You_cannot_delete_root                  = "Ud. no puede borrar el superusuario" ;
  $Query_result                            = "Resultado de la interrogacion" ;
  $Query_string                            = "Cadena de la interrogacion" ;
  $Actual_query_result                     = "Verdadero resultado de la interrogacion" ;
  $Deleting                                = "Borrando" ;
  $Delete                                  = "Borrar" ;
  $Another                                 = "otro" ;
  $Maintenance                             = "Mantencion" ;
  $Action                                  = "Accion" ;
  $No                                      = "Ningun" ;
  $Found_with_that_criteria                = "encontrado con aquéllos criterios" ;
  $Try_Again                               = "Ensayar de nuevo";     //19990813
  $Authorized_facilities                   = "Locales autorizados";
  $Authorized_physicians                   = "Médicos autorizados";
  $Authorized_phy_groups                   = "Grupos de médicos autorizados"; 
  $User_type                               = "Tipo de usuario";
  $Physician                               = "Médico";
  $Miscellaneous                           = "Diversos";
  $lang_MOD			   	   = "MOD" ;
  $lang_DEL			           = "SUPR" ;
  $Actual_physician                        = "Médico real";
?>
