<?php
  # ficheiro: lang/PT/admin.php3.PT.inc  
  # tradução : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228
  # file lang/PT/admin.php3.PT.inc  
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228

  $No_admin_menu_access = "Não tem acesso ao menu administrativo" ; 
  $Icd_code_type = "Tipo de código ICD" ;
  $Graphics_enhanced = "Gráficos" ;
  $Disabled = "Desactivo" ;
  $Enabled = "Activo" ;
  $Scheduling_start_time = "Início do tempo de horário" ;
  $Scheduling_end_time = "Fim do tempo de horário" ;
  $Configure = "Configuração" ;
  $Reset = "Desligar" ;
  $Configuration_complete = "Configuração completa" ;
  $Return_adm_menu = "Voltar ao menu administrativo" ;
  $Reinitialize_database = "Re-inicializar a base de dados" ;
  $Are_you_sure = "Tem a certeza que quer" ;
  $Irreversable_process = "Isto é um processo irreversível!" ;
  $First_initialization = "Verifique aqui se é a primeira inicialização" ;
  $Continue = "Continuar" ;
  $Cancel = "Cancelar" ;
  $Erasing_old_db = "Apagando a base de dados antiga" ;
  $Error_accessing_sql = "Erro ao aceder à base de dados SQL" ;
  $Creating_new_db = "Criando uma nova base de dados" ;
  $Creating_tables = "Criando tabelas" ;
  $Administration_menu = "Menu administrativo" ;
  $Update_config = "Actualizar a configuração" ;
  $User_maintenance = "Manutenção dos utilizadores" ;
  $Return_main_menu = "Voltar ao menu principal" ;
  $DEFAULT = "Início";
    // 19990830
  $SELECTED = "SELEccionado";
  $Update_Configuration = "Actualizar a configuração";
    // 19991007
  $Calendar_overbooking = "Over-Booking do calendário";

?>
