<?php
  # ficheiro : lang/PT/API.PT.inc
  # código : Cristina Bouça<bugsoft@bug-software.com>
  # lic  : GPL
  # Tradução por Cristina Bouça
  # ver : 20000228
  # file : lang/PT/API.PT.inc
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $DEBUG_IS_ON = "Verificando erros";
  $Return_to_the_Main_Menu = "Voltar ao menu principal";
  $Return_to_Previous_Menu = "Voltar ao menu anterior";
  $lang_main = "principal"; // alt tag para o menu superior
  $lang_exit = "exit"; // alt tag para sair do menu superior
  $RETURN_TO_MENU          = "Voltar ao menu";
  $NONE_SELECTED           = "Nada foi seleccionado";
  $SELECTED                = "SELECTED"; // must NOT be translated
  $lang_coded_by           = "feito por"; 
  $NO_RESULT_OF_QUERY      = "Nenhum resultado da pesquisa";
  $Entered_incorrect_NamePasswd =
    "Introduziu um nome ou password incorrectos";
  $Possible_Cookies_Have_Expired =
    "Também é possível que as suas cookies tenham acabado. Por favor<BR>
     volte a fazer login, ou pergunte ao seu administrador de sistema para incrementar a<BR>
     o tempo limite dos cookies.";
  $Login_Screen            = "Menu de Login";
    // 19990824
  $Add                     = "Adicionar";
  $Adding                  = "Adicionando";
  $Clear                   = "Limpar";
    // 19990917
  $Return_to               = "Voltar para";
  $Main_Menu               = "Menu principal";
  $Modify                  = "Modificar";
  $Modifying               = "Modificando";
  $Done                    = "terminou";
  $Menu                    = "Menu";
  $Deleting                = "Apagando";
  $Update_Delete_Another   = "Actualizar/Apagar outro";
  $Deleted                 = "apagado";
  $Abandon_Addition        = "Acabar adicionar";
  $Abandon_Modification    = "Acabar mofificação";
  $Update                  = "Actualizar";
  $Remove_Changes          = "Apagar Alterações";
  $Exporting_data          = "Exportando dados";
  $Export                  = "Exportar";
  $ERROR                   = "ERRO";
  $Action                  = "Acção";
  // 19990920
  $lang_ALL                = "TUDO";
  // 19990921
  $lang_ADD                = "ADICIOANR";  
  $lang_MOD                = "MODIFICAR";
  $lang_DEL                = "APAGAR";
  // 19990922
  $No_Record_Found         = "Não foi encontrado $record_name com a selecção feita.";
  $lang_back               = "Atrás";
  // 19990924
  $lang_HELP               = "AJUDA";
  $Module                  = "MÓDULO";
  $Manage_Patient          = "Actualizar Paciente";
  // 19991005
  $Week_Of                 = "Semana de";
  // 19991013
  $Export_Database         = "Exportar base de dados";
  // 19991026
  $Export_Data             = "Exportar dados";
  // 19991102
  $lang_months             = array ("", // nulo para 0
                                    "Jan",
                                    "Fev",   
                                    "Mar",
                                    "Abr",
                                    "Mai",
                                    "Jun",
                                    "Jul",
                                    "Ago",
                                    "Set",
                                    "Out",
                                    "Nov",
                                    "Dez" );
  $lang_days               = array ("", // nulo para 0
                                    "Dom",
                                    "Seg",
                                    "Ter",
                                    "Qua",
                                    "Qui",
                                    "Sex",
                                    "Sab" ); 
  // 19991116
  $midnight                = "meia noite";
  $noon                    = "noite";
  // 19991122
  $Patient                 = "Paciente";
  $lang_no                 = "não";
  $lang_yes                = "sim";
  $lang_go                 = "ir";  
  $State_Providence        = "Estado/Providência";
  $Return_to_Menu          = "Voltar para o menu";
  // 19991201
  $Post                    = "Post";
?>
