<?php
  # ficheiro: ling/PT/authenticate.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Tradução por Cristina Bouça <bugsoft@bug-software.com>
  # file : ling/PT/authenticate.php3.PT.inc
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Error = "ERRO" ;
  $Return_to_the_login_screen = "Voltar ao ecran de Login";
  $Incorrect_name_password= "Você introduziu o nome ou password incorrecta. <BR>
   Por favor contacte o seu administrador de sistema. Se pensa que esta mensagem é<BR>
   um erro, por favor tome nota das circunstâncias em que isso<BR>
   aconteceu, e forneça isso ao seu administrador de sistema." ;
?>
