<?php
  # file: lang/PT/authenticate.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>


  $Error = "ERROR" ;
  $Return_to_the_login_screen = "Retornar a tela de autenticação" ;
  $Incorrect_name_password= "Nome do usuário ou senha incorretos. <BR>
   No caso desta mensagem aparecer varia vezes, notifique  seu <BR>
   administrador de sistemas. Por favor anote as circunstâncias em que<BR>
   esta mensagem aparece, e comunique igualmente seu seu adminisrador de<BR>
   sistemas. Estas informações serão úteis para sanar o problema." ;

?>
