<?php
  # ficheiro: ling/PT/book_appointment.php3.PT.inc
  # desc: Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228



  $Add_Appointment                     = "Adicionar Apontamento";
  $lang_day                            = "dia";
  $lang_week                           = "Semana";
  $lang_prev                           = "anterior";
  $lang_next                           = "próximo";
  $Current_Date_is                     = "A data actual é";
  $this_date_occurs_in_the_past        = "esta data aconteceu ao copiar";
  $Current_Patient                     = "Paciente actual";
  $Room                                = "Sala";
  $Check_Room                          = "Sala de Entrada";
  $Try_Again                           = "Tente novamente";
  $Date                                = "Data";
  $The_selected_room_is_free_all_day   = "A sala seleccionada está livre todo o dia.";
  $TIME                                = "TEMPO";
  $NO_PREFERENCE                       = "SEM PREFERÊNCIA";
  $Patient                             = "Paciente";
  $Time                                = "Tempo";
  $lang_hour                           = "hora";   // singular
  $lang_hours                          = "horas";  // plural
  $lang_min_abbrev                     = "min";    // abbreviated minutes
  $lang_h                              = "h";      // single letter for hours
  $lang_m                              = "m";      // single letter for minutes
  $Duration                            = "Duração";
  $Physician                           = "Cirurgião";
  $Note                                = "Nota";
  $Adding_Appointment                  = "Adicionar Apontamento";
  // 19991013
  $Facility                            = "Facilidade";
  $Change_Room                         = "Sala de mudanças";
?>
