<?php
  # ficheiro: ling/PT/call-in.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Tradução por Cristina Bouça <bugsoft@bug-software.com>
  # Mod : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Call_In              = "Chamada";
  $Name                 = "Nome";
  $Last                 = "Último";
  $First                = "Primeiro";
  $Middle               = "Meio";
  $Contact_Information  = "Informação para contacto";
  $Home_Phone           = "Telefone de casa";
  $Work_Phone           = "Telefone do trabalho";
  $Took_Call            = "Chamar";
  $Date_of_Birth        = "Data de nascimento";
  $Complaint            = "Mensagem";
  $Facility             = "Facilidade";
  $Physician            = "Cirurgião";
  $Patient_Menu         = "Menu dos Pacientes";
  $Call_In_Menu         = "Chamada no Menu";
  $Main_Menu            = "Menu Principal";
  $NOT_IMPLEMENTED_YET  = "AINDA NÃO ESTÁ IMPLEMENTADO";
  $Date_of_Call         = "Data de chamada";
  $Home_Work_Phone      = "Casa/Trabalho Telefone";
  $Action               = "Acção";
  $VIEW                 = "VER";
  $BOOK                 = "LIVRO";
  // 19990920
  $Old                  = "Antigo";
  $All                  = "Tudo";
  $Current              = "Actual";
?>
