<?php
  # file: ling/EN/cpt.php3.PT.inc
  # desc: Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


// 19990927 - mark l
  $Clear        = "Limpar";

  $record_name                      = "Código CPT";

  $CPT_Code                         = "Código CPT";
  $CPT_Name_Internal                = "Nome CPT (Interno)";
  $CPT_Name_External                = "Nome CPT (Externo)";
  $Relative_Value                   = "Valor relativo";
  $Example                          = "ex";
  $Type_of_Service                  = "Tipo de serviço";
  $Internal_Name                    = "Nome Interno";
?>
