<?php
  # ficheiro: ling/PT/cptmod.php3.PT.inc
  # desc: Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name                      = "Mofificador CPT";

  $Modifier                         = "Modificador";
  $Description                      = "Descrição";
?>
