<?php
  # ficheiro: ling/EN/custom_records.php3.PT.inc
  # desc: Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Registos";

  $Must_select_a_patient       =
      "Não pode fazer isto a não ser que seleccione um paciente!";
  $Must_select_a_template      =
      "Não pode fazer isto a não ser que seleccione um formulário!";
  $Select_a_Patient            = "Seleccione um paciente";
  $No_records_for_this_patient = "Não existem registos para este paciente.";
  $Date_Added                  = "Dados adicionados";
  $Form                        = "Form";
?>
