<?php
  # ficheiro: ling/PT/db_maintenance.php3.PT.inc
  # desc: manutenção da base de dados menu Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Database_Maintenance            = "Manutenção da base de dados";
  $CPT_Procedural_Codes            = "CPT/Códigos";
  $CPT_Procedural_Modifiers        = "CPT/Modificadores";
  $Formulary_Pharmacy_Module       = "Formulário (Farmácia) Módulo";
  $ICD_Codes                       = "ICD 9/10 Códigos";
  $Insurance_Companies             = "Companhias";
  $Insurance_Company_Groups        = "Grupos de Companhias";
  $Physicians                      = "Cirurgião";
  $Physician_Degrees               = "Grau Cirurgião";
  $Physician_Groups                = "Grupos Cirurgião";
  $Physician_Specialties           = "Especialidades Cirurgião";
  $Physician_Statuses              = "Estatutos Cirurgião";
  $Place_of_Service_Facilities     = "Facilidades (<I>Lugares de serviço</I>)";
  $Rooms                           = "Salas";
  $Scheduling_Locations            = "Mapa de Localizações";
  $Type_of_Service                 = "Tipo de serviço";
  $Templates_for_Simple_Reports    = "Formulários para um relatório simples";
  $You_dont_have_access_for_this_menu = "You don't have access for this menu.";
  $Selectable_Printers             = "Impressoras seleccionadas" ;
  $Fixed_Forms                     = "Menus existentes" ;
  $Custom_Patient_Record_Templates = "Optimizar formulários dos pacientes" ;
  $Diagnosis_Families              = "Diagnóstico da Família" ;

?>
