<?php
  # file: ling/PT/degrees.php3.PT.inc
  # desc: Grau de cirurgião Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # mods: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name="Grau Cirurgião";


  $Degree_Title                        = "Título do grau";
  $Degree_Title_Example                = "Médico Pediatra, etc";
  $Degree_Name                         = "Nome do grau";
  $Degree_Name_Example                 = "MD, etc";
  $Date_Last_Modified                  = "Data da última actualização";
  $Degree                              = "Grau";
  $Description                         = "Descrição";
  $No_degrees_are_currently_in_the_database =
     "Nenhum grau está na base de dados actual.";
?>
