<?php
  # ficheiro: ling/PT/episode_of_care.php3.EN.inc
  # desc: Tratamento Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Tratamento";

  $Must_select_record_to_modify =
          "tem que escolher um registo para alterar.";
  $Return_to_Menu              = "Voltar ao Menu";
  $Description                 = "Descrição";
  $Related_to_Pregnancy        = "Relatório de gravidez?";
  $Date_of_First_Occurance     = "Data da primeira ocorrência";
  $Related_to_Employment       = "Relatório para emprego";
  $Date_of_Last_Similar        = "Data do último similar";
  $Related_to_Automobile       = "Relatório para acidente de automóvel";
  $Referring_Physician         = "Referência Cirurgião";
  $Related_to_Other_Cause      = "Relatório para outra causa";
  $Facility                    = "Facilidade"; 
  $Diagnosis_Family            = "Diagnóstico de família";
  $Episode_Type                = "Tipo de tratamento";
  $lang_acute                  = "acontecimento";
  $lang_chronic                = "crónica";
  $lang_chronic_recurrent      = "crónica recorrente";
  $lang_historical             = "histórico";
  $Automobile_Related_Information =
           "Informação do Automóvel";
  $Auto_Insurance              = "Automóvel";
  $Case_Number                 = "Número";
  $Address                     = "Morada";
  $Line_1                      = "Linha 1";
  $Line_2                      = "Linha 2";
  $Contact_Name                = "Nome contacto";
  $Contact_Phone               = "Telefone contacto #";
  $City                        = "Localidade";
  $St_Pr                       = "Concelho";
  $Postal_Code                 = "Código Postal";
  $Email_Address               = "Endereço de Email";
  $Country                     = "País";
  $Employment_Related_Information =
            "Informação do empregado";
  $Name_of_Employer            = "Nome do empregado";
  $File_Number                 = "Ficheiro número";
  $Pregnancy_Related_Information = 
            "Relatório de gravidez";
  $Length_of_Cycle             = "Tempo (dias)";
  $Last_Menstrual_Period       = "ùltimo período menstrual";
  $Gravida                     = "Grávida";
  $Date_of_Confinement         = "Data de fim";
  $Para                        = "Para";
  $Miscarries                  = "Doenças";
  $Abortions                   = "Abortos";
  $Other_Related_Information   = "Outras informações";
  $More_Information            = "Mais informações";
  $Must_specify_patient        = "Tem que escolher o paciente.";
  $Starting_Date               = "Data de início";
  $Description                 = "Descrição";
  $No_record_for_patient       = "Nenhum registo para a paciente escolhido.";
?>
