<?php
  # ficheiro: ling/PT/facility.php3.PT.inc
  # desc: eventos Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228

  # ver : 19991005

  $record_name = "Eventos (POS)";

  $Facility_Name                  = "Nome Evento";
  $Address_Line_1                 = "Primeira linha da morada";
  $Address_Line_2                 = "Segunda linha da morada";
  $City                           = "Cidade";
  $State                          = "Concelho";
  $Zip                            = "Código Postal";
  $Description_Note               = "Descrição/Notas";
  $Default_Physician              = "Cirurgião_inicial";
  $Phone_Number                   = "Número de Telefone";
  $Fax_Number                     = "Número de Fax";
  $Email_Address                  = "Endereço de Email";
  $Date_of_Entry                  = "Data de entrada";
  $Country                        = "País";   // 19991005
?>
