<?php
  # ficheiro : ling/PT/frmlry.php3.PT.inc
  # desc : formulário farmácia Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # mods : Cristina Bouça <bugsoft@bug-software.com>
  # lic  : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Formulário";

  $Class                          = "Classe";
  $Generic_Name                   = "Nome Genérico";
  $Trademark_Name                 = "Nome de Mara";
  $Indication_1                   = "Indicação 1";
  $Indication_2                   = "Indicação 2";
  $Indication_3                   = "Indicação 3";
  $Date_Added                     = "Data de introdução";
?>
