<?php
  # ficheiro: ling/PT/icd9.php3.PT.inc
  # desc: CPT códigos Português (PT) 
  # Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


//19990927
  $Clear        = "Limpar";

  $record_name                      = "Código ICD9";

  $ICD9_Code                        = "Código ICD9";
  $ICD10_Code                       = "Código ICD10";
  $ICD9_Description                 = "Descrição ICD9";
  $ICD10_Description                = "Descrição ICD10";
  $Date_of_Entry                    = "Data de entrada";
  $Diagnosis_Related_Groups         = "Diagnósticos de grupos (Sem uso)";
  $Number_of_Times_Used             = "Número de vezes que foi usado";
  $Amount_Billed                    = "Total cobrado";
  $Amount_Collected                 = "Total junto";
?>
