<?php
  # file: lang/PT/index.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>
 

  $Username                  = "Usuário";
  $Password                  = "Senha";
  $Enter_the_database        = "Acessar a  base de dados";
  $Clear                     = "Limpar";
  $Language                  = "Idioma";
  $Default                   = "Padrão";
  $Facility                  = "Local";
  $Login                     = "Entrar";

?>
