<?php
  # ficheiro: ling/PT/index.php3.PT.inc
  # Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Tradução por Cristina Bouça
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Username     = "Nome do utilizador";
  $Password     = "Password";
  $Enter_the_database = "Base de dados";
  $Clear        = "Limpar";
  $Language     = "Linguagem";
  $Default      = "Por defeito";
    // 19990820
  $Facility     = "Evento";
  $Login        = "Login";
    // 19990922
  $Resume       = "Resumo";
  $Reset_Resume = "Apagar resumo";
?>
