<?php
  # ficheiro: ling/PT/main.php3.PT.inc
  # Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Tradução por Cristina Bouça
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Main_menu                 = "Menu Principal" ;
  $Administration_menu       = "Menu administrativo" ;
  $Billing_functions         = "Funções de pagamento";
  $Database_maintenance      = "Manutenção da base de dados" ;
  $Patient_functions         = "Funções dos Pacientes" ;
  $Help_main_menu            = "Ajuda para o menu principal" ;
  $Logout_of                 = "Fazer o Logout de" ;
  $Quickjump                 = "Ir para" ;
  $User_level                = "Nível do utilizador" ;
  $User_description          = "Descrição do utilizador" ;
  $Call_in                   = "Chamada para";
  $Entry                     = "Entrada";
  // 19991006
  $Day_View                  = "Ver Dia (Calendário)";
  $Week_View                 = "Ver Semana (Calendário)";
?>
