<?php
  # ficheiro: ling/PT/manage.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Tradução por Cristina Bouça
  # Modificações por Cristina Bouça
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Attach_to_Guarantor           = "Attach para o supervisor";
  $Must_select_a_patient         = "tem que seleccionar um paciente.";
  $Select_Guarantor_to_Attach_to = "Seleccione um supervisor para fazer o Attach:";
  $detach                        = "Retirar";
  $Attach                        = "Attach";
  $Return_to_Patient_Management  = "Voltar à manutenção do paciente";
  $Attaching_Guarantor           = "Attaching do supervisor";
  $Detaching_current_dependants  = "Retirar as dependências";
  $lang_done                     = "feito.";
  $Manage_Patient                = "Manutenção do paciente";
  $Select_a_patient              = "Seleccione o paciente";
  $Patient_Information           = "Informação do paciente";
  $View_Manage                   = "Visualizar/Manter";
  $Prescriptions                 = "Prescrições";
  $Procedures                    = "Procedimentos";
  $Progress_Notes                = "Notas dos Progressos";
  $Reports_and_certificates      = "Relatórios e certificados";  // 19990813
  $Choose                        = "Escolha";                    // 19990813
  $Show_Dependants               = "Mostrar Dependentess";
  $Show_Guarantor                = "Mostrar Supervisor";
  $Last_Name                     = "Último Nome";
  $All                           = "Tudo";
  $Select_Another_Patient        = "Seleccione outro paciente";
    // 19990809
  $Appointments                  = "Apontamentos";
  $Book                          = "Livro";
  $Patient                       = "Paciente";
  $Show_Today                    = "Mostrar Hoje";
?>
