<?php
  # ficheiro: ling/PT/patient.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL, v2
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228



  $record_name                   = "Paciente";

  $Dependant                     = "Dependentes";
  $Patient                       = "Paciente";
  $Last_name                     = "Último Nome";
  $First_name                    = "Primeiro Nome";
  $Middle_name                   = "Nome do meio";
  $Date_of_birth                 = "Data de nascimento";
  $YMD                           = "A-M-D";
  $Gender                        = "Sexo";
  $NONE_SELECTED                 = "NENHUM SELECCIONADO";
  $Female                        = "feminino";
  $Male                          = "masculino";
  $Transgender                   = "transsexual";
  $Marital_status                = "Casamento Marietal";
  $Unknown                       = "desconhecido";
  $Single                        = "single";
  $Married                       = "casado";
  $Divorced                      = "divorciado";
  $Internal_practice_id          = "Prática Interna ID";
  $Address                       = "Morada";
  $Line                          = "Linha";
  $City                          = "Cidade";
  $State                         = "Concelho";
  $Zip_code                      = "Código Postal";
  $Country                       = "País";
  $Home_phone                    = "Telefone Casa";
  $Work_phone                    = "Telefone Trabalho";
  $Fax_number                    = "Número de Fax";
  $Email_address                 = "Endereço de Email";
  $Drivers_license               = "Drivers da Licença";
  $No_state                      = "Nenhum estado";
  $Referring_doctor              = "Doutor de referência";
  $Primary_care_physician        = "Tratamento Primário";
  $Other                         = "Outro";
  $Physician                     = "Cirurgião";
  $Type_of_billing               = "Tipo de pagamento"; 
  $Monthly_billing_on_acct       = "pagamento mensal na conta";
  $Statement_billing             = "estado do pagamento";
  $Charge_card_billing           = "alterar tipo de pagamento";
  $Monthly_budget_amount         = "Montante mensal";
  $In_house_doctor               = "Na casa do Doutor";
  $Primary_insurance             = "Primeira instância";
  $Secondary_insurance           = "Segunda instância";
  $Tertiary_insurance            = "Terceira instância";
  $Discount_percent_if_applic    = "Desconto % (se for aplicável)";
  $Self_insured                  = "assegurado";
  $Guarantor                     = "Supervisor";
  $Next_of_kin_information       = "Próxima informação";
  $Employed_presently            = "Empregado actualmente?";
  $UNKNOWN                       = "DESCONHECIDO";
  $Yes                           = "sim";
  $No                            = "não";
  $Adding_patient                = "Adicionando paciente";
  $ADDING                        = "Adicionando";
  $Query_result                  = "Resultado da pesquisa";
  $Query_string                  = "Pesquisa";
  $Actual_query_result           = "Resultado actual da pesquisa";    
  $Error                         = "ERRO";    
  $Return_to_the                 = "Voltar para";
  $Patient_menu                  = "Menu dos pacientes";
  $Main_menu                     = "Menu principal";
  $MODIFYING                     = "Modificando";
  $Please_use_the_MODIFY_form    = "Por favor use o menu MODIFICAR para MODIFICAR um código";
  $Result                        = "RESULTADO";
  $Book_an_appointment           = "Marque um apontamento";
  $Date                          = "Data";
  $Of_entry                      = "de entrada";
  $Of_last_mod                   = "da última alteração";
  $Update                        = "Actualizar";
  $Remove_changes                = "Apagar alterações";
  $Manage                        = "Manter";
  $Select_another                = "Seleccione outro";
  $Patients_meeting_criteria     = "Critério de encontro dos Pacientes";
  $Action                        = "Acção";
  $NEWDEP                        = "Nova dep";
  $DEPS                          = "DEP";
  $GUA                           = "GUA";
  $MANAGE                        = "MANTER";
  $No_patients_found_with_that   = "Não foram encontrados Pacientes na selecção feita";
  $PATIENTS                      = "Pacientes";
  $In_system                     = "Sem sistema";
  $No_patients                   = "Sem Pacientes";
  $Ppl                           = "Paciente(s)";
  $One                           = "Um";
  $By_name                       = "Por nome";
  $Patients_field_search         = "Campo de pesquisa de pacientes"; 
  $Social_security_number        = "Número de segurança social";
  $Patient_account_number        = "Número de contribuinte do paciente";
  $Show_all                      = "Mostrar Tudo";
  $Contains                      = "Contém";
  $Find                          = "encontrar";
  $Searching_for                 = "Procurando por";
  $Last_names                    = "Últimos Nomes";
  $All_Patients                  = "Todos os pacientes";
  $Dependants                    = "Dependentes";
    // 19990823
  $Separated                     = "separados";
    // 19990830
  $Call_In_Menu                  = "Menu de chamada";
    // 19990923
  $Current_Patient		 = "Paciente Actual"; 
  $CONTAINS			 = "contém";        
?>
