<?php
  # ficheiro: ling/PT/phy_avail_map.PT.inc
  # desc: mapa Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Mapa de Doutores disponíveis";

  $Must_specify_physician          = "Tem que especificar um Cirurgião!";
  $Absence_date_from               = "Alteração de disponíbilidade (Data)";
  $Absence_date_to                 = "Alteração (Para a Data)";
  $Time_beginning                  = "Início do tempo";
  $Time_ending                     = "Fim do tempo";
  // 19991005
  $lang_to                         = "para";
  $Comment                         = "Comentário";
  $Physician                       = "Cirurgião";
  $Availability                    = "Disponível";
?>
