<?php
  # ficheiro: ling/PT/phygroup.php3.PT.inc
  # desc: grupo de doutores Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Grupo de Doutores";

  $Physician_Group_Name               = "Nome do grupo de Doutores";
  $Default_Facility                   = "Inicial";
  $Group_Name                         = "Nome do grupo";
?>
