<?php
  # ficheiro: ling/PT/physician_day_view.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Physician_Daily_View                    = "Ver diário doutor";
  $back_one_day                            = "ant";
  $forward_one_day                         = "prox";
  $No_Physician_Selected                   = "Ninguém foi seleccionado"; 
  $Physician                               = "Doutor";
?>
