<?php
  # ficheiro: ling/PT/phystatus.php3.PT.inc
  # desc: physician status Português (PT) language file
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name               = "Status Doutor";

  $Status                    = "Status";
  $Update                    = "Actualizar";
  $Remove_Changes            = "Apagar alterações";
  $Abandon_Modification      = "Sair da modificação";
  $Modifying                 = "Modificando";
  $Done                      = "Feito";
  $Return_to_Previous_Menu   = "Voltar ao menu anterior";
  $Return_to_the_Main_Menu   = "Voltar para o menu principal";
  $Deleting                  = "Apagando";
  $Deleted                   = "Apagado";
  $RESULT                    = "RESULTADO";
  $Update_Delete_Another     = "Actualizar ou apagar outro";
  $Return_to                 = "Voltar para";
  $RETURN_TO_MENU            = "Voltar ao menu";
  $No_Record_Found           = "Nenhum registo foi encontrado";
?>
