<?php
  # ficheiro: ling/PT/physician.php3.PT.inc
  # desc: menu de manutenção Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com> 
  # lic : GPL
  # ver : 19991104
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Add_Physician                   = "Adicioanar Doutor"  ;
  $Last_name                       = "Último Nome"      ;
  $First_name                      = "Primeiro Nome"     ;
  $Title                           = "Título"          ;
  $Middle_Name                     = "Nome do meio"    ;
  $Practice_Name                   = "Nome da prática"  ;
  $Primary_Address_Line            = "Primeira morada"    ;
  $Primary_Address_City            = "Primeira Cidade"    ;
  $Primary_Address_State           = "Primeiro concelho"   ;
  $Primary_Address_Zip             = "Primeiro código postal"     ;
  $Primary_Address_Phone           = "Primeiro número de telefone"   ;
  $Primary_Address_Fax             = "Primeiro número de fax"     ;
  $Secondary_Address_Line          = "Segunda morada"  ;
  $Secondary_Address_City          = "Segunda cidade"  ;
  $Secondary_Address_State         = "Segundo concelho" ;
  $Secondary_Address_Zip           = "Segundo código postal"   ;
  $Secondary_Address_Phone         = "Segundo número de telefone" ;
  $Secondary_Address_Fax           = "Segundo número de fax"   ;
  $Email_Address                   = "Endereço de Email"           ;
  $Cellular_Phone                  = "Telémovel"          ;
  $BeeperPager                     = "Beeper ou Pager"     ;
  $UPIN_Number                     = "Número UPIN"         ;
  $Social_Security                 = "Segurança Social"     ;
  $Degree                          = "Grau"              ;
  $Specialty                       = "Especialidade"           ;
  $Internal_ID                     = "Número interno ID"         ;
  $Status                          = "Status"              ;
  $Reference                       = "Referência"           ;
  $Number_of_Referrals             = "Número de referências" ;
  $Primary_care_provider           = "Tratamento primário" ;
  $Referring                       = "Referência"           ;
  $NULL                            = "NULO"                ;
  $Number_of_Referrals             = "Número de referências" ;
  $Referral_Amount                 = "Total"     ;
  $S_charged                       = "\$ alterado"          ;
  $S_received                      = "\$ recebido"         ;
  $Add                             = "Adicionar"                 ;
  $Clear                           = "Limpar"               ;
  $Adding_Physician                = "Adicionar Doutor"    ;
  $Adding                          = "Adicionando"              ;
  $Done                            = "Feito"                ;
  $ERROR                           = "ERRO"               ;
  $Physician                       = "Doutor"           ;
  $Modify_Physician                = "Modificando Doutor"    ;
  $Please_use_the_MODIFY_form_to_MODIFY_someone = "Por favor use o  menu MODIFICAR para MODIFICAR alguém" ;
  $Return_to_the_Main_Menu         = "Voltar ao menu principal" ;
  $Update                          = "Actualizar"                  ;
  $Abandon_Modification            = "Abandonar a Modificação"    ;
  $Modifying_Physician             = "Modificando Doutor"     ;
  $Modifying                       = "Modificando"               ;
  $Deleting_Physician              = "Apagando Doutor"      ;
  $RESULT                          = "RESULTADO"                  ;
  $Delete_Another                  = "Apagar outro"          ;
  $Physician_Display               = "Mostrar Doutor"       ;
  $You_must_specify_an_id          = "Tem que especificar um id"  ;
  $Return_to_the_Physician_Menu    = "Voltar ao menu do doutor" ;
  $NONE_SELECTED                   = "Não foi nada seleccionado"           ;
  $Physicians                      = "Doutores"              ;
  $Last_Name                       = "Último Nome"               ;
  $First_Name                      = "Primeiro Nome"              ;
  $Degrees                         = "Grau"                 ;
  $Action                          = "Acção"                  ;
  $VIEW                            = "VER"                    ;
  $MOD                             = "MOD"                     ;
  $DEL                             = "APAG"                     ;
  $No_physicians_found_with_that_criteria = "Não foi encontrado nenhum doutor com esse critério de pesquisa" ;



?>