<?php
  # ficheiro: ling/PT/physician_week_view.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $Physician_Weekly_View                   = "Relatório Semanal";
  $back_one_week                           = "ant";
  $forward_one_week                        = "prox";
  $No_Physician_Selected                   = "Ninguém foi seleccionado"; 
  $Physician                               = "Doutor";
?>
