<?php
  # ficheiro: ling/PT/progress_notes.php3.PT.inc
  # lic : GPL
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name                  = "Notas dos progressos";
  $Module                       = "Módulo";
  $ERROR                        = "ERRO";
  $Must_Specify_A_Patient       = "Tem que especificar um paciente!";
  $Entry                        = "Introduza";
  $Manage_Patient               = "Manutenção do Paciente";
  $View_Modify                  = "Ver/Modificar";
  $Applicable_Date              = "Data aplicável";

    // the actual progress parts (with underlines)
  $Subjective                   = "<U>S</U>ubjectivo";
  $Objective                    = "<U>O</U>bjectivo";
  $Assessment                   = "<U>A</U>ceder";
  $Plan                         = "<U>P</U>lano";
  $Interval                     = "<U>I</U>ntervalo";
  $Education                    = "<U>E</U>ducação";
  $Prescription                 = "p<U>R</U>escrição";

  $Add                          = "Adicionar";
  $Clear                        = "Limpar";
  $Abort_Addition               = "Sair da introdução";
  $Adding                       = "Adicionando";
  $Done                         = "feito";
  $FAILED                       = "FALHOU";
  $Must_Call_With_Patient_ID    = "Tem que chamar esta função com um ".
                                  "paciente seleccionado.";
  $Modify                       = "Modificar";
  $Change                       = "Alterare";
  $Restore                      = "Actualizar";
  $Modifying                    = "Modificando";
  $View                         = "Ver";
  $Menu                         = "Menu";
  $Specify_Notes_to_Display     = "Tem que especificae as notas do progresso para ".
                                  "serem mostradas.";
  $Modify_Notes                 = "Modificar notas";
  $Patient                      = "Paciente";
  $This_Patient_Has_No_Notes    = "Este paciente não tem notas para a data.";
  $Existing                     = "Existente";
?>
