<?php
  # ficheiro: ling/PT/roomequip.php3.PT.inc
  # desc: equipamento da sala Português (PT)
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name                       = "Equipamento da sala";
  $Name_of_Equipment                 = "Nome do equipamento";
  $Description                       = "Descrição";
  $Equipment                         = "Equipamento";
?>
