<?php
  # ficheiro: ling/PT/room.php3.PT.inc
  # desc: sala (localização) Português (PT)
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Equipamento da sala";

  $Room_Name                      = "Nome da sala";
  $Location                       = "Localização";
  $Room_Description               = "Descrição da sala";
  $Default_Physician              = "Doutor por defeito";
  $Surgery_Equipped               = "Equipada para Cirurgia?";
  $Is_Booking_Enabled             = "O Booking está activo?";
  $IP_Address                     = "Endereço IP ";
  $For_Future_Use                 = "para uso futuro";
  $For_Scheduling                 = "para horário";
  $Description                    = "Descrição";
?>
