<?php
  # ficheiro: ling/PT/Rx.php3.PT.inc
  # desc: Módulo de prescrição Português (PT) 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Prescrição";

  $Must_Have_Patient_For_Prescriptions =
    "Tem que ter um paciente para usar o módulo de prescrição.";
  $No_Access_To_This_Patient           =
    "Você não tem acesso a este paciente' registo.";
  $Display                             = "Mostrar";
  $Patient                             = "Paciente";
  $Drug                                = "Remédio";
  $Dosage                              = "Quantidade";
  $Starting_Date                       = "data início";
  $In_Days                             = "em dias";
  $Infinite                            = "0 = infinito";
  $Refills                             = "Contra Indicações";
  $Substitution                        = "Substituição";
  $May_Not_Substitute                  = "não deve substituir";
  $May_Substitute                      = "pode substituir";
  $Manage_Prescriptions                = "Controlar prescrições";
  // 19991002
  $Duration                            = "Duração";
?>
