<?php
  # ficheiro: ling/PT/select_printer.php3.PT.inc
  # desc: Seleccionar impressora Português (PT)
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Manutenção das impressoras a seleccionar" ;

  $Selectable_Printer    = "Impressoras a seleccionar"   ;
  $Printer_Name          = "Nome da impressora"         ;
  $Printer_Host          = "Servidor de impressão"         ;
  $Access_Level          = "Nível de acesso"         ;
  $Description           = "Descrição"          ;
  $Add                   = "Adicionar"                  ;
  $Clear                 = "Limpar"                ;
  $Adding                = "Adicionando"               ;
  $Done                  = "Feito"                 ;
  $ERROR                 = "ERRO"                ;
  $Return_to             = "Voltar para"            ;
  $Menu                  = "Menu"                 ;
  $Modify                = "Modificar"               ;
  $Please_use_MODIFY     = "Por favor use o menu MODIFICAR para MODIFICAR um" ;
  $Return_to_the_Main_Menu = "Voltar ao menu principal" ;
  $RESULT                = "RESULTADO"               ;
  $Abandon_Addition      = "Abandonar Introdução"     ;
  $Update                = "Actualizar"               ;
  $Remove_Changes        = "Apagar alterações"       ;
  $Abandon_Modification  = "Abandonar Modificações" ;
  $Modifying             = "Modificando"            ;
  $Deleting              = "Apagando"             ;
  $Deleted               = "Apagado"              ;
  $Update_Delete_Another = "Actualizar ou apagar outro" ;
  $Export                = "Exportar"               ;
  $Exporting_data        = "Exportando dados"       ;
  $Action                = "Acção"               ;
  $Printer               = "Impressora"              ;
  $Host                  = "Servidor"                 ;
  $MOD                   = "MOD"                  ;
  $DEL                   = "APAG"                  ;
  $No_Record_Found       = "Nenhum registo encontrado"      ;
  $Current_Contents      = "registo actual"      ;
  $For_Reference         = "Para referência"        ;

?>
