<?php
  # ficheiro: ling/PT/simplerep.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Relatórios";

  $Add                         = "Adicionar";
  $Clear                       = "Limpar"; 
  $Label                       = "Nome";
  $Category                    = "Categoria";
  $Text                        = "Texto";
  $Abandon_Addition            = "Abandonar introdução";
  $Adding                      = "Adicionando";
  $Return_to                   = "Voltar para";
  $Modify                      = "Modificar";
  $Please_use_MODIFY           = "Por favor use o menu MODIFICAR para MODIFICAR um";
  $Return_to_the_Main_Menu     = "Voltar ao menu principal";
  $Update                      = "Actualizar";
  $Remove_Changes              = "Apagar alterações";
  $Abandon_Modification        = "Abandonar Modificações";
  $Modifying                   = "Modificando";
  $Done                        = "feito";
  $ERROR                       = "ERRO";
  $Menu                        = "Menu";
  $Deleting                    = "Apagando";
  $Deleted                     = "apagado";
  $Update_Delete_Another       = "Actualizar/Apagar outro";
  $Must_Have_Patient_to_Make_Reports =
    "You must have a patient to make reports!";
  $Choose_Report_for_Patient   = "Escolha o relatório para o Paciente";
  $Patient                     = "Paciente";
  $Manage_Patient              = "Manutenção do Paciente";
  $Action                      = "Acção";
  $Mr                          = "Sr";   // 19990926
  $Mrs                         = "Srª";
  $Report                      = "Relatório";
  $Physician                   = "Doutor";
  $Facility                    = "Facilidade";
  $Proceeding                  = "procedimento";  //  19990927
  $Proceed                     = "Procedeu";
  $Please_choose               = "Por favor seleccione alguma coisa para cada";  // 19990927
  $Before                      = "antes";
  $Return_to_report_selection  = "Voltar à selecção de relatórios"; // 19990928
  $Destinatary_is              = "Destinatário é";
  $Delivery_Method             = "Método de deliveração";
  $NONE_SELECTED               = "Não foi seleccionado nada";
  $The_Patient                 = "O Paciente";
  $A_Physician                 = "Um Doutor";
  $An_Insurer                  = "Um Enfermeiro";
  $Other                       = "Outro";
  $Printer                     = "Impressora";
  $Fax                         = "Fax"; 
  $E_mail                      = "E-mail";
  $Edit_report_for_patient     = "Alterar o report para o paciente";
  $Phone                       = "Telefone";  //19991005
  $Datequalif                  = "";
  $Help_for_simple_reports     = "Ajuda para relatórios";
  $Edit_add_simple_reports     = "Adicionar ou alterar Relatórios";  // 19991007
  $Patients_primary_insurer    = "Pacientes primeira acção";   // 19991008
  $Patients_secundary_insurer  = "Pacientes segunda acção";
  $Patients_tertiary_insurer   = "Pacientes terceira acção";
  $Select_from_contact_list    = "Seleccione da lista de contactos";
  $Patients_primary_employer   = "Pacientes primeiro emprego";
  $Patients_secundary_employer = "Pacientes segundo emprego";
  $No_delivery_method_selected = "Nenhum método de deliveração foi seleccionado!"; // 19991008
  $Print                       = "Imprimir";
  $To                          = "Para";                               // 19991009
  $Patient_has_no_fax          = "Este número de fax não é válido";
  $Send                        = "Enviado";
  $Patient_has_no_email        = "Este paciente não tem e-mail";
  $A_physician_must_sign_his_own_name = "Um Doutor tem que assinar com o seu nome";
  $Verification_Key            = "Chave de verificação";
  $Suppress_headers            = "Tirar cabeçalho";
  $Show_full_titles            = "Mostrar Título";
  $Mailed                      = "Enviado"   ;
  $From                        = "Para"     ;
  $Copy_to                     = "Copiar para"  ;
  $Subject                     = "Assunto"  ;
  $Male                        = "Masculino"     ;
  $Female                      = "Feminino"   ;
  $Adult                       = "Adulto"    ;
  $Child                       = "Criança"    ;
  $Return_to_reports_menu      = "Voltar ao menu de Relatórios";  


?>
