<?php
  # ficheiro: ling/PT/simplerep_lout.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228



  $Verification_Key            = "Chave de verificação"      ;
  $To                          = "Para"                    ;
  $Generate_lout_for           = "Generando para"     ;
  $Sr_page                     = "Página"                  ;
  $From                        = "De"                  ;
  $Of                          = "Com"                    ;
  $Page                        = "Página"                  ;
  $Return_to_report_selection  = "Voltar à selecção de relatórios" ;


?>