<?php
  # ficheiro: ling/PT/specialties.php3.PT.inc 
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Especialidades";

  $Specialty_Name                        = "Nome da especialidade";
  $Specialty_Description                 = "Descrição da especialidade";
  $Name                                  = "Nome";
  $Description                           = "Descrição";
?>
