<?php
  # ficheiro: ling/PT/TEMPLATE.PT.inc  
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  // language variables always have underscores and
  //  are either all caps or start with a capital
  //  letter -- jeff

  // you also must have the $record_name variable for ancillary dbs:
  // $record_name = "Equipamento da sala";
  // $Username = "Nome do utilizador";
  // $Password = "Password";
  // $Enter_the_database = "Insira a Base de dados";
?>
