<?php
  # ficheiro: ling/PT/tos.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name = "Tipo de serviço (TS)";

  $Type_of_Service_Name        = "Nome do tipo de serviço";
  $Type_of_Service_Description = "Descrição do tipo de serviço";
  // 19991013
  $Name                        = "Nome";
  $Description                 = "Descrição";
?>
