<?php
  # file: lang/PT/user.php3.PT.inc
  # code: jeff b <jeff@univrel.pr.uconn.edu>
  # lic : GPL
  # Translation by Eduardo SH <edu@icarus.com.br>

  $record_name                             = "Usuário";  

  $Add                                     = "Adicionar";
  $Adding                                  = "Adicionando";
  $Modify                                  = "Modificar" ;
  $Modifying                               = "Modificando" ;
  $User_name                               = "Usuário" ;
  $Password                                = "Senha" ;
  $Verify                                  = "verificar" ;
  $Description                             = "Descrição" ;
  $Physician_group                         = "Grupo de Médicos" ;
  $User_level                              = "Nível de acceso" ;
  $Locked_out                              = "!!! Excluido !!!" ;
  $Undefined                               = "INDEFINIDO" ;
  $Delete_privs                            = "Pode Excluir" ;
  $Superuser                               = "SuperUsuario/Admin." ;
  $Update                                  = "Atualizar" ;
  $Remove_changes                          = "Excluir mudanças" ;
  $Abandon_addition                        = "Abandonar a operação" ; # Just say no ;-)
  $Passwords_must_match                    = "Senhas não conferem!" ;
  $Done                                    = "Terminado" ;
  $Go_back_to_user_menu                    = "Retornar ao menu de usuários" ;
  $Please_use_the_modify_form              = "Por favor use o formulário MODIFICAR para mudanças" ;
  $Return_to_main_menu                     = "Retornar para o menu principal" ;
  $Result                                  = "RESULTADO" ;
  $Error                                   = "ERRO" ;
  $You_cannot_modify_root                  = "Você não pode  modificar o superusuario" ;
  $You_cannot_delete_root                  = "Você não pode remover o superusuario" ;
  $Query_result                            = "Resultado da pesquisa" ;
  $Query_string                            = "variável da pesquisa" ;
  $Actual_query_result                     = "Resultado atual da pesquisa" ;
  $Deleting                                = "Excluindo" ;
  $Delete                                  = "Excluir" ;
  $Another                                 = "Outro" ;
  $Maintenance                             = "Manutenção" ;
  $Action                                  = "Ação" ;
  $No                                      = "Nada" ;
  $Found_with_that_criteria                = "encontrado com estes critérios" ;
  $Try_Again                               = "Tentar novamente";     //19990813
  $Authorized_facilities                   = "Locais autorizados";
  $Authorized_physicians                   = "Médicos autorizados";
  $Authorized_phy_groups                   = "Grupos de médicos autorizados"; 

?>
