<?php
  # ficheiro: ling/PT/user.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228
  # mod : 20000529 adam b

  $record_name                         = "Utilizador";

  $phrase[User_name]            = "Nome do utilizador" ;
  $phrase[Password]             = "Password" ;
  $phrase[Verify]               = "verificação" ;
  $phrase[Description]          = "Descrição" ;
  $phrase[Physician_group]      = "Grupo" ;
  $phrase[User_level]           = "Nível do utilizador" ;
  $phrase[Locked_out]           = "!!! Trancado !!!" ;
  $phrase[Undefined]            = "Não definido" ;
  $phrase[Delete_privs]         = "Apagar" ;
  $phrase[Superuser]            = "SuperUtilizador/Admin." ;
  $phrase[Abandon_addition]     = "Abandonar esta operação" ; # Just say no ;-)
  $phrase[Passwords_must_match] = "Passwords devem estar correctas!" ;
  $phrase[Go_back_to_user_menu] = "Voltar ao menu dos utilizadores" ;
  
  $phrase[Please_use_the_modify_form]
                            = "Por favor use o menu MODIFICAR para fazer isto" ;
  $phrase[Result]                   = "RESULTADO" ;
  $phrase[You_cannot_modify_root]   = "Não pode modificar o superUtilizador" ;
  $phrase[You_cannot_delete_root]   = "Não pode apagar o superUtilizador" ;
  $phrase[Query_result]             = "Resultado da pesquisa" ;
  $phrase[Query_string]             = "Pesquisa" ;
  $phrase[Actual_query_result]      = "Resultado da pesquisa actual" ;
  $phrase[Another]                  = "Outro" ;
  $phrase[Maintenance]              = "Manutenção" ;
  $phrase[Action]                   = "Acção" ;
  $phrase[No]                       = "Não" ;
  $phrase[Found_with_that_criteria] = "encontrado com a pesquisa feita" ;
  $phrase[Try_Again]                = "Tente novamente";
  $phrase[Authorized_facilities]    = "Facilidades autorizadas";
  $phrase[Authorized_physicians]    = "Autorizados Doutores";
  $phrase[Authorized_phy_groups]    = "Autorizados Grupos";
    // 19990909
  $phrase[User_type]            = "Tipo de utilizador";
  $phrase[Physician]            = "Doutor";
  $phrase[Miscellaneous]        = "Muitod";
    //19990927 - mark l
  $phrase[Update]               = "Actualizar";
  $phrase[Remove_changes]       = "Apagar alterações";
    // 19990929
  $phrase[Actual_physician]     = "Doutor Actual";
?>
