<?php
  # ficheiro: ling/PT/user.php3.PT.inc
  # código: Cristina Bouça <bugsoft@bug-software.com>
  # lic : GPL
  # ver : 20000228
  # Translation : Cristina Bouça <bugsoft@bug-software.com>  
  # lic : GPL
  # ver : 20000228


  $record_name                         = "Utilizador";
  $User_name                           = "Nome do utilizador" ;
  $Password                            = "Password" ;
  $Verify                              = "verificação" ;
  $Description                         = "Descrição" ;
  $Physician_group                     = "Grupo" ;
  $User_level                          = "Nível do utilizador" ;
  $Locked_out                          = "!!! Trancado !!!" ;
  $Undefined                           = "Não definido" ;
  $Delete_privs                        = "Apagar" ;
  $Superuser                           = "SuperUtilizador/Admin." ;
  $Abandon_addition                    = "Abandonar esta operação" ; # Just say no ;-)
  $Passwords_must_match                = "Passwords devem estar correctas!" ;
  $Go_back_to_user_menu                = "Voltar ao menu dos utilizadores" ;
  
  $Please_use_the_modify_form          = "Por favor use o menu MODIFICAR para fazer isto" ;
  $Result                              = "RESULTADO" ;
  $You_cannot_modify_root              = "Não pode modificar o superUtilizador" ;
  $You_cannot_delete_root              = "Não pode apagar o superUtilizador" ;
  $Query_result                        = "Resultado da pesquisa" ;
  $Query_string                        = "Pesquisa" ;
  $Actual_query_result                 = "Resultado da pesquisa actual" ;
  $Another                             = "Outro" ;
  $Maintenance                         = "Manutenção" ;
  $Action                              = "Acção" ;
  $No                                  = "Não" ;
  $Found_with_that_criteria            = "encontrado com a pesquisa feita" ;
  $Try_Again                           = "Tente novamente";
  $Authorized_facilities               = "Facilidades autorizadas";
  $Authorized_physicians               = "Autorizados Doutores";
  $Authorized_phy_groups               = "Autorizados Grupos";
    // 19990909
  $User_type                           = "Tipo de utilizador";
  $Physician                           = "Doutor";
  $Miscellaneous                       = "Muitod";
    //19990927 - mark l
  $Update                              = "Actualizar";
  $Remove_changes                      = "Apagar alterações";
    // 19990929
  $Actual_physician                    = "Doutor Actual";
?>
