#! /bin/sh -e
# $Id$
#
# Authors:
#      Jeff Buchbinder <jeff@freemedsoftware.org>
#
# FreeMED Electronic Medical Record and Practice Management System
# Copyright (C) 1999-2011 FreeMED Software Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#	Post-install directives for FreeMED package
#

# Patch PHP ini file to have more than 8M per process
if [ -f /etc/php5/apache2/php.ini ]; do
	perl -pi -e "s|8M|128M|;" /etc/php5/apache2/php.ini
fi

# Apache user has to own freemed
echo -n "Updating ownership of freemed to webserver user ... "
chown -Rf www-data:www-data /usr/share/freemed 
echo "[done]"

# Change writeable permissions for data/, img/store, etc
echo -n "Updating permissions ... "
chmod -Rf a+w /usr/share/freemed/data/{cache,backup}
echo "[done]"

# Attempt to create freemed mysql database ... will have no password if
# it has just been installed. Do not run if there is already a freemed
# version installed.
if [ ! -d /var/lib/mysql/freemed ]; then \ 
	echo "Attempting to create freemed database (enter password, or enter if none) ... "; \
	X=$(mysqladmin -u root -p create freemed 2>&1); \
	echo "[done]"; \
fi

# Restart apache ...
echo "Restarting apache to reload configuration files ... "
if [ -f /etc/init.d/apache2 ]; then \
	/etc/init.d/apache2 restart; \
fi

#DEBHELPER#

exit 0
