<?php
	// $Id$
	// Agata Reports configuration file

$agataConfig['general']['Precision']    = '2';
$agataConfig['general']['ThouSep']      = '.';
$agataConfig['general']['DecSep']       = ',';
$agataConfig['general']['DateFmt']      = 'd/m/Y';
$agataConfig['general']['DateTimeFmt']  = 'd/m/Y';
$agataConfig['general']['Delimiter']    = ';';
$agataConfig['general']['AgataDir']     = dirname(__FILE__);
$agataConfig['general']['OutputDir']    = '/tmp';
$agataConfig['general']['SqlDir']       = dirname(__FILE__).'/report/';

$agataConfig['ps']['Orientation']       = 'Landscape';
$agataConfig['ps']['PsLineLen']         = '800';
$agataConfig['ps']['ColorLines']        = '1';

$agataConfig['pdf']['Orientation']      = 'Landscape';
$agataConfig['pdf']['CellSpacing']      = '1';
$agataConfig['pdf']['Border']           = '0';
$agataConfig['pdf']['BgColor']          = '#010101';
$agataConfig['pdf']['TitleFont']        = 'Arial-B-14';
$agataConfig['pdf']['DataFont']         = 'Arial--11';
$agataConfig['pdf']['TotalFont']        = 'Courier-B-12';
$agataConfig['pdf']['GroupFont']        = 'Helvetica-B-12';
$agataConfig['pdf']['ColumnFont']       = 'Helvetica-B-11';
$agataConfig['pdf']['TitleColor']       = '#898bb3';
$agataConfig['pdf']['TitleBgColor']     = '#ffffff';
$agataConfig['pdf']['DataColor']        = '#120a92';
$agataConfig['pdf']['DataBgColor']      = '#fff7ec';
$agataConfig['pdf']['TotalColor']       = '#ff0f0f';
$agataConfig['pdf']['TotalBgColor']     = '#d4d4d4';
$agataConfig['pdf']['GroupColor']       = '#ffffff';
$agataConfig['pdf']['GroupBgColor']     = '#898bb3';
$agataConfig['pdf']['ColumnColor']      = '#010101';
$agataConfig['pdf']['ColumnBgColor']    = '#d4d4d4';
$agataConfig['pdf']['ColorLines']       = '1';

$agataConfig['html']['CellSpacing']     = '1';
$agataConfig['html']['CellPadding']     = '4';
$agataConfig['html']['Align']           = 'center';
$agataConfig['html']['Width']           = '100%';
$agataConfig['html']['Border']          = '0';
$agataConfig['html']['BgColor']         = '#ffffff';
$agataConfig['html']['TitleFont']       = 'Arial-B-7';
$agataConfig['html']['DataFont']        = 'Helvetica--3';
$agataConfig['html']['TotalFont']       = 'Courier-B-4';
$agataConfig['html']['GroupFont']       = 'Helvetica-I-4';
$agataConfig['html']['ColumnFont']      = 'Helvetica-B-3';
$agataConfig['html']['TitleColor']      = '#01049c';
$agataConfig['html']['TitleBgColor']    = '#ffffff';
$agataConfig['html']['DataColor']       = '#120a92';
$agataConfig['html']['DataBgColor']     = '#fff7ec';
$agataConfig['html']['TotalColor']      = '#ff0f0f';
$agataConfig['html']['TotalBgColor']    = '#d4d4d4';
$agataConfig['html']['GroupColor']      = '#018303';
$agataConfig['html']['GroupBgColor']    = '#ffffff';
$agataConfig['html']['ColumnColor']     = '#010101';
$agataConfig['html']['ColumnBgColor']   = '#d4d4d4';

$agataConfig['graph']['BorderColor']    = '#000000';
$agataConfig['graph']['FontColor']      = '#000000';

$agataConfig['dia']['Levels']           = '2';
$agataConfig['dia']['ShowLines']        = '1';
$agataConfig['dia']['LineDistance']     = '0.3';
$agataConfig['dia']['ColumnDistance']   = '26';
$agataConfig['dia']['LevelDistance']    = '14';
$agataConfig['dia']['TableOffSet']      = '8';

$agataConfig['app']['PsSoft']           = '';
$agataConfig['app']['PdfSoft']          = '';
$agataConfig['app']['TxtSoft']          = '';
$agataConfig['app']['BrowserSoft']      = '';
$agataConfig['app']['SpreadSoft']       = '';
$agataConfig['app']['DiaSoft']          = '';
$agataConfig['app']['XmlSoft']          = '';

$agataConfig['xml']['ReportTag']        = '<relatorio>';
$agataConfig['xml']['TitleTag']         = '<titulo>';
$agataConfig['xml']['HeaderTag']        = '<cabecalho>';
$agataConfig['xml']['HeaderRow']        = '<linha tipo="header">';
$agataConfig['xml']['HeaderCol']        = '<coluna tipo="header" numero="$colnum"> $Column </coluna>';
$agataConfig['xml']['DataTag']          = '<campos>';
$agataConfig['xml']['DataRow']          = '<linha tipo="data">';
$agataConfig['xml']['DataCol']          = '<coluna tipo="data" align="$align" colnum="$colnum"> $QueryCell </coluna>';
$agataConfig['xml']['FooterTag']        = '<rodape>';
$agataConfig['xml']['TotalRow']         = '<linha tipo="total">';
$agataConfig['xml']['TotalCol']         = '<coluna tipo="total" formula="$formula" colnum="$colnum"> $Value </coluna>';
$agataConfig['xml']['GroupTag']         = '<grupo rotulo="$GroupLabel">';

$aDescription['PsSoft'] = 'Viewer for PostScript';
$aDescription['PdfSoft'] = 'Viewer for PDF';
$aDescription['TxtSoft'] = 'Viewer for Text Files';
$aDescription['XmlSoft'] = 'Viewer for XML Files';
$aDescription['DiaSoft'] = 'Viewer for Diagrams';
$aDescription['BrowserSoft'] = 'Browser';
$aDescription['SpreadSoft'] = 'Spread Sheet';
$aDescription['Precision'] = 'Precision';
$aDescription['ThouSep'] = 'Thousand Separator';
$aDescription['DecSep'] = 'Decimal Separator';
$aDescription['DateFmt'] = 'Date Format';
$aDescription['DateTimeFmt'] = 'DateTime Format';
$aDescription['Orientation'] = 'Orientation';
$aDescription['PsLineLen'] = 'PostScript Line Lenght';
$aDescription['CellSpacing'] = 'Spacing between cells';
$aDescription['CellPadding'] = 'Spacing within cells';
$aDescription['Align'] = 'Table Alignment';
$aDescription['Width'] = 'Table Width';
$aDescription['Border'] = 'Table Border';
$aDescription['BgColor'] = 'Table Background Color';
$aDescription['TitleFont'] = 'Title Font';
$aDescription['TitleColor'] = 'Title Color';
$aDescription['TitleBgColor'] = 'Title Background Color';
$aDescription['DataFont'] = 'Data Font';
$aDescription['DataColor'] = 'Data Color';
$aDescription['DataBgColor'] = 'Data Background Color';
$aDescription['TotalFont'] = 'Total Font';
$aDescription['TotalColor'] = 'Total Color';
$aDescription['TotalBgColor'] = 'Total Background Color';
$aDescription['GroupFont'] = 'Group Font';
$aDescription['GroupColor'] = 'Group Color';
$aDescription['GroupBgColor'] = 'Group Background Color';
$aDescription['ColumnFont'] = 'Column Font';
$aDescription['ColumnColor'] = 'Column Color';
$aDescription['ColumnBgColor'] = 'Column Background Color';
$aDescription['Delimiter'] = 'CSV Delimiter';
$aDescription['BorderColor'] = 'Border Color';
$aDescription['FontColor'] = 'Font Color';
$aDescription['AgataDir'] = 'Agata Directory';
$aDescription['OutputDir'] = 'Output Directory';
$aDescription['SqlDir'] = 'SQL Directory';
$aDescription['MergeDir'] = 'Merged Documents Directory';
$aDescription['EisDir'] = 'Graphics Directory';
$aDescription['LabelDir'] = 'Labels Directory';
$aDescription['ColorLines'] = 'Differentiate lines by color';
$aDescription['Levels'] = 'Number of rows in Diagrams';
$aDescription['ShowLines'] = 'Show link lines';
$aDescription['LineDistance'] = 'Distance Between Lines';
$aDescription['ColumnDistance'] = 'Distance Between Columns';
$aDescription['LevelDistance'] = 'Distance Between Levels';
$aDescription['TableOffSet'] = 'Table OffSet';
$aDescription['ReportTag'] = 'Report tag';
$aDescription['TitleTag'] = 'Title tag';
$aDescription['HeaderTag'] = 'Header tag';
$aDescription['HeaderRow'] = 'Header-row tag';
$aDescription['HeaderCol'] = 'Header-column tag';
$aDescription['DataTag'] = 'Data tag';
$aDescription['DataRow'] = 'Data-row tag';
$aDescription['DataCol'] = 'Data-column tag';
$aDescription['FooterTag'] = 'Footer tag';
$aDescription['TotalRow'] = 'Total-row tag';
$aDescription['TotalCol'] = 'Total-column tag';
$aDescription['GroupTag'] = 'Group tag';
?>
