<?php
	// $Id$

/***********************************************************/
/* Classe de traducoes                                     */
/* Linguagem PHP-GTK                                       */
/* Autor: Pablo Dall'Oglio                                 */
/* Última ateração em 19 Outubro 2001 por Pablo            */
/*                                                         */
/* History:                                                */
/*   10/24/2001  Thomas S. - Some improvements             */
/*               german messages, positional parameters    */
/*               and default instantiation                 */
/*               Bruno Depero - Italian Translation        */
/*               Christian Etuy - French Translation       */
/*                                                         */
/*   20/11/2002  Lucas Di Pentima - Spanish Translation    */
/*                                                         */
/***********************************************************/

/***********************************************************/
/* Classe de Traducoes                                     */
/***********************************************************/

class Trans
{
  //
  //  default spanish messages
  //

  var $messages = array(

    'es' => array(
        'Tablas',
        'Nombre de campos',
        'Selección',
        'Enlaces',
        'Restricciones',
        'Autor',
        'Ejecutar consulta',
        'Exportar TXT',
        'Exportar PS',
        'Cargar SQL',
        'Guardar SQL',
        'Cerarr ventana',
        'Bloque',
        'Contenido',
        'Nombre de tabla',
        'Tablas requeridas',
        'Departamento IT',
        'Desarrollo por',
        'Campos de la tabla seleccionada',
        'Por favor, seleccione un campo',
        'Orden ascendente',
        'Orden descendente',
        'Limpiar selección',
        'Limpiar ordenación',
        'Promedio',
        'Mínimo',
        'Máximo',
        'Agrupar por Select',
        'Abrir archivo SQL',
        'Guardar como archivo SQL',
        'Guardar como archivo PS',
	'Guardar como archivo PDF',
        'Guardar como archivo TXT',
	'Guardar como archivo HTML',
	'Guardar como archivo XML',
	'Guardar como archivo CSV',
        'Expresión',
        'Por favor ingrese una expresión',
        'Limpiar cláusula Where',
        'Resultado de la consulta',
        'Error de la consulta',
        'Marcar las tablas a las cuales aplicar la selección',
        'Tipo de selección del campo',
        'Enlazar tablas',
        'Reglas y restricciones del Select',
        'Algunos datos sobre el desarrollo',
        'Error inesperado, causa desconocida',
        'Espere un momento.',
        'Mensaje',
        'Cerrar',
        'Pregunta',
        'Ingrese el nombre del reporte',
        'No es posible conectarse a la base de datos',
        'Error de archivo',
	'Hacer clic en una línea para editar su contenido',
        'Agregar',
        'Editar',
        'Eliminar',
        'Limpiar',
        'Edición de lista',
        'Nuevo ítem',
        'Editar ítem',

        'Arriba',
        'Abajo',
        'Escribir',
        'Configuración de la conexión a la base de datos',
        'Dirección IP de la base de datos',
        'Nombre de la base de datos',
        'Nombre de usuario',
        'Contraseña',
        'Lenguaje',
        'Tipo de base de datos',
        'Visor para PostScript',
	'Visor para PDF',
        'Visor para archivos de texto',
        'Visor para archivos XML',
	'Mezclar con documento',
        'Elegir documento',
        'Vea también el archivo THANKS',
        'Sistema de ayuda',
        'Cargado desde config.php',
        'Herramienta de mezclado',
        'Mezclar',
        'Cargar archivo',
        'Guardar archivo',
        'Mezclar a PS',
        'Nuevo archivo PS',
        'Nuevo archivo TXT',
        'Tipografías',
        'Controles especiales',
        'Altura de línea',
        'Copyright',
        'Número de línea',
        'Número de página',
        'Imprimir',
	'Por favor ingrese las líneas y las tipografías en diferentes renglones',
	'No controla los cortes de línea automáticamente',
        'Línea comentada',
        'Espacio de línea',
	'Por favor cargue un archivo SQL en la pantalla principal',
        'Párrafo',
        'Spaniard', // FIXME: what's this?
        'Registrado',
        'Sesión de subconsulta',
        'Página',
        'Fin de subconsulta',
        'Ayuda: Subconsultas',
        'Debe ingresar una sesión de subconsulta',
	'Ingresar $subcampo1, $subcampo2, etc., todo en una línea',
	'Las variables de arriba serán convertidas a resultados de la subconsulta',
	'La línea con las variables de la subconsulta será replicada de acuerdo con los resultados de la subconsulta',
        'Ingresar fin de subconsulta',
	
	'Configuración',
	'Precisión',
	'Separador de miles',
	'Separador decimal',
	'Formato de fecha',
	'Formato FechaHora',
	'Configuración del reporte',
	'Aquí puede escribir su propio SELECT',
	'Orientación',
	'Longitud de línea (PostScript)',
	'Reportes guardados',
	'Consultas guardadas',
	'Herramientas',
	'Crear diagrama',
	'Limpiar consulta',
	'Ingresar el nombre del diagrama',
	'Visor para diagramas',
	'Tema',
	'Generador de etiquetas',
	'Etiquetas guardadas',
	'Márgen izquierdo',
	'Márgen superior',
	'Seleccione alguna tabla',
	'Primero debe construir una consulta SQL',
	'Importar',
	'Importar DBF',
	'Importar CSV',
	'Soporte para DBASE no habilitado',
	'No es un archivo DBF',
	'Columnas DBF',
	'Columnas destino',
	'Generar gráfico',
	'Título',
	'Ayuda',
	'Introducción',
	'Consultas',
	'Por líneas',
	'Por columnas',
	'Generar',
	'Gráfico de líneas',
	'Gráfico de barras',
	'Gráfico de torta',
	'Extensión no cargada',
	'Resultado',
	'No hay datos numéricos en la consulta',
	'Dimensión',
	'Planilla de cálculos',
	'Dimensiones demasiado pequeñas',
	'Delimitador',
	'Color de la tipografía',
	'Color del borde',
	'Espere un momento',
	'Seleccione los campos de ambas columnas',
	'Resultado',
	'Debe enlazar las columnas',
	'No hay columnas para visualizar',
	'Gráfico+datos',
	'Mostrar valores',
	'En la caja de abajo, puede ingresar cualquier consulta (select...)',
	'Puede también cargar otras consultas (.sql) hechas con Agata.',
	'Edición de SubSql',
	'Volver',
	'Nombre del proyecto',
	'No hay resultados',
	'Archivo',
	'Ejecutar',
	'Herramientas',
	'Importar',
	'Tipo',
	
	'Estructura de las tablas',
	'Sobre',
	'Funciones comunes',
	'Funciones de la BD',
	'Ordenamiento',
	'Transferir',
	'Grupo',
	'Grupos',
	'Reiniciar',
	'Campos',
	'Funciones',
	'Acción',
	'Fórmula',
	'Fórmulas',
	'Esta tabla no pertenece a la base de datos',
	'Columna',
	'Nivel',
	'Count',
	'Sum',
	'Mostrar grupos de columnas',
	'Insertar',
	'Parámetros',
	'Ingrese arriba los parámetros de la consulta'
    ),

    'en' => array(
        'Tables',
        'Field Names',
        'Selection',
        'Links',
        'Constraints',
        'Author',
        'Execute Query',
        'Export TXT',
        'Export PS',
        'Load SQL',
        'Save SQL',
        'Close Window',
        'Block',
        'Content',
        'Table Name',
        'Require Tables',
        'IT Department',
        'Development by',
        'Fields of Selected Table',
        'Select field, please',
        'Ascendant Order',
        'Descendant Order',
        'Clear Select',
        'Clear Order',
        'Average',
        'Minimal',
        'Maximal',
        'Group by Select',
        'Open SQL File',
        'Save to SQL File',
        'Save to PS File',
	'Save to PDF File',
        'Save to TXT File',
	'Save to HTML File',
	'Save to XML File',
	'Save to CSV File',
        'Expression',
        'Please type a expression',
        'Clear Where',
        'Query Result',
        'Query Error',
        'Mark Tables to proceed the Selection',
        'Type of Selection on Field',
        'Link Tables',
        'Rules, Constraints of Select',
        'Some informations about developmnent',
        'Unexpected Error, Unknown Cause',
        'Wait a moment.',
        'Message',
        'Close',
        'Question',
        'Type the Report Name',
        'Cannot connect to Database',
        'File Error',
        'Click on line to edit the content',
        'Add',
        'Edit',
        'Delete',
        'Clear',
        'List Edition',
        'New Item',
        'Edit Item',

        'Up',
        'Down',
        'Write',
        'DataBase Connection Setup',
        'Database Host/SID/DSN',
        'Database Name',
        'User',
        'Password',
        'Language',
        'Database type',
        'Viewer for PostScript',
	'Viewer for PDF',
        'Viewer for Text Files',
        'Viewer for XML Files',
        'Merge with Doc',
        'Choose Document',
        'See also THANKS file',
        'System Help',
        'Loaded from config.php',
        'Merge Tool',
        'Merge',
        'Load File',
        'Save File',
        'Merge to PS',
        'New PS File',
        'New TXT File',
        'Fonts',
        'Special Controls',
        'Line height',
        'Copyright',
        'Line number',
        'Page Number',
        'Print',
        'Please, Insert Lines and Fonts in separated lines',
        'It does not control break lines automatically',
        'Commented Line',
        'Line Space',
        'Please, Load an SQL file on main screen',
        'Paragraph',
        'Spaniard',
        'Registered',
        'SubQuery Session',
        'Page',
        'End of SubQuery',
        'HowTo: SubQueries',
        'You must insert a SubQuerySession',
        'Insert $subfield1, $subfield2 and so on, all in one line',
        'this variables above will be converted into SubQuery results',
        'This line with SubQuery variables will be replicated according with SubSql results',
        'Insert EndOfSubQuery',
	
	'Configuration',
	'Precision',
	'Thousand Separator',
	'Decimal Separator',
	'Date Format',
	'DateTime Format',
	'Report Configuration',
	'Here you may type your free select',
	'Orientation',
	'PostScript Line Lenght',
	'Saved Reports',
	'Saved Queries',
	'Tools',
	'Create Diagram',
	'Clear Query',
	'Type the Diagram Name',
	'Viewer for Diagrams',
	'Theme',
	'Label Tool',
	'Saved Labels',
	'Left Margin',
	'Top Margin',
	'Require Tables, please',
	'You Have to build the SQL Query firstly',
	'Import',
	'Import DBF',
	'Import CSV',
	'Dbase support is not enabled',
	'It is not a DBF File',
	'DBF Columns',
	'Destinated Columns',
	'Generate Graph',
	'Title',
	'Help',
	'Introduction',
	'Queries',
	'Per lines',
	'Per columns',
	'Generate',
	'Lines Graph',
	'Bars Graph',
	'Pizza Graph',
	'Extension not loaded',
	'Output',
	'There is no numeric data on query',
	'Dimension',
	'Spread Sheet',
	'Dimensions too small',
	'Delimiter',
	'Font Color',
	'Border Color',
	'Wait a moment',
	'Select fields of both columns',
	'Result',
	'You have to link the columns',
	'There are no columns to view',
	'Graph+data',
	'Show Values',
	'In this box below, you can type any query (select...).',
	'You can also load another queries (.sql) built with Agata.',
	'SubSql Edition',
	'Back',
	'Project Name',
	'No Result',
	'File',
	'Run',
	'Tools',
	'Import',
	'Type',
	
	'Table Structure',
	'About',
	'Common Functions',
	'DB Functions',
	'Ordering',
	'Transfer',
	'Group',
	'Groups',
	'Reset',
	'Fields',
	'Functions',
	'Action',
	'Formula',
	'Formulas',
	'This table does not belong to this database',
	'Column',
	'Level',
	'Count',
	'Sum',
	'Show Group Columns',
	'Insert',
	'Parameters',
	'Type the query parameters above',
	
	'DB Error: syntax error',
	'Select Description',
	'general',
	'Spacing between cells',
	'Spacing within cells',
	'Table Alignment',
	'Table Width',
	'Table Border',
	'Table Background Color',
	'Title Font',
	'Title Color',
	'Title Background Color',
	'Data Font',
	'Data Color',
	'Data Background Color',
	'Total Font',
	'Total Color',
	'Total Background Color',
	'Group Font',
	'Group Color',
	'Group Background Color',
	'Column Font',
	'Column Color',
	'Column Background Color',
	'Font',
	'Size',
	'Style',
	'Color Selection',
 	'Font Selection',
	'Show Detail',
	'CSV Delimiter',
	'GD support is not enabled',
	'Agata Directory',
	'New Query',
	'Yes',
	'No',
	'Query not saved, Do you really want to continue ?',
	'Do you really want to delete ?',
	'Show total labels',
	'Output Directory',
	'SQL Directory',
	'Differentiate lines by color',
	'Database connected',
	'Select a project',
	'All Tables',
	'Query',
	'Apply Function',
	'Apply',
	'Select this column',
	'Sort this column',
	'Repository',
	'Do you want to open this report ?',
	'This action will create a group',
	'Automatic link',
	'These table does not belong to this database',
	'Table Families',
	'Families',
	'Linking Settings',
	'General',
	'Family',
	'Select items from both lists',
	'Classify',
	'Number of rows in Diagrams',
	'Show link lines',
	'Distance Between Lines',
	'Distance Between Columns',
	'Distance Between Levels',
	'Table OffSet',
	'Create Folder',
	'Open',
	'Folder Name',
	'Report tag',
	'Title tag',
	'Header tag',
	'Header-row tag',
	'Header-column tag',
	'Data tag',
	'Data-row tag',
	'Data-column tag',
	'Footer tag',
	'Total-row tag',
	'Total-column tag',
	'Group tag',
	'Set Group',
	'Master-Detail Reports',
	'Report Levels',
	'Grand Total' ,
	'Data Description',
	'Data Structure',
	'Data',
	'Description',
	'Fill all the required fields',
	'Cannot remove the file',
	'Cannot remove the directory',
	'Loaded from projects directory',
	'Extras',
	'Save as',
	'Load Database Structure',
	'Selected Tables',
	'Choose the tables',
	'Plotted Columns',
	'Legend',
	'Select a Legend, please',
	'Select columns to plot',
	'Year',
	'Month',
	'Day',
	'Month Name',
	'Week Day',
	'January',
	'February',
	'March',
	'April',
	'May',
	'June',
	'July',
	'August',
	'September',
	'October',
	'November',
	'December',
	'Sunday',
	'Monday',
	'Tuesday',
	'Wednesday',
	'Thursday',
	'Friday',
	'Saturday',
	'Node',
	'Tab Stop at column ^1',
	'SubField ^1',
	'Not allowed'
    ),

    //
    // brazilian portuguese messages
    //

    'pt' => array(
        'Tabelas',
        'Nome dos campos',
        'Seleção',
        'Ligações',
        'Restrições',
        'Autor',
        'Executa SQL',
        'Gera TXT',
        'Gera PS',
        'Carrega SQL',
        'Salva SQL',
        'Fecha Janela',
        'Cláusula',
        'Conteúdo',
        'Nome da Tabela',
        'Solicita Tabelas',
        'Centro de Processamento de Dados',
        'Desenvolvido por',
        'Campos da Tabela Selecionada',
        'Selecione o campo.',
        'Ordem Ascendente',
        'Ordem Descendente',
        'Limpa o Select',
        'Limpa o Order',
        'Média',
        'Mínimo',
        'Máximo',
        'Agrupa por Select',
        'Abrir arquivo SQL',
        'Salvar como arquivo SQL',
        'Salvar como arquivo PS',
	'Salvar como arquivo PDF',
        'Salvar como arquivo TXT',
	'Salvar como arquivo HTML',
	'Salvar como arquivo XML',
	'Salvar como arquivo CSV',
        'Expressão',
        'Digite uma expressão',
        'Limpa Where',
        'Resultado da Pesquisa',
        'Erro na Pesquisa',
        'Maque as Tabelas para continuar a seleção',
        'Tipo de seleção do campo',
        'Ligar Tabelas',
        'Regras e Restrições do Select',
        'Informações sobre o desenvolvimento',
        'Erro inesperado, Causa desconhecida',
        'Aguarde um momento',
        'Mensagem',
        'Fechar',
        'Questão',
        'Nome do Relatório',
        'Erro ao Conectar Base de Dados',
        'Erro ao criar arquivo',
        'Clique na linha para editar o conteúdo',
        'Adicionar',
        'Editar',
        'Deletar',
        'Limpar',
        'Edição de Lista',
        'Novo Item',
        'Edita Item',

        'Cima',
        'Baixo',
        'Grava',
        'Configuração do Acesso ao Banco',
        'IP do Banco de Dados',
        'Nome do Banco de Dados',
        'Usuario do Banco',
        'Senha',
        'Linguagem',
        'Tipo de Banco de Dados',
        'Visualizador para PostScript',
	'Visualizador para PDF',
        'Visualizador para Texto',
        'Visualizador para XML',
        'Mesclar para Documento',
        'Escolha o Documento',
        'Leia tambem o arquivo THANKS',
        'Ajuda',
        'Lido apartir do config.php',
        'Ferramenta de Mesclagem',
        'Mesclagem',
        'Abrir Arquivo',
        'Salvar Arquivo',
        'Mesclar para PostScript',
        'Novo PostScript',
        'Novo TXT',
        'Fontes',
        'Controles Especiais',
        'Altura Linha',
        'Copyright',
        'Numero de Linha',
        'Paginacao',
        'Imprimir',
        'Atencao, Insira Linhas e Fontes em linhas separadas',
        'Agata nao controla quebra de linhas automaticamente',
        'Linha comentada',
        'Espacamento',
        'Atencao, carregue um SQL na tela principal',
        'Paragrafo',
        'Spaniard',
        'Registered',
        'Secao SubPesquisa',
        'Pagina',
        'Final da SubPesquisa',
        'Ajuda: SubPesquisas',
        'Voce deve inserir uma Sessao SubPesquisa',
        'Insira $subfield1, $subfield2 e assim por diante, tudo em uma linha',
        'As variaveis acima serao convertidas por resultados da SubPesquisa',
        'Essa linha com as variaveis da SubPesquisa sera replicada de acordo com os resultados',
        'Insira EndOfSubQuery',

	'Configuração',
	'Precisão',
	'Separador de Milhar',
	'Separador Decimal',
	'Formato de Data',
	'Formato DataHora',
	'Configuração do Relatório',
	'Aqui você pode digitar um select à mão livre',
	'Orientação',
	'Comprimento de Linha (PostScript)',
	'Relatórios Salvos',
	'Consultas Salvas',
	'Ferramentas',
	'Criar Diagrama',
	'Limpar Consulta',
	'Digite o nome do diagrama',
	'Visualizador para diagramas',
	'Tema',
	'Gerador de Etiquetas',
	'Etiquetas Salvas',
	'Margem Esquerda',
	'Margem Topo',
	'Solicite alguma tabela',
	'Faça alguma pesquisa primeiro',
	'Importa',
	'Importa DBF',
	'Importa CSV',
	'Suporte ao Dbase não habilitado',
	'Não é um arquivo DBF',
	'Colunas DBF',
	'Colunas destino',
	'Gerar Gráfico',
	'Título',
	'Ajuda',
	'Introdução',
	'Pesquisas',
	'Por Linhas',
	'Por Colunas',
	'Gerar',
	'Gráfico de Linhas',
	'Gráfico de Barras',
	'Gráfico de Pizza',
	'Extensão não carregada',
	'Resultado',
	'Não há dados numéricos na pesquisa',
	'Dimensão',
	'Planilha',
	'Dimensões muito pequenas',
	'Delimitador',
	'Cor da fonte',
	'Cor da Borda',
	'Aguarde um momento',
	'Selecione campos de ambas colunas',
	'Resultado',
	'É necessário ligar as colunas',
	'Não há colunas para serem visualizadas',
	'Grafico+dados',
	'Exibir valores',
	'Na caixa abaixo, você pode digitar qualquer pesquisa (select...).',
	'Você pode também carregar outras pesquisas (.sql) feitas com o Agata',
	'Edição de SubSql',
	'Voltar',
	'Nome do Projeto',
	'Sem Resultado',
	'Arquivo',
	'Executar',
	'Ferramentas',
	'Importar',
	'Tipo',
	
	'Estrutura da Tabela',
	'Sobre',
	'Funções Comuns',
	'Funções do BD',
	'Ordenação',
	'Transferir',
	'Grupo',
	'Grupos',
	'Reset',
	'Campos',
	'Funções',
	'Ação',
	'Formula',
	'Formulas',
	'Tabela de outro Banco de Dados',
	'Coluna',
	'Nível',
	'Count',
	'Sum',
	'Mostrar Colunas de Grupo',
	'Inserir',
	'Parâmetros',
	'Digite acima os parâmetros da consulta',
	
	'Erro de sintáxe',
	'Descrição do Select',
	'geral',
	'Espaço entre células',
	'Espaço dentro das células',
	'Alinhamento da tabela',
	'Largura da Tabela',
	'Borda da Tabela',
	'Cor de fundo da tabela',
	'Fonte do título',
	'Cor do título',
	'Cor de fundo do título',
	'Fonte dos dados',
	'Cor dos dados',
	'Cor de fundo dos dados',
	'Fonte dos totais',
	'Cor dos totais',
	'Cor do fundo dos totais',
	'Fonte do grupo',
	'Cor do grupo',
	'Cor de fundo do grupo',
	'Fonte do título da coluna',
	'Cor do título da coluna',
	'Cor de fundo do título da coluna',
	'Fonte',
	'Tamanho',
	'Estilo',
	'Seleção de cor',
	'Seleção de fonte',
	'Exibir detalhes',
	'Delimitador CSV',
	'Suporte à GD não está habilitado',
	'Diretório do Agata',
	'Nova Pesquisa',
	'Sim',
	'Não',
	'Pesquisa não salva, Deseja continuar ?',
	'Deseja realmente apagar ?',
	'Exibir rótulos de total',
	'Diretório de Saída para relatórios',
	'Diretório pesquisas SQL',
	'Diferenciar linhas pela cor',
	'Banco de Dados conectado',
	'Selecione um projeto',
	'Todas Tabelas',
	'Consulta',
	'Aplicar Função',
	'Aplicar',
	'Seleciona esta coluna',
	'Ordena por esta coluna',
	'Repositório',
	'Você deseja abrir este relatório ?',
	'Esta ação irá formar um grupo',
	'Ligação automática',
	'Esta(s) tabela(s) não pertencem à este banco de dados',
	'Famílias de Tabelas',
	'Famílias',
	'Ligações entre tabelas',
	'Geral',
	'Família',
	'Selecione itens das duas listas',
	'Classificar',
	'Quantidade de linhas do diagrama',
	'Exibir linhas de ligação',
	'Distância entre linhas',
	'Distância entre colunas',
	'Distância entre níveis',
	'Margem da tabela',
	'Criar pasta',
	'Abrir',
	'Nome da pasta',
	'Etiquta de relatório',
	'Etiqueta de título',
	'Etiqueta de cabeçalho',
	'Etiqueta de linha de cabeçalho',
	'Etiqueta de coluna de cabeçalho',
	'Etiqueta de dados',
	'Etiqueta de linha de dados',
	'Etiqueta de coluna de dados',
	'Etiqueta de rodapé',
	'Etiqueta de linha de total',
	'Etiqueta de coluna de total',
	'Etiqueta de grupo',
	'Configurar Agrupamentos',
	'Relatórios Mestre-Detalhe',
	'Níveis do Relatório',
	'Grande Total',
	'Descrição dos dados',
	'Estrutura dos Dados',
	'Dados',
	'Descrição',
	'Preencha todos campos requisitados',
	'Impossível remover o arquivo',
	'Impossível remover a pasta',
	'Lido do diretório projects',
	'Extras',
	'Salvar como...',
	'Carregar estrutura do Banco de Dados',
	'Tabelas selecionadas',
	'Escolha as tabelas',
	'Colunas Projetadas',
	'Legenda',
	'Selecione uma legenda',
	'Selecione colunas para projetar',
	'Ano',
	'Mês',
	'Dia',
	'Nome do mês',
	'Dia da semana',
	'Janeiro',
	'Fevereiro',
	'Março',
	'Abril',
	'Maio',
	'Junho',
	'Julho',
	'Agosto',
	'Setembro',
	'Outubro',
	'Novembro',
	'Dezembro',
	'Domingo',
	'Segunda-feira',
	'Terça-feira',
	'Quarta-feira',
	'Quinta-feira',
	'Sexta-feira',
	'Sábado',
	'Nodo',
	'Tabulação na coluna ^1',
	'Subcampo ^1',
	'Não permitido'
    ),

    //
    // german messages
    //

    'de' => array(
        'Tabellen',
        'Feldnamen',
        'Auswahl',
        'Verweise',
        'Filter',
        'Author',
        'Abfrage ausführen',
        'TXT Exportieren',
        'PS Exportieren',
        'SQL Laden',
        'SQL Speichern',
        'Fenster schließen',
        'Block',
        'Inhalt',
        'Tabellenname',
        'Benötige Tabelle',
        'IT Abteilung',
        'Entwickelt von',
        'Felder der Tabelle',
        'Bitte ein Feld auswählen',
        'Reihenfolge Aufsteigend',
        'Reihenfolge Absteigend',
        'Abfrage zurücksetzen',
        'Sortierung zurücksetzen',
        'Durchschnitt',
        'Minimal',
        'Maximal',
        'Gruppierung',
        'SQL Datei öffnen',
        'In SQL Datei speichern',
        'In PS Datei speichern',
	'In PDF Datei speichern',
        'In TXT Datei speichern',
	'In HTML Datei speichern',
	'In XML Datei speichern',
	'In CSV Datei speichern',
        'Ausdruck',
        'Bitte einen Ausdruck eingeben',
        'Filter zurücksetzen',
        'Abfrage-Ergebnis',
        'Abfrage-Fehler',
        'Tabellen auswählen um mit der Abrage fortzufahren',
        'Feld-Typ wählen',
        'Tabellen verginden',
        'Abfrage-Filter',
        'Einige Informationen über die Programm-Entwicklung',
        'Unerwarteter Fehler (Ursache unbekannt)',
        'Bitte einen Moment warten',
        'Mitteilung',
        'Schließen',
        'Frage',
        'Name des Berichtes',
        'Fehler bei Verbindung zur Datenbank',
        'Fehler beim Erstellen der Datei',
        'Auf Zeile klicken um Inhalt zu editieren',
        'Hinzu(fügen)',
        'Ändern',
        'Löschen',
        'Leeren',
        'Liste bearbeiten',
        'Neu(er Eintrag)',
        'Ändern',

        'Auf',
        'Ab',
        'Schreiben',
        'Koonfiguration Verbindung',
        'IP Addresse Datenbank',
        'Name Datenbank',
        'Benutzername',
        'Passwort',
        'Sprache',
        'Typ Datenbank',
        'Viewer für Postscript',
	'Viewer für PDF',
        'Viewer für Text',
        'Viewer für XML',
        'Mit Doc zusammenfügen',
        'Dokument wählen',
        'Siehe auch Datei THANKS',
        'System-Hilfe',
        'Geladen aus config.php',
        'Hilfsprogramm Zusammenführung',
        'Zusammenführung',
        'Datei laden',
        'Datei speichern',
        'Zusammenführung in PS',
        'Neue PS Datei',
        'Neue TXT Datei',
        'Fonts',
        'Besondere Kontrollzeichen',
        'Zeilenhöhe',
        'Copyright',
        'Zeilennummer',
        'Seitennummer',
        'Drucken',
        'Bitte Linien und Fonts in separaten Zeilen einfügen',
        'Agata führt Zeilenumbrüche nicht automatisch durch',
        'Kommentierte Zeile',
        'Leerzeile',
        'Bitte eine SQL Datei in das Hauptfenster laden',
        'Absatz',
        'Spaniard',
        'Registriert',
        'Unterabfrage Sitzung',
        'Seite',
        'Ende Unterabfrage',
        'HowTo: Unterabfragen',
        'Sie müssen eine Unterabfrage Sitzung einfügen',
        'Bitte so einfügen $subfield1, $subfield2 usw., alles in einer Zeile',
        'die obenstehenden Variablen werden in Unterabfrage-Ergebnisse umgewandelt',
        'Diese Zeile mit Unterabfrage-Variablen wird entsprechend der Anzahl der Zeilen im Unterabfrage-Resultat wiederholt',
        'Einfügen EndOfSubQuery',
        
	'Koonfiguration',
	'Präzision',
	'Tausendertrennzeichen',
	'Dezimaltrennzeichen',
	'Datumsformat',
	'Datum-/Zeitformat',
	'Berichtkonfiguration',
	'Beliebigen SELECT Befehl eingeben',
	'Ausrichtung',
	'PostScript Linienlänge',
	'Gespeicherte Berichte',
	'Gespeicherte Abfragen',
	'Werkzeuge',
	'Diagramm erstellen',
	'Abfrage löschen',
	'Diagrammnamen eingeben',
	'Diagrammanzeige',
	'Thema',
	'Werkzeug für Feldnamen',
	'Gespeicherte Feldnamen',
	'Linker Rand',
	'Oberer Rand',
	'Benötigt Tabellen, bitte',
	'Zuerst die SQL Abfrage zusammenstellen',
	'Importieren',
	'Importieren DBF',
	'Importieren CSV',
	'DBase Unterstützung nicht vorhanden',
	'Dies ist keine DBF Datei',
	'DBF Spalten',
	'Ausgabespalten',
	'Grafik erstellen',
	'Titel',
	'Hilfe',
	'Einführung',
	'Abfragen',
	'per Zeilen',
	'per Spalten',
	'Generieren',
	'Linen Grafik',
	'Balken Grafik',
	'Pizza Grafik',
	'Erweiterung nicht geladen',
	'Ausgabe',
	'Abfrage liefert keine numerischen Daten',
	'Abmessung',
	'Spread Sheet',
	'Abmessung zu klein',
	'Trennzeichen',
	'Font Farbe',
	'Rahmen Farbe',
	'Bitte einen Moment warten',
	'Felder beider Spalten wählen',
	'Ergebnis',
	'Die Spalten müssen verbunden werden',
	'Es gibt keine Spalten zur Anzeige vorhanden',
	'Grafik+Daten',
	'Werte anzeigen',
	'In das folgende Feld kann eine beliebige Abfrage (select...) eingegeben werden',
	'Es können ebenfalls andere Abfragen (.sql) geladen werden, welche mit Agata erstellt wurden',
	'SubSql Bearbeiten',
	'Zurück',
	'Projektname',
	'Kein Ergebnis',
	'Datei',
	'Ausführen',
	'Werkzeuge',
	'Importieren',
	'Feld-Typ',
	
	'Tabellen-Struktur',
	'Uber',
	'Allgemeine Funktionen',
	'DB Funktionen',
	'Sortierung',
	'Ubertragung',
	'Gruppierung',
	'Gruppierungen',
	'Zurucksetzen',
	'Felder',
	'Funktionen',
	'Aktion',
	'Formel',
	'Formeln',
	'Diese Tabelle gehort nicht zu dieser Datenbank',
	'Spalte',
	'Ebene',
	'Anzahl',
	'Summe',
	'Gruppierungsspalten anzeigen',
	'Einfugen',
	'Parameter',
	'Abfrage Parameter oben eingeben'
	
    ),

    //
    // french messages
    //

    'fr' => array(
        'Tables',
        'Nom des Champs',
        'Sélection',
        'Liens',
        'Contraintes',
        'Auteur',
        'Executer SQL',
        'Exporter TXT',
        'Exporter PS',
        'Ouvrir SQL',
        'Enregistrer SQL',
        'Quitter',
        'Clause',
        'Contenu',
        'Nom des Tables',
        'Sélectionner ces tables',
        'Service Technique',
        'Développement par',
        'Champs de la table sélectionnée',
        'Merci de sélectionner un champ',
        'Ordre croissant',
        'Ordre décroissant',
        'Effacer Select',
        'Effacer Order',
        'Moyenne',
        'Minimum',
        'Maximum',
        'Group By',
        'Ouvrir fichier SQL',
        'Enregistrer dans un fichier SQL',
        'Enregistrer dans un fichier PS',
	'Enregistrer dans un fichier PDF',
        'Enregistrer dans un fichier TXT',
	'Enregistrer dans un fichier HTML',
	'Enregistrer dans un fichier XML',
	'Enregistrer dans un fichier CSV',
        'Expression',
        'Merci de tapez une expression',
        'Effacer Where',
        'Résultat de la requête',
        'Erreur de requête',
        'Sélectionnez les Tables pour continuer',
        'Type de sélection',
        'Lier les Tables',
        'Règles, Contraintes de sélection',
        'Informations importantes sur le développement',
        'Erreur inattendue, Cause inconnue',
        'Patientez un instant',
        'Message',
        'Fermer',
        'Question',
        'Tapez le nom du rapport',
        'Connexion à la base impossible',
        'Erreur de fichier',
        'Cliquez sur la ligne pour éditer le contenu',
        'AJOUTER',
        'Editer',
        'Supprimer',
        'Vider',
        'Edition de la liste',
        'Nouvel item',
        'Editer'
    ),

    'it' => array(
        'Tabelle',
        'Nomi dei Campi',
        'Selezione',
        'Riferimenti',
        'Filtri',
        'Autore',
        'Esegue Query',
        'Esporta TXT',
        'Esporta PS',
        'Carica SQL',
        'Salva SQL',
        'Chiude',
        'Blocco',
        'Contenuto',
        'Nome della Tabella',
        'Tabelle Necessarie',
        'Dipartimento IT',
        'Sviluppato da',
        'Campi delle Tabelel Selezionate',
        'Prego Selezionare il campo',
        'Ordine Ascendente',
        'Ordine Discendente',
        'Svuota la Selezione',
        'Svuota Ordine',
        'Media',
        'Minimo',
        'Massimo',
        'Raggruppa per Selezione',
        'Apre un file SQL',
        'Salva in File SQL',
        'Salva in File PS',
	'Salva in File PDF',
        'Salva in File TXT',
	'Salva in File HTML',
	'Salva in File XML',
	'Salva in File CSV',
        'Espressione',
        'Prego inserire una espressione',
        'Svuota le Condizioni',
        'Risultato della Query',
        'Errore nella Query',
        'Marcare le Tabelle per procedere alla Selezione',
        'Tipo di Selezione nel Campo',
        'Link Tables',
        'Ruoli e Riferimenti della Selezione',
        'Alcune informazioni sullo sviluppo',
        'Errore inatteso, Causa Sconosciuta',
        'Attendere un Attimo.',
        'Messaggio',
        'Chiude',
        'Domanda',
        'Inserire il Nome del Rapporto',
        'Impossibile collegarsi al Database',
        'Errore nel File',
        'Clickare sulla linea per cambiarne il contenuto',
        'Aggiungi',
        'Cambia',
        'Cancella',
        'Svuota',
        'List Edition',
        'Nuovo Oggetto',
        'Cambia Oggetto',

        'sù',
        'giù',
        'scrive',
        'Configurazione Connessioni Database',
        'Indirizzo IP del Database',
        'Nome del Database',
        'Nome Utente',
        'Password',
        'Lingua',
        'Tipo di Database',
        'Visualizzatore per PostScript',
	'Visualizzatore per PDF',
        'Visualizzatore per Files di Testo',
        'Visualizzatore per Files XML',
        'Incorpora in Doc',
        'Scegliere il Documento',
        'Guardare anche il file THANKS (Ringraziamenti)',
        'Aiuto di Sistema',
        'Caricato da config.php',
        'Strumento di Incorporazione',
        'Incorpora',
        'Carica un File',
        'Salva un File',
        'Incorpora in PS',
        'Nuovo File PS',
        'Nuovo File TXT',
        'Caratteri',
        'Controlli Speciali',
        'Altezza della Linea',
        'Diritto di Stampa',
        'Numero della Linea',
        'Numero della Pagina',
        'Stampa',
        'Prego Inserire Righe e Caratteri su righe separate',
        'Non taglia automaticamente le righe',
        'Riga Commentata',
        'Spaziatura',
        'Prego Caricare un file SQL sulla schermata principale',
        'Paragrafo',
        'Spagnolo',
        'Registrato',
        'Sessione SottoQuery',
        'Pagina',
        'Fine della SottoQuery',
        'Come fare: SottoQueries',
        'Devi inserire una Sessione SottoQuery',
        'Inserisci $sottocampo1, $sottocampo2 e così via, tutto in una riga',
        'le variabili sopra saranno convertite in risultati di SottoQuery',
        'Questa Riga con variabili di SottoQuery saranno replicate in accordo con i risultati della SottoSQL',
        'Inserisci Fine della SottoQuery (EndOfSubQuery)',
        
	'Configurazione',
	'Precisione',
	'Separatore delle migliaia',
	'Sseparatore dei decimali',
	'Formato della data',
	'Formato di data e ora',
	'Configurazione stampa',
	'Qui puoi scrivere la tua select libera',
	'Orientamento',
	'lunghezza della linea postscript',
	'report salvati',
	'queries salvate',
	'Strumenti',
	'Crea diagramma',
	'Azzera query',
	'Scrivere il nome del diagramma',
	'Visualizzatore per i diagrammi',
	'Tema',
	'Strumento etichette',
	'Etichette salvate',
	'Margine sinistro',
	'Margine superiore',
	'Tabelle richieste, prego',
	'Devi prima creare la query sql',
	'Importa',
	'Importa DBF',
	'Importa CSV',
	'Il supporto per dbase non è abilitato',
	'Non è un file dbf',
	'colonne dbf',
	'colonne destinate',
	'Genera grafico',
	'Titolo',
	'Aiuto',
	'Introduzione',
	'Queries',
	'Per linee',
	'Per colonne',
	'Genera',
	'Grafico a linee',
	'Grafico a barre',
	'Grafico a pie',
	'Estensione non caricata',
	'Risultato',
	'non ci sono dati numerici sulla query',
	'Dimensione',
	'Foglio di calcolo',
	'Dimensioni troppo piccole',
	'Delimitatore',
	'Colore del carattere',
	'Colore del bordo',
	'attendere un momento',
	'Seleziona i campi su entrambi le colonne',
	'Risultato',
	'devi collegare le colonne',
	'Non ci sono colonne da visualizzare',
	'dati + grafico',
	'mostra i valori',
	'nella casella sotto puoi scrivere una query (select ... )',
	'puoi inoltre caricare altre queries (.sql) create con Agata',
	'Edizione SubSql',
	'indietro',
	'nome del progetto',
	'nessun risultato',
	'File',
	'Esegui',
	'Strumenti',
	'Importa',
	'Tipo',
	
	'Struttura della tabella',
	'informazioni',
	'funzioni comuni',
	'funzioni db',
	'ordinamento in corso',
	'trasferimento',
	'Grupo',
	'Grupos',
	'Azzeramento',
	'Campi',
	'Funzioni',
	'Azione',
	'Formula',
	'Formule',
	'Questa tabella non appartiene a questo database',
	'Colonna',
	'Livello',
	'Conteggio',
	'Somma',
	'Mostra colonne gruppo',
	'Inserisci',
	'Parametri',
	'Scrivi sopra i parametri della query',

	'errore nel DB: errore di sintassi',
	'descrizione della select',
	'generale',
	'spaziatura tra le celle',
	'spaziatura all\'interno delle celle',
	'allineamento della tabella',
	'larghezza della tabella',
	'bordo della tabella',
	'colore di fondo della tabella',
	'carattere del titolo',
	'colore del titolo',
	'colore di fondo del titolo',
	'carattere dei dati',
	'colore dei dati',
	'colore di fondo dei dati',
	'carattere dei totali',
	'colore dei totali',
	'colore di fondo dei totali',
	'carattere raggruppamento',
	'colore raggruppamento',
	'colore di fondo del raggruppamento',
	'carattere testata colonna',
	'colore testata colonna',
	'colore di fondo testata colonna',
	'carattere',
	'dimensioni',
	'stile',
	'selezione colore',
	'selezione carattere',
	'mostra dettagli',
	'delimitatore csv',
	'supporto GD non abilitato',
	'Directory di Agata',
	'Nuova Query',
	'Si',
	'No',
	'Query non salvata, vuoi veramente continuare ?',
	'Vuoi veramente cancellare ?',
	'Mostra etichette dei totali',
	'Directory per risultati',
	'Directory per SQL',
	'Differenzia linee con colore',
	'Database connesso',
	'Seleziona un progetto',
	'Tutte le tabelle',
	'Query',
	'Applica funzione',
	'Applica',
	'Seleziona questa colonna',
	'Ordina per questa colonna',
	'Deposito',
	'Vuoi aprire questo report ?',
	'Questa azione creera un raggruppamento',
	'Collega automaticamente',
	'Questa tabella non appartiene a questo database',
	'Famiglie della tabella',
	'Famiglie',
	'Configurazione collegamenti',
	'Generale',
	'Famiglia',
	'Seleziona un oggetto da entrambe le liste',
	'Classifica',
	'Numero di righe nei diagrammi',
	'mostra linee di collegamento',
	'distanza tra linee',
	'distanza tra colonne',
	'distanza tra livelli',
	'margine tabella',
	'crea foglio',
	'apri',
	'nome foglio',
	'tag di report',
	'tag di titolo',
	'tag di intestazione',
	'tag di intestazione riga',
	'tag di intestazione colonna',
	'tag di dati',
	'tag di riga dati',
	'tag di colonna dati',
	'tag di piede',
	'tag di riga totali',
	'tag di colonna totali',
	'tag di gruppo',
	'imposta gruppi',
	'report testata - dettaglio',
	'livelli del report',
	'totale generale',
	'descrizione dei dati',
	'struttura dei dati',
	'dati',
	'descrizione',
	'riempi tutti i campi richiesti',
	'impossibile cancellare il file',
	'impossibile cancellare la directory',
	'caricate dalla directory dei progetti',
	'extra',
	'salva come',
	'carica struttura database',
	'tabelle selezionate',
	'scegli le tabelle',
	'colonne stampate',
	'legenda',
	'prego seleziona una legenda',
	'seleziona le colonne da stampare',
	'anno',
	'mese',
	'giorno',
	'nome del mese',
	'giorno della settimana',
	'gennaio',
	'febbraio',
	'marzo',
	'aprile',
	'maggio',
	'giugno',
	'luglio',
	'agosto',
	'settembre',
	'ottobre',
	'novembre',
	'dicembre',
	'domenica',
	'lunedi',
	'martedi',
	'mercoledi',
	'giovedi',
	'venerdi',
	'sabato',
	'nodo',
	'ferma tabulazione alla colonna ^1',
	'sotto campo ^1',
	'Non permessa'
    ),

    'se' => array(
        'Tabeller',
        'Fältnamn',
        'Urval',
        'Länkar',
        'Restriktioner',
        'Upphovsman',
        'Exekvera förfrågan',
        'Exportera till TXT',
        'Exportera till PS',
        'Ladda SQL',
        'Spara SQL',
        'Stäng fönster',
        'Block',
        'Innehåll',
        'Tabellnamn',
        'Kräv Tabeller',
        'IT Avdelningen',
        'Utveckling av',
        'Fält i vald Tabell',
        'Välj fält, tack',
        'Stigande Sortering',
        'Fallande Sortering',
        'Rensa Select',
        'Rensa Sortering',
        'Genomsnitt',
        'Minimal',
        'Maximal',
        'Group by Select',
        'Öppna SQL-fil',
        'Spara SQL fil',
        'Spara till PS-fil',
	'Spara till PDF-fil',
        'Spara till TXT-fil',
	'Spara till HTML-fil',
	'Spara till XML-fil',
	'Spara till CSV-fil',
        'Uttryck',
        'Var god skriv ett utrryck',
        'Rensa Where',
        'Query Result',
        'Query Error',
        'Markera tabeller för att fortsätta med urvalet',
        'Typ av urval på fältet',
        'Länka Tabeller',
        'Regler, Restriktioner i Select',
        'Information om utveckling',
        'Oväntat fel, okänd anledningn',
        'Ett ögonblick.',
        'Meddelande',
        'Stäng',
        'Fråga',
        'Skriv rapportens namn',
        'Kan inte ansluta till Databasen',
        'Fil Error',
        'Clicka på linjen för att editera innehållet',
        'Lägg till',
        'Editera',
        'Ta bort',
        'Rensa',
        'Lista Upplaga',
        'Ny post',
        'Editera post',

        'Upp',
        'Ner',
        'Skriv',
        'Databasinställningar',
        'Databasens IP-adress',
        'Databasens Namn',
        'Användare för anslutning',
        'Lösenord för anslutning',
        'Språk',
        'Databastyp',
        'Program för att visa PostScript-filer',
	'Program för att visa PDF-filer',
        'Program för att visa Text-filer',
        'Program för att visa XML-filer',
        'Förena med Doc',
        'Välj dokument',
        'Se även THANKS-filen',
        'Systemhjälp',
        'Laddad från config.php',
        'Föreningsverktyget',
        'Förena',
        'Öppna fil',
        'Spara fil',
        'Förena till PS',
        'Ny PS-fil',
        'Ny TXT-fil',
        'Fonter',
        'Speciella kontroller',
        'Linjehöjd',
        'Copyright',
        'Radnummer',
        'Sidnummer',
        'Skriv ut',
        'Var god sätt in rader och fonter på separerade rader',
        'Den radbryter inte automatiskt',
        'Bortkommenterad rad',
        'Radbrytning',
        'Var god ladda en SQL-fil i huvudfönstret',
        'Paragraf',
        'Spanjor',
        'Registrerad',
        'Underfrågssession',
        'Sida',
        'Slut på undefråga',
        'HowTo: Underfrågor',
        'Du måste lägga till en underfrågssession',
        'Infoga $subfield1, $subfield2 och så vidare, på en rad',
        'variablerna ovan kommer bli konverterade till underfrågsresultat',
        'Denna rad med underfrågsvariabler kommer bli replikerad enligt SubSql-resultaten.',
        'Infoga EndOfSubQuery',
	
	'Konfiguration',
	'Precision',
	'Thousand Separator',
	'Decimal Separator',
	'Date Format',
	'DateTime Format',
	'Rapportkonfiguration',
	'Here you may type your free select',
	'Orientering',
	'PostScript radlängd',
	'Sparade Rapporter',
	'Sparade Queries',
	'Verktyg',
	'Skapa Diagram',
	'Rensa Query',
	'Skriv in Diagramnamnet',
	'Visare för Diagram',
	'Tema',
	'Etikettverktyg',
	'Sparade etiketter',
	'Vänstermarginal',
	'Toppmarginal',
	'Require Tables, please',
	'Du måste bygga SQL-queryn först',
	'Importera',
	'Importera DBF',
	'Importera CSV',
	'Dbase support är inte aktiverat',
	'Det är ej en DBF-fil',
	'DBF Kolumner',
	'Destinated Columns',
	'Generera grafik',
	'Titel',
	'Hjälp',
	'Introduktion',
	'Queries',
	'Per rad',
	'Per kolumn',
	'Generera',
	'Lines Graph',
	'Bars Graph',
	'Pizza Graph',
	'Extension not loaded',
	'Utdata',
	'There is no numeric data on query',
	'Dimension',
	'Spread Sheet',
	'Dimensions too small',
	'Avgränsare',
	'Typsnittsfärg',
	'Ramfärg',
	'Ett ögonblick',
	'Select fields of both columns',
	'Resultat',
	'Du måste länka kolumnerna',
	'Det finns inga kolumner att visa',
	'Grafik+data',
	'Visa värden',
	'I denna box nedan kan du skriva alla typer av queries (select...).',
	'Du kan också ladda andra queries (.sql) skrivna i Agata.',
	'SubSql Edition',
	'Tillbaka',
	'Projektnamn',
	'Inget resultat',
	'Fil',
	'Kör',
	'Verktyg',
	'Importera',
	'typ',
	
	'Tabellstruktur',
	'om',
	'Vanliga funktioner',
	'DB Funktioner',
	'Beställa',
	'Överför',
	'Grupo',
	'Grupos',
	'Nollställ',
	'Fält',
	'Funktioner',
	'Acción',
	'Formel',
	'Formler',
	'Denna tabell tillhör inte den denna databasen',
	'Kolumn',
	'Nivå',
	'Count',
	'Sum',
	'Mostrar grupos de columnas',
	'Insert',
	'Parametrar',
	'Skriv förfrågninsparametrarna ovan',

	'DB Error: felaktig syntax',
	'Välj beskrivning',
	'allmänt',
	'Avstånd mellan celler',
	'Avstånd inom celler',
	'Tabellens placering',
	'Tabellens bredd',
	'Tabellens kant',
	'Tabellens bakgrundsfärg',
	'Rubrikens typsnitt',
	'Rubrikens färg',
	'Rubrikens bakgrundsfärg',
	'Datans typsnitt',
	'Datans färg',
	'Datans bakgrundsfärg',
	'Summeringens typsnitt',
	'Summeringens färg',
	'Summeringens bakgrundsfärg',
	'Grupperingens typsnitt',
	'Grupperingens färg',
	'Grupperingens bakgrundsfärg',
	'Kolumnernas typsnitt',
	'Kolumnernas färg',
	'Kolumnernas bakgrundsfärg',
	'Typsnitt',
	'Storlek',
	'Typ',
	'Färgurval',
	'Typsnittsurval',
	'Visa detaljer',
	'CSV Avgränsare',
	'GD-stöd är ej aktiverat',
	'Agatas sökväg',
	'Ny fråga',
	'Ja',
	'Nej',
	'Frågan är inte sparad, vill du fortsätta ändå?',
	'Vill du verkligen ta bort ?',
	'Visa totaletiketter',
	'Sökväg där utdata sparas',
	'Sökväg där SQL-frågorna sparas',
	'Särskilj raderna med färg',
	'Databas ansluten',
	'Välj projekt',
	'Alla tabeller',
	'SQL-Fråga',
	'Tillämpa funktion',
	'Använd',
	'Välj denna kolumn',
	'Sortera denna kolumn',
	'Förvaringsplats',
	'Vill du öppna den här rapporten?',
	'Detta kommer gruppera',
	'Länka automatiskt',
	'Dessa tabeller hör inte till den här databasen',
	'Tabellfamiljer',
	'Familjer',
	'Länkinställningar',
	'Allmänt',
	'Familj',
	'Välj poster från båda listorna',
	'Klassificera',
	'Antal rader i diagram',
	'Visa länklinjer',
	'Avstånd mellan linjer',
	'Avstånd mellan kolumner',
	'Avstånd mellan nivåer',
	'Tabellutjämning',
	'Ny mapp',
	'Öppna',
	'Mappnamn',
	'Beteckning på rapport',
	'Beteckning på titel',
	'Beteckning på rubrik',
	'Beteckning på rubrikrad',
	'Beteckning på rubrikkolumn',
	'Beteckning på data',
	'Beteckning på datarad',
	'Beteckning på datakolumn',
	'Beteckning på sidfot',
	'Beteckning på totalrad',
	'Beteckning på totalkolumn',
	'Beteckning på grupp',
	'Fastställ Grupp',
	'Master-Detail Rapport',
	'Rapportera nivåer',
	'Grand Total',
	'Databeskrivning',
	'Datastruktur',
	'Data',
	'Beskrivning',
	'Fyll i alla obligatoriska fält',
	'Kan inte ta bort filen',
	'Kan inte ta bort mappen',
	'Inladdat från projektmappen',
	'Tillägg',
	'Spara som',
	'Ladda databasstruktur',
	'Markerade tabeller',
	'Välj tabeller',
	'Valda kolumner',
	'Legend',
	'Select a Legend, please',
	'Välj kolumner att rita',
	'År',
	'Månad',
	'Dag',
	'Månadsnamn',
	'Veckodag',
	'Januari',
	'Februari',
	'Mars',
	'April',
	'Maj',
	'Juni',
	'Juli',
	'Augusti',
	'September',
	'Oktober',
	'November',
	'December',
	'Söndag',
	'Måndag',
	'Tisdag',
	'Onsdag',
	'Torsdag',
	'Fredag',
	'Lördag',
	'Nod',
	'Tabstopp vid kolumn ^1',
	'Delfält ^1',
	'Inte tillåtet'
     )
 );


  var $language = 'en';

  /**
   *  A common used technique is, to keep a default instance
   *  for shared classes. In this case, the global variable
   *  $Language has become a member variable of this class,
   *  which is more consistent from the OO point of view.
   *
   *  Calling this method will return the default instance.
   *  If the default instance does not exist, it will be
   *  created.
   *
   *  One defect of PHP is, that it does not allow static
   *  class member variables - thus we have to use a common
   *  global to hold the default instance ;-)
   */
  function & GetDefaultInstance()
  {
    global $__default_trans_instance;

    if ( ! $__default_trans_instance )
    {
      $__default_trans_instance = new Trans();
    }

    return $__default_trans_instance;
  }

  /**
   *  The translate method takes a string $msg and three
   *  optional positional parameters ($p1,$p2,$p3). The
   *  positional parameters will substitute occurrencies
   *  of the form ^1, ^2 and ^3 contained in the string.
   *
   *  Positional parameters are useful, to include parameters
   *  like filenames or others. In different languages, it is
   *  likely, that the position changes:
   *
   *    'the _white_ dog'   vs.   'o cachorro _branco_'
   */
  function Translate($msg,$p1=null,$p2=null,$p3=null)
  {
    $inst = & Trans::GetDefaultInstance();

    //
    // $nls will become our localized message, if one would
    // be found. Otherwise, it will become the original message
    // prepended by an underscore to notify, that a localized
    // message is missing.
    //

    $nls = $msg;

    if ( $inst->language != 'en' )
    {
      $nls = $msg;

      if ( is_array($inst->messages[$inst->language]) )
      {
        $i = 0;

        foreach ( $inst->messages['en'] as $m )
        {
          if ( $m == $msg )
          {
            $m = $inst->messages[$inst->language][$i];

            if ( $m )
            {
              $nls = $m;
              break;
            }
          }

          $i++;
        }
      }
    }

    //
    // substitute positional parameters if necessary
    //

    if ( $p1 != null )
      $nls = str_replace('^1',$p1,$nls);

    if ( $p2 != null )
      $nls = str_replace('^2',$p2,$nls);

    if ( $p3 != null )
      $nls = str_replace('^3',$p3,$nls);

    return $nls;
  }

  /**
   *  returns the currently selected language identifier
   */
  function GetLanguage()
  {
    $inst = & Trans::GetDefaultInstance();

    return $inst->language;
  }

  /**
   *  switches to another language. If the specified language
   *  is not defined, an error message is generated
   */
  function SetLanguage($lang, $showMsg = tru)
  {
    $inst = & Trans::GetDefaultInstance();

    if ( ! $inst->messages[$lang] )
    {
      if ($showMsg)
        Dialog::Aviso("Language '$lang' is not supported!");
      return false;
    }

    $inst->language = $lang;
    return true;
  }

  /**
   *  for testing and demonstrating the new features
   */
  function Dump()
  {
    $inst = & Trans::GetDefaultInstance();

    $old_lang = Trans::GetLanguage();

    //
    // dumps mapping of all available messages except the default ones
    //

    foreach( array_keys($inst->messages) as $l )
    {
      if ( $l == 'en' )
        continue;

      $inst->language = $l;

      echo "<table bgcolor=#999999 cellspacing=1 cellpadding=2 width=100%>\n";
      echo "<tr><td colspan=3 align=center><font color=white><b>Current language is '$l'</b></font></td></tr>\n";

      foreach ( $inst->messages['en'] as $m )
        echo "<tr><td width=50% bgcolor=#efefef><i>$m</i></td>"
             ."<td align=center bgcolor=#ffefef>&nbsp;=&gt;&nbsp;</td>"
             ."<td width=50% bgcolor=#ffffef>" . _T($m) . "</td></tr>\n";

      echo "</table>\n";
      echo "<br>\n";
    }

    Trans::SetLanguage($old_lang);

    //
    // positional parameters test
    //

    $samples = array(
                      array( 'The numbers are ^1, ^2 and ^3', array('one','two','three') ),
                      array( 'Little boys like ^2 and little girls like ^1 ...', array('dolls','cars') ),
                      array( '... and when they become older, ^1 like ^2 and ^2 like ^1', array('boys','girls') )
                    );

    echo "<table bgcolor=#999999 cellspacing=1 cellpadding=2 width=100%>\n";
    echo "<tr><td colspan=3 align=center><font color=white><b>Postional Parameters</b></font></td></tr>\n";

    foreach ( $samples as $s )
    {
      $m = $s[0];

      list ( $p1, $p2, $p3 ) = $s[1];

      echo "<tr><td width=50% bgcolor=#efefef><i>$m</i></td>"
           ."<td align=center bgcolor=#ffefef>&nbsp;=&gt;&nbsp;</td>"
           ."<td width=50% bgcolor=#ffffef>" . _T($m,$p1,$p2,$p3) . "</td></tr>\n";
    }

    echo "</table>\n";
    echo "<br>\n";

    Trans::SetLanguage('xyz');
  }
}

// a shorthand for Trans::Translate()

//function _T($e,$p1=null,$p2=null,$p3=null) { return Trans::Translate($e,$p1,$p2,$p3); }

// a test run

//Trans::Dump();

//--> new words

// 'DB Error: syntax error'
// 'Select Description'
// 'general'
// 'Spacing between cells'
// 'Spacing within cells'
// 'Table Alignment'
// 'Table Width'
// 'Table Border'
// 'Table Background Color'
// 'Title Font'
// 'Title Color'
// 'Title Background Color'
// 'Data Font'
// 'Data Color'
// 'Data Background Color'
// 'Total Font'
// 'Total Color'
// 'Total Background Color'
// 'Group Font';
// 'Group Color';
// 'Group Background Color';
// 'Column Font';
// 'Column Color';
// 'Column Background Color';
// 'Font'
// 'Size'
// 'Style'
// 'Color Selection'
// 'Font Selection'
// 'Show Detail' -> it's the same that 'show the content lines of report... and not just the totalization lines'...
// 'CSV Delimiter'
// 'GD support is not enabled'
// 'Agata Directory'
// 'New Query'
// 'Yes'
// 'No'
// 'Query not saved, Do you really want to continue ?'
// 'Do you really want to delete ?'
// 'Show total labels' -> it's the same that 'show a litle label in front of totalization lines in order to identificate the referenced column'
// 'Output Directory';
// 'SQL Directory';
// 'Merged Documents Directory';
// 'Graphs Directory';
// 'Labels Directory
// 'Differentiate lines by color'
// 'Database connected'
// 'Select a project'
// 'All Tables'
// 'Query'
// 'Apply Function'
// 'Apply'
// 'Select this column'
// 'Sort this column'
// 'Repository'
// 'Do you want to open this report ?'
// 'This action will create a group'
// 'Automatic link'
// 'These table does not belong to this database'
// 'Table Families'
// 'Families'
// 'Linking Settings'
// 'General'
// 'Family'
// 'Select items from both lists'
// 'Classify'
// 'Number of rows in Diagrams'
// 'Show link lines'
// 'Distance Between Lines';
// 'Distance Between Columns';
// 'Distance Between Levels'
// 'Table OffSet'
// 'Create Folder'
// 'Open'
// 'Folder Name'
// 'Report tag'
// 'Title tag'
// 'Header tag'
// 'Header-row tag'
// 'Header-column tag'
// 'Data tag'
// 'Data-row tag'
// 'Data-column tag'
// 'Footer tag'
// 'Total-row tag'
// 'Total-column tag'
// 'Group tag'
// 'Set Group'
// 'Master-Detail Reports'
// 'Report Levels'
// 'Grand Total' 
// 'Data Description'
// 'Data Structure'
// 'Data'
// 'Description'
// 'Fill all the required fields'
// 'Cannot remove the file'
// 'Cannot remove the directory'
// 'Loaded from projects directory'
// 'Extras'
// 'Save as'
// 'Load Database Structure'
// 'Selected Tables'
// 'Choose the tables'
// 'Plotted Columns'
// 'Legend'
// 'Select a Legend, please'
// 'Select columns to plot'
// 'Year'
// 'Month'
// 'Day'
// 'Month Name'
// 'Week Day'
// 'January'
// 'February'
// 'March'
// 'April'
// 'May'
// 'June'
// 'July'
// 'August'
// 'September'
// 'October'
// 'November'
// 'December'
// 'Sunday'
// 'Monday'
// 'Tuesday'
// 'Wednesday'
// 'Thursday'
// 'Friday'
// 'Saturday'
// 'Node'
// 'Tab Stop at column ^1'
// 'SubField ^1'
// 'Not allowed'
?>
