dojo.provide("mywidgets.widget.Timezones");

mywidgets.widget.timezones = [
	{name:"International Date Line West", sn:"Dateline", offset:-720, dst:0, standard:0},
	{name:"Midway Island, Samoa", sn:"Samoa", offset:-660, dst:0, standard:0},
	{name:"Hawaii", sn:"Hawaiian", offset:-600, dst:0, standard:0},
	{name:"Alaska", sn:"Alaskan", offset:-540, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Pacific Time (US & Canada); Tijuana", sn:"Pacific", offset:-480, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Mountain Time (US & Canada)", sn:"Mountain", offset:-420, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Chihuahua, La Paz, Mazatlan", sn:"Mexico%202", offset:-420, dst:"5,1,1", standard:"9,-1,1"},
	{name:"Arizona", sn:"US%20Mountain", offset:-420, dst:0, standard:0},
	{name:"Central Time (US & Canada)", sn:"Central", offset:-360, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Guadalajara, Mexico City, Monterrey", sn:"Mexico", offset:-360, dst:"4,1,1", standard:"9,-1,1"},
	{name:"Central America, Saskatchewan", sn:"Central%20America/Canada%20Central", offset:-360, dst:0, standard:0},
	{name:"Eastern Time (US & Canada)", sn:"Eastern", offset:-300, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Indiana (East), Bogota, Lima, Quito", sn:"US%20Eastern/SA%20Pacific", offset:-300, dst:0, standard:0},
	{name:"Atlantic Time (Canada)", sn:"Atlantic", offset:-240, dst:"4,1,1", standard:"10,-1,1"},
	{name:"Santiago", sn:"Pacific%20SA", offset:-240, dst:"10,2,7", standard:"3,2,7"},
	{name:"Caracas, La Paz", sn:"SA%20Western", offset:-240, dst:0, standard:0},
	{name:"Newfoundland", sn:"Newfoundland", offset:-210, dst:"4,1,1", standard:"10,-1,1"},
	{name:"Brasilia", sn:"E.%20South%20America", offset:-180, dst:"10,3,1", standard:"2,2,1"},
	{name:"Greenland", sn:"Greenland", offset:-180, dst:"4,1,1", standard:"10,-1,1"},
	{name:"Buenos Aires, Georgetown", sn:"SA%20Eastern", offset:-180, dst:0, standard:0},
	{name:"Mid-Atlantic", sn:"Mid-Atlnatic", offset:-120, dst:"3,-1,1", standard:"9,-1,1"},
	{name:"Azores", sn:"Azores", offset:-60, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Cape Verde Is.", sn:"Cape%20Verde", offset:-60, dst:0, standard:0},
	{name:"Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London", sn:"GMT", offset:0, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Casablanca, Monrovia", sn:"Greenwich", offset:0, dst:0, standard:0},
	{name:"Central European", sn:"Western/Central%20Europe", offset:60, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"West Central Africa", sn:"W.%20Central%20Africa", offset:60, dst:0, standard:0},
	{name:"Eastern European", sn:"Eastern%20Europe", offset:120, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Cairo", sn:"Egypt", offset:120, dst:"5,1,6", standard:"9,-1,4"},
	{name:"Jerusalem, Harare, Pretoria", sn:"Israel/South%20Africa", offset:120, dst:0, standard:0},
	{name:"Moscow, St. Petersburg, Volgograd", sn:"Russian", offset:180, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Baghdad", sn:"Arabic", offset:180, dst:"4,1,1", standard:"10,1,1"},
	{name:"Kuwait, Riyadh, Nairobi", sn:"Arab/E.%20Africa", offset:180, dst:0, standard:0},
	{name:"Tehran", sn:"Iran", offset:210, dst:"3,1,1", standard:"9,4,3"},
	{name:"Baku, Tbilisi, Yerevan", sn:"Caucasus", offset:240, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Abu Dhabi, Muscat", sn:"Arabian", offset:240, dst:0, standard:0},
	{name:"Kabul", sn:"Afghanistan", offset:270, dst:0, standard:0},
	{name:"Ekaterinburg", sn:"Ekaterinburg", offset:300, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Islamabad, Karachi, Tashkent", sn:"West%20Asia", offset:300, dst:0, standard:0},
	{name:"Chennai, Kolkata, Mumbai, New Delhi", sn:"India", offset:330, dst:0, standard:0},
	{name:"Kathmandu", sn:"Nepal", offset:345, dst:0, standard:0},
	{name:"Almaty, Novosibirsk", sn:"N.%20Central%20Asia", offset:360, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Astana, Dhaka, Sri Jayawardenepura", sn:"Central%20Asia/Sri%20Lanka", offset:360, dst:0, standard:0},
	{name:"Rangoon", sn:"Myanmar", offset:390, dst:0, standard:0},
	{name:"Bangkok, Hanoi, Jakarta", sn:"SE%20Asia", offset:420, dst:0, standard:0},
	{name:"Krasnoyarsk", sn:"North%20Asia", offset:420, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Beijing, Taipei, Singapore, Perth", sn:"China/Singapore/Taiwan/W.%20Australia", offset:480, dst:0, standard:0},
	{name:"Irkutsk, Ulaan Bataar", sn:"North%20Asia%20East", offset:480, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Seoul, Tokyo", sn:"Japan/Korea", offset:540, dst:0, standard:0},
	{name:"Yakutsk", sn:"Yakutsk", offset:540, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Adelaide", sn:"Cen.%20Australia", offset:570, dst:"10,-1,1", standard:"3,-1,1"},
	{name:"Darwin", sn:"AUS%20Central", offset:570, dst:0, standard:0},
	{name:"Canberra, Melbourne, Sydney", sn:"AUS%20Eastern", offset:600, dst:"10,-1,1", standard:"3,-1,1"},
	{name:"Vladivostok", sn:"Vladivostok", offset:600, dst:"3,-1,1", standard:"10,-1,1"},
	{name:"Hobart", sn:"Tasmania", offset:600, dst:"10,1,1", standard:"3,-1,1"},
	{name:"Brisbane, Guam, Port Moresby", sn:"E.%20Australia/West%20Pacific", offset:600, dst:0, standard:0},
	{name:"Magadan, Solomon Is., New Caledonia", sn:"Central%20Pacific", offset:660, dst:0, standard:0},
	{name:"Auckland, Wellington", sn:"New%20Zealand", offset:720, dst:"10,1,1", standard:"3,3,1"},
	{name:"Fiji, Kamchatka, Marchall Is.", sn:"Fiji", offset:720, dst:0, standard:0},
	{name:"Nuku\'alofa", sn:"Tonga", offset:780, dst:0, standard:0}
];