<?
define ('images', 'interface' . bar);
define ('IMAGEBUTTON', 4);
define ('ICONBUTTON',  5);
define ('TOPBUTTON',  6);
define ('isGui', true);
define ('BREAKLN', "\n");
define ("K_ENTER", 65293);
define ("K_ESC", 65307);
define ("K_SPACE", 32);
define ("K_F1", 65470);
define ("K_F2", 65471);
define ("K_F3", 65472);
define ("K_F4", 65473);
define ("K_TAB", 65289);
define ('XMLHEADER', "<?xml version=\"1.0\"?>\n");
?>
