<?
# SPECIAL CHARS
$sup1  = chr(185);
$sup2  = chr(178);
$sup3  = chr(179);
$supo  = chr(186);
$supa  = chr(170);
$s14   = chr(188);
$s12   = chr(189);
$s34   = chr(190);
$reco  = chr(174);
$copy  = chr(169);
$ster  = chr(163);
$para  = chr(167);
$iesp  = chr(191);
$pi    = chr(182);
$mame  = chr(177);
$filename = $this->FileName;

# DATE AND TIME
$year = date('Y');
$month = date('m');
$day = date('d');
$monthname = _a(trim(date('F')));
$weekday = _a(trim(date('l')));
$time = _a(trim(date("H:i:s")));
?>
