#!/bin/bash
#  cfg-value
#  -- returns the config value from global.var.inc, for use with non-PHP
#  -- languages. to be run as "scripts/cfg-value (value-to-return, no $)"
#  -- (ex)  scripts/cfg-value packagename   would be "freemed"....

OURPATH="/usr/share/freemed"
GLOBALVARFILE="lib/freemed.php"

#if [ -f $GLOBALVARFILE ]; then
#  GLOBALVARFILE="../freemed.php";
#fi

cat $OURPATH/$GLOBALVARFILE | grep "define ('$1" | awk -F\" '{ print $2 } ' | cat
