#!/bin/bash
# $Id$
#
# Authors:
#      Jeff Buchbinder <jeff@freemedsoftware.org>
#
# Copyright (C) 1999-2011 FreeMED Software Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

OURPATH="$(dirname "$0")"
CFGVALUE=${OURPATH}/cfg-value
CURRENTDATE=$(date +%Y%m%d)

# Extract all neccessary variables from lib/freemed.php
DB_NAME=$(${CFGVALUE} DB_NAME)
DB_USER=$(${CFGVALUE} DB_USER)
DB_PASS=$(${CFGVALUE} DB_PASS)

# MySQL backup with bzip2 compression
mysqldump \
	--single-transaction \
	--user=${DB_USER} \
	--password=${DB_PASS} \
	${DB_NAME} \
	| bzip2 -qc > ${OURPATH}/data/backup/freemed.backup.${CURRENTDATE}.bz2


