#!/usr/bin/perl -w
# $Id$
#
# Authors:
#      Jeff Buchbinder <jeff@freemedsoftware.org>
#
# FreeMED Electronic Medical Record and Practice Management System
# Copyright (C) 1999-2008 FreeMED Software Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# Auto-detect the path for libraries and the FreeMED install
use FindBin;
use lib "$FindBin::Bin/../lib/perl";
my $rootpath = "$FindBin::Bin/..";

use XML::RAX;

my $file = shift or die("$0 inputfile > outputfile");

my $h = new XML::RAX();
$h->openfile($file);

# Print header ... for now, we fake most of it
$h->setRecord('information');
my $headers = $h->readRecord();
print "# This file is automatically generated by GettextXML utilities\n";
print "#\n";
print "msgid \"\"\n";
print "msgstr \"\"\n";
print "\"MIME-Version: 1.0\\n\"\n";
print "\n";

# Translate records
my $r = new XML::RAX();
$r->openfile($file);
$r->setRecord('translation');
while (my $rec = $r->readRecord()) {
	if ($rec->getField('original') =~ /\n/) {
		my @lines = split(/\n/, $rec->getField('original'));
		print "msgid \"\"\n";
		foreach my $line (@lines) {
			print "\"".$line."\"\n";
		}
	} else {
		print "msgid \"".$rec->getField('original')."\"\n";
	}
	if ($rec->getField('translated') =~ /\n/) {
		my @lines = split(/\n/, $rec->getField('translated'));
		print "msgstr \"\"\n";
		foreach my $line (@lines) {
			print "\"".$line."\"\n";
		}
	} else {
		print "msgstr \"".$rec->getField('translated')."\"\n";
	}
	print "\n";
}

